// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → csu-northridge · cs.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/csu-northridge/facts/cs.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California State University, Northridge · COMPUTER SCIENCE, B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=42&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F42%2FMajor%2Fbffba4e5-6c72-46bf-425c-08dda831fbe0 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · COMP 282: cell absent from articulations
//   · COMP 222: cell absent from articulations
//   · MATH 262: cell absent from articulations
//   · PHIL 230: cell absent from articulations
export const REQ_ECC_CSU_NORTHRIDGE_CS: RequirementSet = {
  school: "csu-northridge",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California State University, Northridge, COMPUTER SCIENCE, B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=42&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F42%2FMajor%2Fbffba4e5-6c72-46bf-425c-08dda831fbe0",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: false,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "Computer Science AS-T",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "Computer Science AS-T",
      notes: "CSUN's ADT matching table lists the Computer Science ADT as matching \"BS - Computer Science - General\" — the degree modeled here. Caveat on the sending side: not every California community college offers the Computer Science AS-T (Mount San Antonio College, one of the 20 colleges modeled here, does not list it), so availability must be checked at the student's own college. Computer Science is not impacted at CSUN.",
    },
    campusImpacted: "none — CSUN is not campus-impacted for transfers. For BOTH 2026-2027 and 2027-2028 exactly two majors are impacted: the B.A. in Cinema and Television Arts (Film Production and Television Production options only) and the B.A. in Music (audition). No other major carries supplementary criteria (verified 2026-08-19).",
    localAdmissionArea: "None in effect. CSUN states that local/nonlocal-area (regional) impaction \"is no longer in effect\" for 2026-2027 and 2027-2028 — every first-time transfer applicant meets the same standard CSU criteria, and Table 1 of the transfer-impaction page sets one minimum admission GPA (2.00) for a California community college \"Anywhere in California\". There is therefore no local-area advantage or penalty from any of the 20 sending colleges modeled here (verified 2026-08-19). Historical note: CSUN did operate a local-area 0.10 GPA bump in earlier cycles; that is retired.",
    sourceUrl: "https://www.csun.edu/admissions-financial-aid/how-to-apply/impaction/transfer-impaction",
  },
  majorPrep: [
    {
      id: "math-150b",
      label: "Calculus II (MATH 150B)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "comp-182",
      label: "Data Structures and Program Design (COMP 182) [series COMP 182+COMP 182L]",
      options: ["CSCI 2"],
      required: true,
    },
    {
      id: "comp-122",
      label: "Computer Architecture and Assembly Language (COMP 122) [series COMP 122+COMP 122L]",
      options: ["CSCI 16"],
      required: true,
    },
    {
      id: "comp-256",
      label: "Discrete Structures for Computer Science (COMP 256) [series COMP 256+COMP 256L]",
      options: ["MATH 210"],
      required: true,
    },
    {
      id: "math-150a",
      label: "Calculus I (MATH 150A)",
      options: ["MATH 190"],
      required: true,
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "comp-110",
      label: "Introduction to Algorithms and Programming (COMP 110) [series COMP 110+COMP 110L]",
      options: ["CSCI 1"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for LOWER DIVISION MAJOR PREPARATION COURSES.", count: 1, memberId: "g2-o1" },
    },
    // ASSIST row note: Option 1 of 3
    {
      id: "biol-106",
      label: "Biological Principles I (BIOL 106) [series BIOL 106+BIOL 106L]",
      options: ["BIOL 120"],
      required: false,
      group: { id: "g3-opt", label: "Complete one of the 3 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g3-o1" },
    },
    // ASSIST row note: Option 2 of 3
    {
      id: "biol-107",
      label: "Biological Principles II (BIOL 107) [series BIOL 107+BIOL 107L]",
      options: ["BIOL 110"],
      required: false,
      group: { id: "g3-opt", label: "Complete one of the 3 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g3-o2" },
    },
    // ASSIST row note: Option 3 of 3
    {
      id: "geol-110-p1",
      label: "The Fossil Record of Ancient Life on Earth (GEOL 110) [series GEOL 110+GEOL 112] — part 1 of 2 (complete all)",
      options: ["GEOL 4"],
      required: false,
      group: { id: "g3-opt", label: "Complete one of the 3 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g3-o3" },
    },
    // ASSIST row note: Option 3 of 3
    {
      id: "geol-110-p2",
      label: "The Fossil Record of Ancient Life on Earth (GEOL 110) [series GEOL 110+GEOL 112] — part 2 of 2 (complete all)",
      options: ["GEOL 2"],
      required: false,
      group: { id: "g3-opt", label: "Complete one of the 3 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g3-o3" },
    },
    // ASSIST row note: Option 1 of 6
    {
      id: "chem-101",
      label: "General Chemistry I (CHEM 101) [series CHEM 101+CHEM 101L+CHEM 101D]",
      options: ["CHEM 1A"],
      required: false,
      group: { id: "g4-opt", label: "Complete one of the 6 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g4-o1" },
    },
    // ASSIST row note: Option 2 of 6
    {
      id: "geog-101-p1",
      label: "The Physical Environment (GEOG 101) [series GEOG 101+GEOG 102] — part 1 of 2 (complete all)",
      options: ["GEOG 6"],
      required: false,
      group: { id: "g4-opt", label: "Complete one of the 6 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g4-o2" },
    },
    // ASSIST row note: Option 2 of 6
    {
      id: "geog-101-p2",
      label: "The Physical Environment (GEOG 101) [series GEOG 101+GEOG 102] — part 2 of 2 (complete all)",
      options: ["GEOG 1"],
      required: false,
      group: { id: "g4-opt", label: "Complete one of the 6 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g4-o2" },
    },
    // ASSIST row note: Option 3 of 6
    {
      id: "geog-103",
      label: "Weather (GEOG 103) [series GEOG 103+GEOG 105]",
      options: ["GEOG 9"],
      required: false,
      group: { id: "g4-opt", label: "Complete one of the 6 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g4-o3" },
    },
    // ASSIST row note: Option 4 of 6
    {
      id: "geol-101-p1",
      label: "Geology of Planet Earth (GEOL 101) [series GEOL 101+GEOL 102] — part 1 of 2 (complete all)",
      options: ["GEOL 1"],
      required: false,
      group: { id: "g4-opt", label: "Complete one of the 6 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g4-o4" },
    },
    // ASSIST row note: Option 4 of 6
    {
      id: "geol-101-p2",
      label: "Geology of Planet Earth (GEOL 101) [series GEOL 101+GEOL 102] — part 2 of 2 (complete all)",
      options: ["GEOL 3"],
      required: false,
      group: { id: "g4-opt", label: "Complete one of the 6 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g4-o4" },
    },
    // ASSIST row note: Option 3 of 3
    {
      id: "geol-110-p1-2",
      label: "The Fossil Record of Ancient Life on Earth (GEOL 110) [series GEOL 110+GEOL 112] — part 1 of 2 (complete all)",
      options: ["GEOL 4"],
      required: false,
      group: { id: "g4-opt", label: "Complete one of the 6 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g4-o5" },
    },
    // ASSIST row note: Option 3 of 3
    {
      id: "geol-110-p2-2",
      label: "The Fossil Record of Ancient Life on Earth (GEOL 110) [series GEOL 110+GEOL 112] — part 2 of 2 (complete all)",
      options: ["GEOL 2"],
      required: false,
      group: { id: "g4-opt", label: "Complete one of the 6 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g4-o5" },
    },
    // ASSIST row note: Option 6 of 6
    {
      id: "phys-220a",
      label: "Mechanics (PHYS 220A) [series PHYS 220A+PHYS 220AL]",
      options: ["PHYS 1A"],
      required: false,
      group: { id: "g4-opt", label: "Complete one of the 6 options for SCIENCE ELECTIVE WITH LAB.", count: 1, memberId: "g4-o6" },
    },
  ],
};
