// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → csulb · cs.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/csu-long-beach/facts/cs.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California State University, Long Beach · Computer Science · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=81&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F81%2FMajor%2F0827c64e-650f-4f76-3391-08ddb349963e (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · ENGR 102: cell absent from articulations
//   · CECS 277: Course(s) Denied
//   · CECS 105: cell absent from articulations
export const REQ_ECC_CSULB_CS: RequirementSet = {
  school: "csulb",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California State University, Long Beach, Computer Science",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=81&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F81%2FMajor%2F0827c64e-650f-4f76-3391-08ddb349963e",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2.5,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "Computer Science AS-T (TMC 2007) — deemed similar to the CSULB Computer Science B.S. (General), effective Fall 2012",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "Computer Science AS-T (TMC 2007) — deemed similar to the CSULB Computer Science B.S. (General), effective Fall 2012",
      notes: "The Computer Science AS-T is deemed similar to this major at CSULB, so the ADT carries the full benefit — worth contrasting with Cal Poly Pomona, which maps the same ADT to Science, Technology & Society rather than its CS B.S. How CSULB uses an ADT: it counts only when the ADT is deemed \"similar\" to the CSULB major applied to, and the student applies to that major. When it is similar, the ADT curriculum is used IN LIEU OF the major-specific degree requirements, the cumulative GPA is increased by 0.1 (applied both to the major-specific minimum GPA and to the ranking of applicants), and the bachelor's is completable in 60 further units. The ADT must be granted no later than the prior Spring term for fall entry, or the prior Summer for spring entry; if it is not completed, CSULB re-evaluates and may withdraw the admission offer. CSULB does not publish the similarity list itself — it points students at their community-college transfer center — so the similarity facts here come from the CSU Chancellor's Office TMC similar-major database (2,649 rows across all 22 universities; dataset SiteAssets/tmcData.js?v=20260817 behind https://www.calstate.edu/attend/degrees-certificates-credentials/Pages/TMC-Search.aspx), read 2026-08-19. Sources: https://www.csulb.edu/admissions/associate-degree-transfer-program-adt and the college transfer-criteria page in factsSourceUrl.",
    },
    campusImpacted: "campus-wide — the CSU's official 2027-28 impaction listing names Cal State Long Beach among the universities where ALL undergraduate programs, pre-programs and undeclared/undecided programs are impacted, for first-time freshmen and upper-division transfers alike (https://www.calstate.edu/attend/degrees-certificates-credentials/Pages/impacted-degrees.aspx, read 2026-08-19); CSULB repeats it in its own ASSIST agreement header: \"ALL MAJORS ARE IMPACTED at California State University, Long Beach.\" CSULB then flags a smaller HIGHLY IMPACTED tier inside that — for the fall 2026 / spring 2027 cycle exactly three programs: Nursing BSN Basic, Nursing RN-to-BSN and Social Work. None of the 13 wired majors is highly impacted, so local preference is not suspended for them.",
    localAdmissionArea: "CSULB sets local preference by HIGH SCHOOL of graduation (named districts: ABC, Anaheim Union in part, Bellflower, Compton, Downey, Huntington Beach, Long Beach, Los Alamitos, Norwalk-La Mirada, Paramount, plus named private schools), by military-veteran status regardless of school, or — for transfers, new since fall 2025 — by completing the MAJORITY of units with the LAST school attended being one of five colleges: Long Beach City College, Cerritos College, Golden West College, Coastline Community College or Orange Coast College. Of the 20 sending colleges wired here, only Long Beach City, Cerritos and Orange Coast are local; the other 17 are non-local. This matters more than usual at CSULB: for a major that is NOT highly impacted (all 13 wired majors), a CSU-eligible LOCAL applicant who meets the major-specific minimum cumulative GPA and the required lower-division preparation \"will be offered admission\". Non-local applicants are admitted on a space-available basis, ranked by cumulative GPA and by how many of the additional recommended preparation courses they finished. A local applicant to a HIGHLY impacted major gets a +0.1 GPA increase instead of the guarantee. (https://www.csulb.edu/admissions/local-preference-admission-consideration, read 2026-08-19)",
    sourceUrl: "https://www.csulb.edu/admissions/fall-2026-transfer-major-specific-degree-requirements-hung-family-college-of-engineering",
  },
  majorPrep: [
    {
      id: "cecs-174",
      label: "Introduction to Programming and Problem Solving (CECS 174)",
      options: ["CSCI 14", "CSCI 3", "CSCI 1"],
      required: true,
    },
    {
      id: "cecs-274",
      label: "Data Structures (CECS 274)",
      options: ["CSCI 2"],
      required: true,
    },
    {
      id: "cecs-229",
      label: "Discrete Structures with Computing Applications II (CECS 229)",
      options: ["MATH 270"],
      required: true,
    },
    {
      id: "cecs-228",
      label: "Discrete Structures with Computing Applications (CECS 228)",
      options: ["MATH 210"],
      required: true,
    },
    {
      id: "cecs-225",
      label: "Digital Logic and Assembly Programming (CECS 225)",
      options: ["CSCI 16"],
      required: true,
    },
    {
      id: "engr-101",
      label: "Introduction to Engineering Profession (ENGR 101)",
      options: ["ENGR 1"],
      required: true,
    },
    {
      id: "math-123",
      label: "Calculus II (MATH 123)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "math-122",
      label: "Calculus I (MATH 122)",
      options: ["MATH 190"],
      required: true,
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "chem-111a",
      label: "General Chemistry (CHEM 111A)",
      options: ["CHEM 1A"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for SCIENCE ELECTIVES.", count: 1, memberId: "g2-o1" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "phys-151-p1",
      label: "Mechanics and Heat (PHYS 151) — part 1 of 2 (complete all)",
      options: ["PHYS 1A"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for SCIENCE ELECTIVES.", count: 1, memberId: "g2-o2" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "phys-151-p2",
      label: "Mechanics and Heat (PHYS 151) — part 2 of 2 (complete all)",
      options: ["PHYS 1B"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for SCIENCE ELECTIVES.", count: 1, memberId: "g2-o2" },
    },
    // ASSIST row note: Option 1 of 3
    {
      id: "biol-200",
      label: "General Biology (BIOL 200)",
      options: ["BIOL 10"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 3 options for ADDITIONAL SCIENCE SUPPORT ELECTIVES.", count: 1, memberId: "g3-o1" },
    },
    // ASSIST row note: Option 2 of 3
    {
      id: "biol-205",
      label: "Human Biology (BIOL 205)",
      options: ["ANAT 30"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 3 options for ADDITIONAL SCIENCE SUPPORT ELECTIVES.", count: 1, memberId: "g3-o2" },
    },
    // ASSIST row note: Option 3 of 3
    {
      id: "biol-207-c1",
      label: "Human Physiology (BIOL 207) — option set 1 of 2",
      options: ["PHYO 31", "APHY 34A"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 3 options for ADDITIONAL SCIENCE SUPPORT ELECTIVES.", count: 1, memberId: "g3-o3" },
    },
    // ASSIST row note: Option 3 of 3
    {
      id: "biol-207-c2",
      label: "Human Physiology (BIOL 207) — option set 2 of 2",
      options: ["PHYO 31", "APHY 34B"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 3 options for ADDITIONAL SCIENCE SUPPORT ELECTIVES.", count: 1, memberId: "g3-o3" },
    },
  ],
};
