// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → csu-northridge · business.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/csu-northridge/facts/business.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California State University, Northridge · BUSINESS ADMINISTRATION, B.S. - Option in Management · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=42&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F42%2FMajor%2F9cb62bb5-9d4d-4c77-4292-08dda831fbe0 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_CSU_NORTHRIDGE_BUSINESS: RequirementSet = {
  school: "csu-northridge",
  major: "business",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California State University, Northridge, BUSINESS ADMINISTRATION, B.S. - Option in Management",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=42&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F42%2FMajor%2F9cb62bb5-9d4d-4c77-4292-08dda831fbe0",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: false,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "Business Administration AS-T (the \"Business Administration 2.0\" TMC, which includes statistics)",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "Business Administration AS-T (the \"Business Administration 2.0\" TMC, which includes statistics)",
      notes: "CSUN's ADT matching table lists the Business Administration ADT as matching the B.S. Business Administration Management option — the option modeled here — along with Business Analytics, Business Law, Global Supply Chain Management, Pre-Finance, Real Estate, Systems and Operations Management, plus B.S. Consumer Sciences (Consumer Affairs) and B.A. Economics. CSUN's own footnote: from fall 2022 admission, only the newer \"Business Administration 2.0\" ADT (the one that includes statistics) matches the Marketing option.",
    },
    campusImpacted: "none — CSUN is not campus-impacted for transfers. For BOTH 2026-2027 and 2027-2028 exactly two majors are impacted: the B.A. in Cinema and Television Arts (Film Production and Television Production options only) and the B.A. in Music (audition). No other major carries supplementary criteria (verified 2026-08-19).",
    localAdmissionArea: "None in effect. CSUN states that local/nonlocal-area (regional) impaction \"is no longer in effect\" for 2026-2027 and 2027-2028 — every first-time transfer applicant meets the same standard CSU criteria, and Table 1 of the transfer-impaction page sets one minimum admission GPA (2.00) for a California community college \"Anywhere in California\". There is therefore no local-area advantage or penalty from any of the 20 sending colleges modeled here (verified 2026-08-19). Historical note: CSUN did operate a local-area 0.10 GPA bump in earlier cycles; that is retired.",
    sourceUrl: "https://www.csun.edu/admissions-financial-aid/how-to-apply/impaction/transfer-impaction",
  },
  majorPrep: [
    {
      id: "acct-220",
      label: "Introduction to Financial Accounting (ACCT 220)",
      options: ["BUS 150"],
      required: true,
    },
    {
      id: "econ-160",
      label: "Principles of Microeconomics (ECON 160)",
      options: ["ECON C2001"],
      required: true,
    },
    {
      id: "acct-230",
      label: "Introduction to Managerial Accounting (ACCT 230)",
      options: ["BUS 151"],
      required: true,
    },
    {
      id: "engl-205",
      label: "Business Communication in its Rhetorical Contexts (ENGL 205)",
      options: ["BUS 108"],
      required: true,
    },
    {
      id: "blaw-280",
      label: "Business Law I (BLAW 280)",
      options: ["LAW 5", "LAW 4"],
      required: true,
    },
    {
      id: "is-212",
      label: "Information Systems for Business Users (IS 212)",
      options: ["CIS 13"],
      required: true,
    },
    {
      id: "econ-161",
      label: "Principles of Macroeconomics (ECON 161)",
      options: ["ECON C2002"],
      required: true,
    },
    // ASSIST row note: Option 1 of 3
    {
      id: "math-150a",
      label: "Calculus I (MATH 150A)",
      options: ["MATH 190"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 3 options for CALCULUS.", count: 1, memberId: "g2-o1" },
    },
    // ASSIST row note: Option 2 of 3
    {
      id: "math-255a",
      label: "Calculus for the Life Sciences I (MATH 255A)",
      options: ["MATH 190", "MATH 165"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 3 options for CALCULUS.", count: 1, memberId: "g2-o2" },
    },
    // ASSIST row note: Option 3 of 3
    {
      id: "math-103",
      label: "Mathematical Methods for Business (MATH 103)",
      options: ["MATH 165"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 3 options for CALCULUS.", count: 1, memberId: "g2-o3" },
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "math-140bus",
      label: "Introductory Statistics for Business (MATH 140BUS)",
      options: ["STAT C1000", "STAT C1000H", "BUS 116"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 2 options for STATISTICS.", count: 1, memberId: "g3-o1" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "som-120",
      label: "Basic Business Statistics (SOM 120)",
      options: ["BUS 116"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 2 options for STATISTICS.", count: 1, memberId: "g3-o2" },
    },
  ],
};
