// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → san-diego-state · cs.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/san-diego-state/facts/cs.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → San Diego State University · Computer Science, B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=26&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F26%2FMajor%2F17a3686b-6292-4a45-f3f9-08ddd3b241a4 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · CS 240: No Course Articulated
//   · CS 210: cell absent from articulations
//   · CS 250: cell absent from articulations
//   · MATH 245: No Course Articulated
export const REQ_ECC_SAN_DIEGO_STATE_CS: RequirementSet = {
  school: "san-diego-state",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → San Diego State University, Computer Science, B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=26&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F26%2FMajor%2F17a3686b-6292-4a45-f3f9-08ddd3b241a4",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "Computer Science AS-T — SDSU maps it to the Computer Science B.S. (Computer Science – General), effective Fall 2014",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "Computer Science AS-T — SDSU maps it to the Computer Science B.S. (Computer Science – General), effective Fall 2014",
      notes: "SDSU’s own equivalence table lists \"Computer Science (AS-T) → Computer Science, B.S.\"; the CSU TMC dataset carries the matching San Diego row, effective Fall 2014. So the AS-T Computer Science carries full weight here — admission priority plus the 0.1 GPA cushion — which is the opposite of Cal Poly Pomona, where the same ADT is mapped to Science, Technology and Society rather than to the CS B.S. How an ADT works at SDSU: an ADT holder who applies to the SDSU major SDSU has approved as equivalent \"will be given admission priority\", and \"applicants using the ADT pathway for admission may be within .1 of the grade point average (GPA) required by the major to which they are applying\" — a 0.1 GPA cushion under the published minimum — \"however, a higher GPA may be required.\" The applicant must select the matching ADT major on Cal State Apply by November 30, 2026, submit the mandatory Academic History Update, have the community college eVerify the degree (or send the Verification of Intent form by March 15, 2027), and send a final transcript showing the ADT awarded. Sources: https://admissions.sdsu.edu/transfers/transfer-pathways (SDSU’s own AA-T/AS-T-to-SDSU-major equivalence table, read 2026-08-19) cross-checked against the CSU Chancellor’s Office TMC similar-degree dataset for campus \"San Diego\" (46 rows; SiteAssets/tmcData.js?v=20260817 behind https://www.calstate.edu/attend/degrees-certificates-credentials/Pages/TMC-Search.aspx, read 2026-08-19). The two sources agree on every one of the 13 majors wired here.",
    },
    campusImpacted: "campus-wide, and for upper-division transfers as well as first-time freshmen. The CSU Chancellor’s Office 2027-28 Undergraduate Impacted Programs Matrix (July 2026) says it verbatim: \"San Diego: Impacted for FTF and UDT, and in all undergraduate programs, pre-programs, and undeclared/undecided programs.\" (https://www.calstate.edu/attend/impaction-at-the-csu/Documents/ImpactedProgramsMatrix.pdf, read 2026-08-19). SDSU repeats it on its own transfer page: \"SDSU is impacted at the undergraduate level in all majors and programs. As such, we are unable to offer admission to all CSU eligible applicants.\" (https://admissions.sdsu.edu/transfers/minimum-requirements, page last updated 7/1/26). Because EVERY undergraduate program is impacted, impaction does not distinguish one SDSU major from another — the per-major minimum cumulative GPA does, and SDSU publishes one for every major.",
    localAdmissionArea: "SDSU sets its transfer local admissions area by the COMMUNITY COLLEGE attended, and the list is short: Cuyamaca, Grossmont, Imperial Valley, San Diego City, San Diego Mesa, San Diego Miramar and Southwestern. \"If you attend a community college in SDSU’s local admissions area, then you will receive priority consideration during the admission ranking process.\" NONE of the 20 sending colleges wired in this repo is on that list — Cerritos, Chaffey, College of the Canyons, De Anza, Diablo Valley, East Los Angeles, El Camino, Fullerton, Irvine Valley, Los Angeles Pierce, Long Beach City, Modesto Junior, Moorpark, Mount San Antonio, Orange Coast, Pasadena City, Riverside City, Saddleback, Santa Monica and Sierra are ALL non-local at SDSU. So every student this repo serves is a non-local applicant to a campus where every program is impacted: no local priority, no local guarantee, admitted on a space-available basis and \"ranked based on the extent to which they have completed the requirements\" — i.e. the ranking lever is finishing the 60 units, the Golden Four, the GE and the full major preparation early and with the highest GPA, not merely clearing the minimum. Two adjacent local routes also exclude these colleges: the SDCCD-SDSU Guaranteed Admissions Agreement (San Diego City, Mesa and Miramar only) and the Palomar/MiraCosta priority for programs CSU San Marcos does not offer. (The FIRST-YEAR local area is a different, geographic definition — a high school in San Diego County south of state route 56 extending east to the Imperial County line, or any high school in Imperial County — and does not apply to transfers.) Sources: https://admissions.sdsu.edu/local-admissions-area (read 2026-08-19; page last updated 11/14/25), https://admissions.sdsu.edu/transfers/transfer-pathways and https://admissions.sdsu.edu/_resources/pdf/tag-2027-fall.pdf (Enrollment Services, 7/2026).",
    sourceUrl: "https://admissions.sdsu.edu/transfers/gpa-requirements",
  },
  majorPrep: [
    {
      id: "math-254",
      label: "Introduction to Linear Algebra (MATH 254)",
      options: ["MATH 270"],
      required: true,
    },
    {
      id: "stat-250",
      label: "Statistical Principles and Practices (STAT 250)",
      options: ["STAT C1000", "SOCI 109A"],
      required: true,
    },
    {
      id: "math-151",
      label: "Calculus II (MATH 151)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "math-150",
      label: "Calculus I (MATH 150)",
      options: ["MATH 190"],
      required: true,
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "phys-195",
      label: "Principles of Physics (PHYS 195) [series PHYS 195+PHYS 195L]",
      options: ["PHYS 1A"],
      required: true,
      group: { id: "g4-opt", label: "Complete one of the 2 options for PREPARATION FOR THE MAJOR.", count: 1, memberId: "g4-o1" },
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "phys-196",
      label: "Principles of Physics (PHYS 196) [series PHYS 196+PHYS 196L]",
      options: ["PHYS 1C"],
      required: true,
      group: { id: "g5-opt", label: "Complete one of the 2 options for PREPARATION FOR THE MAJOR.", count: 1, memberId: "g5-o1" },
    },
  ],
};
