// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → csudh · cs.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/csu-dominguez-hills/facts/cs.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California State University, Dominguez Hills · Computer Science B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=50&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F50%2FMajor%2F354a6f50-c620-4966-ac52-08ddbf3f4ee7 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_CSUDH_CS: RequirementSet = {
  school: "csudh",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California State University, Dominguez Hills, Computer Science B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=50&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F50%2FMajor%2F354a6f50-c620-4966-ac52-08ddbf3f4ee7",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: false,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "AS-T Computer Science",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "AS-T Computer Science",
      notes: "CSUDH’s catalog states that ADT holders \"are guaranteed admission with junior standing to a CSU and given priority admission over other transfer applicants when applying to a local CSU or non-impacted CSU program\" — and since every CSUDH program is non-impacted, that priority applies to this major. The similar-degree determination below is the CSU Chancellor’s Office’s own, read 2026-08-19 from the ADT Major & Campus Search (webapps.calstate.edu/sasdegreesearch, AjaxMethods.aspx/CreateCSUProgramList for campus \"Dominguez Hills\"; the tool reports its data last updated 07/08/2026). A similar degree also means the remaining requirements can be finished within 60 more semester units. The CSU search returns \"Computer Science, BS\" as the CSUDH program similar to the Computer Science AS-T — a direct match, and the major is not impacted, so an AS-T holder gets both admission priority and the 60-unit graduation guarantee. Worth contrasting with Cal Poly Pomona, where the same AS-T maps to Science, Technology & Society rather than the CS B.S.",
    },
    campusImpacted: "none",
    localAdmissionArea: "Not a gating factor at CSUDH. CSU local-admission areas matter only where a campus or program is impacted, and nothing at CSUDH is impacted for 2027-28, so there is no local-vs-non-local cutoff to clear — every one of the 20 sending colleges wired in this repo is admitted on the same 2.0 + Golden Four basis. CSUDH’s own local-service-area definition was not re-verified on 2026-08-19 because it does not affect admission here.",
    sourceUrl: "https://www.csudh.edu/future-students/transfer/admitted/admissions-requirements/",
  },
  majorPrep: [
    {
      id: "csc-121",
      label: "Introduction to Computer Science and Programming I (CSC 121)",
      options: ["CSCI 3"],
      required: true,
    },
    {
      id: "csc-123",
      label: "Introduction to Computer Science and Programming II (CSC 123)",
      options: ["CSCI 2"],
      required: true,
    },
    {
      id: "csc-221",
      label: "Assembly Language and Introduction to Computer Organization (CSC 221)",
      options: ["CSCI 16"],
      required: true,
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "csc-281",
      label: "Discrete Structures (CSC 281)",
      options: ["MATH 210"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for LOWER DIVISION REQUIRED COURSES.", count: 1, memberId: "g2-o1" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "mat-281",
      label: "Discrete Mathematics (MAT 281)",
      options: ["MATH 210"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for LOWER DIVISION REQUIRED COURSES.", count: 1, memberId: "g2-o2" },
    },
    {
      id: "mat-191",
      label: "Calculus I (MAT 191)",
      options: ["MATH 190"],
      required: true,
    },
    {
      id: "mat-193",
      label: "Calculus II (MAT 193)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "phy-130-p1",
      label: "General Physics I (PHY 130) [series PHY 130+PHY 132+PHY 134] — part 1 of 4 (complete all)",
      options: ["PHYS 1D"],
      required: true,
      group: { id: "g4-n10", label: "Select 10 course(s) from the following.", count: 10, memberId: "phy-130" },
    },
    {
      id: "phy-130-p2",
      label: "General Physics I (PHY 130) [series PHY 130+PHY 132+PHY 134] — part 2 of 4 (complete all)",
      options: ["PHYS 1B"],
      required: true,
      group: { id: "g4-n10", label: "Select 10 course(s) from the following.", count: 10, memberId: "phy-130" },
    },
    {
      id: "phy-130-p3",
      label: "General Physics I (PHY 130) [series PHY 130+PHY 132+PHY 134] — part 3 of 4 (complete all)",
      options: ["PHYS 1C"],
      required: true,
      group: { id: "g4-n10", label: "Select 10 course(s) from the following.", count: 10, memberId: "phy-130" },
    },
    {
      id: "phy-130-p4",
      label: "General Physics I (PHY 130) [series PHY 130+PHY 132+PHY 134] — part 4 of 4 (complete all)",
      options: ["PHYS 1A"],
      required: true,
      group: { id: "g4-n10", label: "Select 10 course(s) from the following.", count: 10, memberId: "phy-130" },
    },
  ],
};
