// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uc-berkeley · cs.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-berkeley/facts/cs.facts.json (verified UC facts, accessed 2026-07-02)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Berkeley · Computer Science, B.A. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=79&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F79%2FMajor%2F18bc32d8-6aa4-47cc-aced-08ddbf3f4ee7 (accessed 2026-08-18)
// verification: 'verified' — checked against the official ASSIST agreement
// (verified 2026-08-18; evidence in verification/ + the agreement JSON's verificationNote).
// ASSIST header notes: Auto-transformed 2026-08-18 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · COMPSCI 61A: cell absent from articulations
//   · COMPSCI 61C: cell absent from articulations
//   · COMPSCI 70: This course must be taken at the university after transfer
export const REQ_ECC_UC_BERKELEY_CS: RequirementSet = {
  school: "uc-berkeley",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Berkeley, Computer Science, B.A.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=79&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F79%2FMajor%2F18bc32d8-6aa4-47cc-aced-08ddbf3f4ee7",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-18",
    verification: 'verified',
  },
  impacted: true,
  gpaTarget: 3,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: false,
    gpa: null,
    notes: "Berkeley does NOT offer TAG — confirmed by omission 2026-07-02: the official TAG page/matrix list exactly six TAG campuses (Davis, Irvine, Merced, Riverside, Santa Barbara, Santa Cruz).",
    sourceUrl: "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/uc-transfer-programs/transfer-admission-guarantee-tag.html",
  },
  majorPrep: [
    {
      id: "math-54",
      label: "Linear Algebra and Differential Equations (MATH 54)",
      options: ["MATH 270"],
      required: true,
      group: { id: "g1-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "math-54" },
    },
    {
      id: "math-51",
      label: "Calculus I (MATH 51)",
      options: ["MATH 190"],
      required: true,
    },
    {
      id: "math-52",
      label: "Calculus II (MATH 52)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "compsci-61b-p1",
      label: "Data Structures (COMPSCI 61B) — part 1 of 2 (complete all)",
      options: ["CSCI 2"],
      required: false,
    },
    {
      id: "compsci-61b-p2",
      label: "Data Structures (COMPSCI 61B) — part 2 of 2 (complete all)",
      options: ["CSCI 30"],
      required: false,
    },
  ],
};
