// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uc-san-diego · cs.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-san-diego/facts/cs.facts.json (verified UC facts, accessed 2026-07-01)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, San Diego · CSE: Computer Science B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=7&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F7%2FMajor%2F76ab1c59-2dcf-4c6f-f364-08ddd3b241a4 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · CSE 30: cell absent from articulations
//   · CSE 21: cell absent from articulations
//   · CSE 29: cell absent from articulations
export const REQ_ECC_UC_SAN_DIEGO_CS: RequirementSet = {
  school: "uc-san-diego",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, San Diego, CSE: Computer Science B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=7&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F7%2FMajor%2F76ab1c59-2dcf-4c6f-f364-08ddd3b241a4",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2.4,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  majorPrep: [
    {
      id: "cse-11",
      label: "Introduction to Programming and Computational Problem Solving - Accelerated Pace (CSE 11)",
      options: ["CSCI 3"],
      required: true,
    },
    {
      id: "cse-12",
      label: "Basic Data Structures and Object-Oriented Design (CSE 12)",
      options: ["CSCI 2"],
      required: true,
    },
    {
      id: "cse-20",
      label: "Discrete Mathematics (CSE 20)",
      options: ["MATH 210"],
      required: true,
    },
    {
      id: "math-20b",
      label: "Calculus for Science and Engineering (MATH 20B)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "math-18",
      label: "Linear Algebra (MATH 18)",
      options: ["MATH 270"],
      required: true,
    },
    {
      id: "math-20c",
      label: "Calculus and Analytic Geometry for Science and Engineering (MATH 20C)",
      options: ["MATH 220"],
      required: true,
    },
    {
      id: "math-20a",
      label: "Calculus for Science and Engineering (MATH 20A)",
      options: ["MATH 190"],
      required: true,
    },
    {
      id: "bild-2-c1",
      label: "Multicellular Life (BILD 2) — option set 1 of 4",
      options: ["BIOL 110", "BIOL 110H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "bild-2" },
    },
    {
      id: "bild-2-c2",
      label: "Multicellular Life (BILD 2) — option set 2 of 4",
      options: ["BIOL 110", "BIOL 120H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "bild-2" },
    },
    {
      id: "bild-2-c3",
      label: "Multicellular Life (BILD 2) — option set 3 of 4",
      options: ["BIOL 120", "BIOL 110H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "bild-2" },
    },
    {
      id: "bild-2-c4",
      label: "Multicellular Life (BILD 2) — option set 4 of 4",
      options: ["BIOL 120", "BIOL 120H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "bild-2" },
    },
    {
      id: "chem-6a",
      label: "General Chemistry I (CHEM 6A)",
      options: ["CHEM 1A"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "chem-6a" },
    },
    {
      id: "chem-6b-p1",
      label: "General Chemistry II (CHEM 6B) — part 1 of 2 (complete all)",
      options: ["CHEM 1A"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "chem-6b" },
    },
    {
      id: "chem-6b-p2",
      label: "General Chemistry II (CHEM 6B) — part 2 of 2 (complete all)",
      options: ["CHEM 1B"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "chem-6b" },
    },
    {
      id: "phys-2a",
      label: "Physics - Mechanics (PHYS 2A)",
      options: ["PHYS 1A"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "phys-2a" },
    },
    {
      id: "phys-2b",
      label: "Physics - Electricity and Magnetism (PHYS 2B)",
      options: ["PHYS 1C"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "phys-2b" },
    },
    {
      id: "bild-3-c1",
      label: "Organismic and Evolutionary Biology (BILD 3) — option set 1 of 4",
      options: ["BIOL 110", "BIOL 110H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "bild-3" },
    },
    {
      id: "bild-3-c2",
      label: "Organismic and Evolutionary Biology (BILD 3) — option set 2 of 4",
      options: ["BIOL 110", "BIOL 120H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "bild-3" },
    },
    {
      id: "bild-3-c3",
      label: "Organismic and Evolutionary Biology (BILD 3) — option set 3 of 4",
      options: ["BIOL 120", "BIOL 110H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "bild-3" },
    },
    {
      id: "bild-3-c4",
      label: "Organismic and Evolutionary Biology (BILD 3) — option set 4 of 4",
      options: ["BIOL 120", "BIOL 120H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "bild-3" },
    },
    {
      id: "bild-1-c1",
      label: "The Cell (BILD 1) — option set 1 of 4",
      options: ["BIOL 110", "BIOL 110H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "bild-1" },
    },
    {
      id: "bild-1-c2",
      label: "The Cell (BILD 1) — option set 2 of 4",
      options: ["BIOL 110", "BIOL 120H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "bild-1" },
    },
    {
      id: "bild-1-c3",
      label: "The Cell (BILD 1) — option set 3 of 4",
      options: ["BIOL 120", "BIOL 110H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "bild-1" },
    },
    {
      id: "bild-1-c4",
      label: "The Cell (BILD 1) — option set 4 of 4",
      options: ["BIOL 120", "BIOL 120H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "bild-1" },
    },
  ],
};
