// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → ucla · psych.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/ucla/facts/psych.facts.json (verified UC facts, accessed 2026-07-01)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Los Angeles · Psychology/B.A. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=117&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F117%2FMajor%2F4326f498-897c-4aae-1fce-08ddcb96df9e (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · CHEM 17: cell absent from articulations
//   · PHYSICS 11: cell absent from articulations
//   · PHILOS 1: cell absent from articulations
//   · PHILOS 2: cell absent from articulations
//   · PHILOS 3: cell absent from articulations
//   · PHILOS 4: cell absent from articulations
//   · PHILOS 5: cell absent from articulations
//   · PHILOS 6: cell absent from articulations
//   · PHILOS 7: cell absent from articulations
//   · PHILOS 8: cell absent from articulations
//   · PHILOS 9: cell absent from articulations
//   · PHILOS 21: cell absent from articulations
//   · PHILOS 22W: cell absent from articulations
//   · PHILOS 23: cell absent from articulations
export const REQ_ECC_UCLA_PSYCH: RequirementSet = {
  school: "ucla",
  major: "psych",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Los Angeles, Psychology/B.A.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=117&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F117%2FMajor%2F4326f498-897c-4aae-1fce-08ddcb96df9e",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 3.2,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  majorPrep: [
    {
      id: "psych-10",
      label: "Introductory Psychology (PSYCH 10)",
      options: ["PSYC C1000", "PSYC C1000H"],
      required: false,
    },
    {
      id: "lifesci-7a",
      label: "Cell and Molecular Biology (LIFESCI 7A)",
      options: ["BIOL 110H", "BIOL 110"],
      required: false,
    },
    {
      id: "lifesci-15",
      label: "Life: Concepts and Issues (LIFESCI 15)",
      options: ["BIOL 10", "BIOL 10H"],
      required: false,
    },
    {
      id: "physci-3-b1",
      label: "Introduction to Human Physiology (PHYSCI 3) — option 1 of 2",
      options: ["PHYO 31"],
      required: false,
      group: { id: "physci-3-opt", label: "Complete one full option for Introduction to Human Physiology (PHYSCI 3)", count: 1, memberId: "physci-3-b1" },
    },
    {
      id: "physci-3-b2-p1",
      label: "Introduction to Human Physiology (PHYSCI 3) — option 2 of 2, part 1 of 2",
      options: ["APHY 34B"],
      required: false,
      group: { id: "physci-3-opt", label: "Complete one full option for Introduction to Human Physiology (PHYSCI 3)", count: 1, memberId: "physci-3-b2" },
    },
    {
      id: "physci-3-b2-p2",
      label: "Introduction to Human Physiology (PHYSCI 3) — option 2 of 2, part 2 of 2",
      options: ["APHY 34A"],
      required: false,
      group: { id: "physci-3-opt", label: "Complete one full option for Introduction to Human Physiology (PHYSCI 3)", count: 1, memberId: "physci-3-b2" },
    },
    {
      id: "req-lower-division-biology-courses",
      label: "Lower Division Biology Courses",
      options: ["BIOL 120"],
      required: false,
    },
    {
      id: "chem-20a",
      label: "Chemical Structure (CHEM 20A)",
      options: ["CHEM 1A"],
      required: false,
    },
    {
      id: "physics-10",
      label: "Physics (PHYSICS 10)",
      options: ["PHYS 2A", "PHYS 11"],
      required: false,
    },
    {
      id: "physics-1a",
      label: "Physics for Scientists and Engineers: Mechanics (PHYSICS 1A)",
      options: ["PHYS 1A"],
      required: false,
    },
    {
      id: "physics-5a",
      label: "Physics for Life Sciences Majors: Mechanics and Energy (PHYSICS 5A)",
      options: ["PHYS 3A"],
      required: false,
    },
    {
      id: "req-introductory-chemistry-courses",
      label: "Introductory Chemistry Courses",
      options: ["CHEM 20", "CHEM 4H", "CHEM 21A", "CHEM 4"],
      required: false,
    },
    // ASSIST row note: cell absent from articulations
    {
      id: "philos-22",
      label: "Introduction to Ethical Theory (PHILOS 22)",
      options: ["PHIL 103"],
      required: false,
    },
    // ASSIST row note: cell absent from articulations
    {
      id: "philos-31",
      label: "Logic, First Course (PHILOS 31)",
      options: ["PHIL 106"],
      required: false,
    },
    {
      id: "req-introductory-philosophy-courses",
      label: "Introductory Philosophy Courses",
      options: ["PHIL 105", "PHIL 101", "PHIL 111", "PHIL 107", "PHIL 103", "PHIL 106"],
      required: false,
    },
    {
      id: "stats-10",
      label: "Introduction to Statistical Reasoning (STATS 10)",
      options: ["BUS 116", "STAT C1000"],
      required: false,
    },
    {
      id: "req-introductory-statistics-courses",
      label: "Introductory Statistics Courses",
      options: ["COMS 180", "STAT C1000", "PSYC 109A"],
      required: false,
    },
    {
      id: "req-calculus-requirement",
      label: "Calculus Requirement",
      options: ["MATH 190"],
      required: false,
    },
    {
      id: "comptng-10a",
      label: "Introduction to Programming (COMPTNG 10A)",
      options: ["CSCI 1"],
      required: false,
    },
  ],
};
