// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uci · business.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-irvine/facts/business.facts.json (verified UC facts, accessed 2026-07-01)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Irvine · Business Administration, B.A. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=120&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F120%2FMajor%2Ffd5c78c2-b236-48a2-fbba-08dda2ee8889 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_UCI_BUSINESS: RequirementSet = {
  school: "uci",
  major: "business",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Irvine, Business Administration, B.A.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=120&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F120%2FMajor%2Ffd5c78c2-b236-48a2-fbba-08dda2ee8889",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 3,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: false,
    gpa: null,
    notes: "UC Irvine offers TAG, but Business Administration is excluded from TAG (2026–27 matrix; 2027–28 not yet published). The campus requires a 3.0 UC-transferable GPA with all major prep done by end of spring before fall enrollment.",
    sourceUrl: "https://admission.universityofcalifornia.edu/_assets/files/transfer-requirements/uc-tag-matrix_2026-2027.pdf",
  },
  majorPrep: [
    {
      id: "math-2b",
      label: "Single-Variable Calculus (MATH 2B)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "math-2a",
      label: "Single-Variable Calculus (MATH 2A)",
      options: ["MATH 190"],
      required: true,
    },
    // ASSIST row note: Option 1 of 3
    {
      id: "econ-20a",
      label: "Basic Economics I (ECON 20A)",
      options: ["ECON C2001"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 3 options for MAJOR PREPARATION COURSES REQUIRED FOR TRANSFER.", count: 1, memberId: "g2-o1" },
    },
    // ASSIST row note: Option 1 of 3
    {
      id: "econ-20b",
      label: "Basic Economics II (ECON 20B)",
      options: ["ECON C2002", "ECON C2002H"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 3 options for MAJOR PREPARATION COURSES REQUIRED FOR TRANSFER.", count: 1, memberId: "g2-o1" },
    },
    {
      id: "mgmt-7-p1",
      label: "Statistics for Business Decision Making (MGMT 7) — part 1 of 3 (complete all)",
      options: ["STAT C1000"],
      required: true,
    },
    {
      id: "mgmt-7-p2",
      label: "Statistics for Business Decision Making (MGMT 7) — part 2 of 3 (complete all)",
      options: ["STAT C1000H"],
      required: true,
    },
    {
      id: "mgmt-7-p3",
      label: "Statistics for Business Decision Making (MGMT 7) — part 3 of 3 (complete all)",
      options: ["PSYC 109A"],
      required: true,
    },
    {
      id: "mgmt-30a",
      label: "Principles of Accounting I (MGMT 30A)",
      options: ["BUS 150"],
      required: true,
    },
    {
      id: "mgmt-30b",
      label: "Principles of Accounting II (MGMT 30B)",
      options: ["BUS 151"],
      required: true,
    },
    {
      id: "mgmt-1",
      label: "Introduction to Business and Management (MGMT 1)",
      options: ["BUS 101"],
      required: false,
    },
  ],
};
