// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → cal-poly-pomona · business.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/cal-poly-pomona/facts/business.facts.json (verified CSU facts, accessed 2026-07-01)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California Polytechnic University, Pomona · Business Administration, B.S. - Technology and Operations Management Option · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=75&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F75%2FMajor%2F26b9c394-3cfe-403b-6628-08dd783dfd80 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_CAL_POLY_POMONA_BUSINESS: RequirementSet = {
  school: "cal-poly-pomona",
  major: "business",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California Polytechnic University, Pomona, Business Administration, B.S. - Technology and Operations Management Option",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=75&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F75%2FMajor%2F26b9c394-3cfe-403b-6628-08dd783dfd80",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: false,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "Business Administration 2.0 AS-T",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "Business Administration 2.0 AS-T",
      notes: "An AS-T in Business Administration 2.0 guarantees admission to the CSU SYSTEM with junior standing and priority consideration, and CPP maps it to its Business Administration B.S. (the wired ASSIST agreement variant is Technology & Operations Management — see facts.demo.json 'agreement'). Verified 2026-07-01.",
    },
    campusImpacted: null,
    localAdmissionArea: null,
    sourceUrl: "https://www.cpp.edu/admissions/transfer/impacted-majors.shtml",
  },
  majorPrep: [
    {
      id: "acc-2070",
      label: "Financial Accounting for Decision Making (ACC 2070)",
      options: ["BUS 150"],
      required: true,
    },
    {
      id: "acc-2080",
      label: "Managerial Accounting for Decision Making (ACC 2080)",
      options: ["BUS 151"],
      required: true,
    },
    {
      id: "bus-2500",
      label: "Applied Business Communication (BUS 2500)",
      options: ["BUS 108"],
      required: true,
    },
    {
      id: "ec-2202",
      label: "Principles of Macroeconomics (EC 2202)",
      options: ["ECON C2002", "ECON C2002H"],
      required: true,
    },
    {
      id: "ec-2201",
      label: "Principles of Microeconomics (EC 2201)",
      options: ["ECON C2001", "ECON 100"],
      required: true,
    },
    {
      id: "sta-1200",
      label: "Statistics with Applications (STA 1200)",
      options: ["STAT C1000", "STAT C1000H"],
      required: true,
    },
    {
      id: "cis-1010",
      label: "Introduction to Personal Computing (CIS 1010)",
      options: ["CIS 13"],
      required: true,
    },
    {
      id: "frl-2013",
      label: "The Legal Environment of Business and its Transactions (FRL 2013)",
      options: ["LAW 4"],
      required: true,
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "mat-1250",
      label: "Introductory Calculus for Business (MAT 1250)",
      options: ["MATH 165"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for MAJOR REQUIRED.", count: 1, memberId: "g2-o1" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "mat-1140",
      label: "Calculus I (MAT 1140)",
      options: ["MATH 190"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for MAJOR REQUIRED.", count: 1, memberId: "g2-o2" },
    },
  ],
};
