// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uci · cs.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-irvine/facts/cs.facts.json (verified UC facts, accessed 2026-07-01)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Irvine · Computer Science, B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=120&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F120%2FMajor%2F7752acca-2b16-46d0-fb90-08dda2ee8889 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_UCI_CS: RequirementSet = {
  school: "uci",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Irvine, Computer Science, B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=120&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F120%2FMajor%2F7752acca-2b16-46d0-fb90-08dda2ee8889",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 3,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: false,
    gpa: null,
    notes: "UC Irvine offers TAG, but every Donald Bren School of ICS major (including Computer Science) is excluded from TAG (2026–27 matrix). The campus requires a 3.0 UC-transferable GPA AND a minimum grade of B in each required prep course.",
    sourceUrl: "https://admission.universityofcalifornia.edu/_assets/files/transfer-requirements/uc-tag-matrix_2026-2027.pdf",
  },
  majorPrep: [
    {
      id: "i-c-sci-31-p1",
      label: "Introduction to Programming (I&C SCI 31) [series I&C SCI 31+I&C SCI 32+I&C SCI 33] — part 1 of 2 (complete all)",
      options: ["CSCI 30"],
      required: true,
    },
    {
      id: "i-c-sci-31-p2",
      label: "Introduction to Programming (I&C SCI 31) [series I&C SCI 31+I&C SCI 32+I&C SCI 33] — part 2 of 2 (complete all)",
      options: ["CSCI 1"],
      required: true,
    },
    {
      id: "math-2b",
      label: "Single-Variable Calculus (MATH 2B)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "math-2a",
      label: "Single-Variable Calculus (MATH 2A)",
      options: ["MATH 190"],
      required: true,
    },
    {
      id: "i-c-sci-46",
      label: "Data Structure Implementation and Analysis (I&C SCI 46)",
      options: ["CSCI 2"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "i-c-sci-46" },
    },
    {
      id: "i-c-sci-6d",
      label: "Discrete Mathematics for Computer Science (I&C SCI 6D)",
      options: ["MATH 210"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "i-c-sci-6d" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "math-3a",
      label: "Introduction to Linear Algebra (MATH 3A)",
      options: ["MATH 270"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 2 options for ADDITIONAL APPROVED COURSES FOR THE MAJOR.", count: 1, memberId: "g3-o2" },
    },
  ],
};
