// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → csu-sacramento · psych.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/csu-sacramento/facts/psych.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California State University, Sacramento · Psychology, BS · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=60&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F60%2FMajor%2F145cb5ac-b906-4cc7-ad2e-08ddbf3f4ee7 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · PSYC 8: Not Articulated
//   · PSYC 4: No Comparable Course
export const REQ_ECC_CSU_SACRAMENTO_PSYCH: RequirementSet = {
  school: "csu-sacramento",
  major: "psych",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California State University, Sacramento, Psychology, BS",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=60&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F60%2FMajor%2F145cb5ac-b906-4cc7-ad2e-08ddbf3f4ee7",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: false,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "the AA-T in Psychology — Sacramento State names \"Psychology - General\" as the similar major/concentration",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "the AA-T in Psychology — Sacramento State names \"Psychology - General\" as the similar major/concentration",
      notes: "Sacramento State publishes its own ADT \"Similar\" Majors and Concentrations list (Rev. 06.2026, https://www.csus.edu/apply/admissions/application-process/_internal/_documents/adt-corresponding-major.pdf) and it maps the AA-T in Psychology to \"Psychology - General\" — the program wired here. The CSU Chancellor’s Office ADT Major & Campus Search (data updated 07/08/2026) returns the same determination independently. What the ADT is worth at Sacramento State, in the campus’s own words: it \"ensures that all of your lower-division general education and major coursework is complete\", it \"waives the second semester (ENG20) graduation requirement\", and \"You’ll need just 60 units to complete your bachelor’s degree – guaranteed!\" The system-level guarantee behind it is admission to A CSU with junior standing plus priority at a local or non-impacted campus/program — not a promise of THIS campus. Since this major is not impacted for 2027-28, that priority applies here cleanly. Deadlines that actually bite: Sac State must receive ADT in-progress verification by March 15 (fall) or October 31 (spring), and you must self-report the ADT on Cal State Apply or file the correction form. Sacramento State also names Family Studies and Human Development as similar to the Psychology AA-T. The department calls the ADT \"the recommended transfer pathway\" and gives ADT holders one benefit nobody else gets: in-progress prerequisite coursework counts when the department decides whether you can leave Pre-Major status.",
    },
    campusImpacted: "none — the 2027-28 CSU Undergraduate Impacted Programs Matrix (July 2026) reads for this campus exactly: \"Sacramento: No campus impaction for FTF or UDT.  Impacted in business administration (all options), graphic design (general), and nursing (general).\" (https://www.calstate.edu/attend/impaction-at-the-csu/Documents/ImpactedProgramsMatrix.pdf, read 2026-08-19). Sacramento State says the same on its own impaction page: \"Campus-wide impaction has been lifted for the Fall 2024 Application Period. All applicants, local and non-local who meet the minimum requirements of the university will be considered for admission.\" So of the 13 majors wired here, exactly ONE — Business Administration — is impacted; the other twelve are admitted on the university’s ordinary transfer bar.",
    localAdmissionArea: "Sacramento State defines its local admission area by the COLLEGE ATTENDED, not by high school or county: \"A student transferring with the majority of units from one or more of the following community colleges is considered to be in Sacramento State’s local admission area: American River, Cosumnes River, Folsom Lake, Lake Tahoe, Sacramento City, Sierra, San Joaquin Delta, Solano, Woodland, and Yuba.\" Of the 20 sending colleges wired in this repo, exactly ONE is local: SIERRA COLLEGE. The other 19 (Cerritos, Chaffey, College of the Canyons, De Anza, Diablo Valley, East Los Angeles, El Camino, Fullerton, Irvine Valley, LA Pierce, Long Beach City, Modesto Junior, Moorpark, Mt. SAC, Orange Coast, Pasadena City, Riverside City, Saddleback, Santa Monica) are NON-local. Two consequences, both published: (1) the 2.0 minimum transfer GPA is stated for local-area applicants — for a non-local applicant \"the academic characteristics of the transfer applicant pool will determine the GPA minimum\", i.e. no number is published; (2) for the impacted Business Administration major, a local-area applicant receives a +0.1 boost to the cumulative GPA used for rank-ordering, stacking with the separate +0.1 an ADT earns. Note Diablo Valley College appears on Sac State’s ADT \"Transfer Ready\" partners list but NOT on the local-admission-area list, so it is a partner, not a local college. (https://www.csus.edu/apply/admissions/application-process/transfer-process.html, read 2026-08-19)",
    sourceUrl: "https://www.csus.edu/college/social-sciences-interdisciplinary-studies/psychology/apply-info.html",
  },
  majorPrep: [
    {
      id: "psyc-2",
      label: "Introductory Psychology (PSYC 2)",
      options: ["PSYC C1000", "PSYC C1000H"],
      required: true,
    },
    {
      id: "psyc-3",
      label: "Human Development (PSYC 3)",
      options: ["PSYC 116"],
      required: true,
    },
    {
      id: "psyc-9",
      label: "Introductory Statistics for Psychology (PSYC 9)",
      options: ["PSYC 109A"],
      required: true,
    },
  ],
};
