// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uc-santa-barbara · business.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-santa-barbara/facts/business.facts.json (verified UC facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Santa Barbara · Economics and Accounting, B.A. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=128&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F128%2FMajor%2F3ffa69d7-747f-45c6-341d-08ddf001012b (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · ECON 10A: This course must be taken at the university after transfer
export const REQ_ECC_UC_SANTA_BARBARA_BUSINESS: RequirementSet = {
  school: "uc-santa-barbara",
  major: "business",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Santa Barbara, Economics and Accounting, B.A.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=128&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F128%2FMajor%2F3ffa69d7-747f-45c6-341d-08ddf001012b",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2.75,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: true,
    gpa: 3.4,
    notes: "UCSB TAG, fall 2027 cycle: overall 3.40 UC-transferable GPA by the end of fall 2026; TAG filed in UC TAP Sept 1-30, 2026; UC application Oct 1 - Nov 30, 2026 with the SAME major as the TAG; TAU by Jan 31, 2027; decisions in April (UCSB gives no early evaluation). Cal-GETC/IGETC not required. Read 2026-08-19 from the campus TAG page and the 2027-28 UC TAG matrix (https://admission.universityofcalifornia.edu/_assets/files/transfer-requirements/updated_202728-tag-matrix_ada.pdf, accurate as of June 9, 2026). This major sits in one of the six departments (Biological Sciences, Chemistry & Biochemistry, Economics, Mathematics, Physics, Statistics & Applied Probability) whose TAG ALSO requires the major-preparation courses on the ASSIST agreement - the major-prep GPA earned by the end of fall 2026 and the courses themselves completed by the end of spring 2027. Admission through TAG is to the PRE-major only: UCSB guarantees the pre-major, and further requirements must be met at UCSB to enter the full major.",
    sourceUrl: "https://admissions.sa.ucsb.edu/tag",
  },
  majorPrep: [
    {
      id: "econ-1",
      label: "Principles of Economics-Micro (ECON 1)",
      options: ["ECON C2001"],
      required: true,
    },
    {
      id: "econ-2",
      label: "Principles of Economics-Macro (ECON 2)",
      options: ["ECON C2002H", "ECON C2002"],
      required: true,
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "math-3a",
      label: "Calculus with Applications, First Course (MATH 3A)",
      options: ["MATH 190"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 2 options for MAJOR PREPARATION COURSES REQUIRED FOR TRANSFER.", count: 1, memberId: "g3-o1" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "math-34a",
      label: "Calculus for Social and Life Sciences (MATH 34A)",
      options: ["MATH 165"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 2 options for MAJOR PREPARATION COURSES REQUIRED FOR TRANSFER.", count: 1, memberId: "g3-o2" },
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "math-34b",
      label: "Calculus for Social and Life Sciences (MATH 34B)",
      options: ["MATH 165"],
      required: true,
      group: { id: "g4-opt", label: "Complete one of the 2 options for MAJOR PREPARATION COURSES REQUIRED FOR TRANSFER.", count: 1, memberId: "g4-o1" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "math-3b",
      label: "Calculus with Applications, Second Course (MATH 3B)",
      options: ["MATH 191"],
      required: true,
      group: { id: "g4-opt", label: "Complete one of the 2 options for MAJOR PREPARATION COURSES REQUIRED FOR TRANSFER.", count: 1, memberId: "g4-o2" },
    },
    {
      id: "econ-3a",
      label: "Financial Accounting (ECON 3A)",
      options: ["BUS 150"],
      required: false,
    },
    {
      id: "econ-3b",
      label: "Financial Accounting (ECON 3B)",
      options: ["BUS 150"],
      required: false,
    },
  ],
};
