// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → csu-northridge · psych.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/csu-northridge/facts/psych.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California State University, Northridge · PSYCHOLOGY, B.A. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=42&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F42%2FMajor%2Fffdf7c81-35bf-4c20-4298-08dda831fbe0 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_CSU_NORTHRIDGE_PSYCH: RequirementSet = {
  school: "csu-northridge",
  major: "psych",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California State University, Northridge, PSYCHOLOGY, B.A.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=42&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F42%2FMajor%2Fffdf7c81-35bf-4c20-4298-08dda831fbe0",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: false,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "Psychology AA-T",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "Psychology AA-T",
      notes: "CSUN's ADT matching table lists the Psychology ADT as matching \"BA - Psychology - General\" — the degree modeled here — and also the B.S. Family and Consumer Sciences (Family Studies) option. Psychology is not impacted at CSUN, so the ADT's impaction-priority benefit is moot; junior standing, the 60-unit path and priority registration still apply.",
    },
    campusImpacted: "none — CSUN is not campus-impacted for transfers. For BOTH 2026-2027 and 2027-2028 exactly two majors are impacted: the B.A. in Cinema and Television Arts (Film Production and Television Production options only) and the B.A. in Music (audition). No other major carries supplementary criteria (verified 2026-08-19).",
    localAdmissionArea: "None in effect. CSUN states that local/nonlocal-area (regional) impaction \"is no longer in effect\" for 2026-2027 and 2027-2028 — every first-time transfer applicant meets the same standard CSU criteria, and Table 1 of the transfer-impaction page sets one minimum admission GPA (2.00) for a California community college \"Anywhere in California\". There is therefore no local-area advantage or penalty from any of the 20 sending colleges modeled here (verified 2026-08-19). Historical note: CSUN did operate a local-area 0.10 GPA bump in earlier cycles; that is retired.",
    sourceUrl: "https://www.csun.edu/admissions-financial-aid/how-to-apply/impaction/transfer-impaction",
  },
  majorPrep: [
    {
      id: "psy-250",
      label: "Physiological Correlates of Human Behavior (PSY 250)",
      options: ["PSYC 107"],
      required: true,
    },
    {
      id: "psy-150",
      label: "Introduction to Psychology (PSY 150)",
      options: ["PSYC C1000", "PSYC C1000H"],
      required: true,
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "math-140",
      label: "Introductory Statistics (MATH 140)",
      options: ["STAT C1000", "STAT C1000H", "BUS 116"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for LOWER DIVISION MAJOR PREPARATION COURSES.", count: 1, memberId: "g2-o1" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "req-other-acceptable-statistics",
      label: "Other Acceptable Statistics",
      options: ["SOCI 109A", "PSYC 109A"],
      required: true,
    },
  ],
};
