// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → ucla · business.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/ucla/facts/business.facts.json (verified UC facts, accessed 2026-07-01)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Los Angeles · Business Economics/B.A. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=117&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F117%2FMajor%2Ffee8c832-0108-4517-1f93-08ddcb96df9e (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · ECON 11: This Course is Never Articulated
//   · ECON 41: This Course is Never Articulated
export const REQ_ECC_UCLA_BUSINESS: RequirementSet = {
  school: "ucla",
  major: "business",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Los Angeles, Business Economics/B.A.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=117&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F117%2FMajor%2Ffee8c832-0108-4517-1f93-08ddcb96df9e",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 3.2,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  majorPrep: [
    {
      id: "econ-2",
      label: "Principles of Economics(Macroeconomics) (ECON 2)",
      options: ["ECON C2002H", "ECON C2002"],
      required: true,
    },
    {
      id: "econ-1",
      label: "Principles of Economics(Microeconomics) (ECON 1)",
      options: ["ECON C2001"],
      required: true,
    },
    {
      id: "mgmt-1a",
      label: "Principles of Accounting: Introduction to Financial Accounting Principles (MGMT 1A)",
      options: ["BUS 150"],
      required: true,
    },
    {
      id: "mgmt-1b",
      label: "Principles of Accounting:Introduction to Managerial Accounting Principles (MGMT 1B)",
      options: ["BUS 151"],
      required: true,
    },
    {
      id: "math-31a",
      label: "Differential and Integral Calculus (MATH 31A)",
      options: ["MATH 190"],
      required: true,
    },
    {
      id: "math-31b",
      label: "Integration and Infinite Series (MATH 31B)",
      options: ["MATH 191"],
      required: true,
    },
  ],
};
