// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → csu-fullerton · psych.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/csu-fullerton/facts/psych.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California State University, Fullerton · Psychology, B.A. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=129&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F129%2FMajor%2F7b1bcb3f-5d76-457a-8108-08dd55dbff27 (accessed 2026-08-19)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-19 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_CSU_FULLERTON_PSYCH: RequirementSet = {
  school: "csu-fullerton",
  major: "psych",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California State University, Fullerton, Psychology, B.A.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=129&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F129%2FMajor%2F7b1bcb3f-5d76-457a-8108-08dd55dbff27",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-19",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "AA-T Psychology (TMC 1002, effective Fall 2011) — deemed similar to CSUF Psychology B.A., Psychology - General",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "AA-T Psychology (TMC 1002, effective Fall 2011) — deemed similar to CSUF Psychology B.A., Psychology - General",
      notes: "Straightforward case: the Psychology AA-T is the one deemed-similar ADT for this major, and the designation has been in force since Fall 2011. How CSUF uses an ADT: because CSUF is impacted at BOTH the campus and the major level, an ADT does not guarantee admission here. CSUF states it plainly — \"Student must meet the GPA cutoff for the term. Cal State Fullerton is impacted at the local level as well as major impacted. Thus, under current CSU guidelines, the student will receive a 0.1 GPA bump. The 'calculated GPA' will be applied to the major specific minimum GPA and to any GPA used in the ranking of applicants.\" Separately: \"Students who have completed an approved Associate Degree for Transfer program deemed 'similar' to their Cal State Fullerton major are eligible to graduate in 60 units\", and that 60-unit option is lost if the student changes major or adds a second major or a minor. The ADT must be verified in progress or awarded by the campus deadline — Fall 2026 entrants must complete it by Spring 2026, Spring 2027 entrants by Summer 2026 — through ADT eVerify or an official transcript. CSUF's 2026-2027 catalog names AA-T/AS-T verification as one of the supplementary criteria used to rank transfer applicants to impacted programs, so an ADT is worth real ranking points even where it is not deemed similar. The similar / not-similar determination recorded above is the CSU Chancellor's Office's own, read from the TMC similar-major dataset (2,649 rows across all 22 universities, 124 of them for Fullerton; dataset SiteAssets/tmcData.js?v=20260817 behind https://www.calstate.edu/attend/degrees-certificates-credentials/Pages/TMC-Search.aspx) on 2026-08-19 — not inferred from the discipline name. Sources: https://admissions.fullerton.edu/prospective-students/transfer.html and https://www.calstate.edu/apply/transfer/Pages/ccc-associate-degree-for-transfer.aspx",
    },
    campusImpacted: "campus-wide, and at the major level too. The CSU's 2027-28 Undergraduate Impacted Programs Matrix (July 2026) says of Fullerton: \"Impacted for FTF and UDT, and in all undergraduate programs, pre-programs, undeclared/undecided programs\" (https://www.calstate.edu/attend/impaction-at-the-csu/Documents/ImpactedProgramsMatrix.pdf, read 2026-08-19). The CSU impaction database names Cal State Fullerton as one of only FIVE universities where all undergraduate programs are impacted for 2027-28 (with Cal Poly San Luis Obispo, Long Beach, San Diego State and San Jose State). CSUF says the same in its own words: \"Cal State Fullerton is impacted by campus and major\" and \"Cal State Fullerton is an impacted campus at the transfer level for all majors\"; its 2026-2027 catalog adds \"Cal State Fullerton has been declared impacted on the first-time freshman level and upper-division transfer level.\" Consequences that apply to every one of the 13 wired majors: meeting the CSU minimum does NOT guarantee admission; supplementary admission criteria are applied; a waitlist may be established and is \"rank-ordered according to GPA... First priority admission preference will be given to local transfer students\"; and no major except Nursing accepts second-bachelor's applicants. CSUF separately publishes a short list of majors carrying an extra supplemental REQUIREMENT (an audition or a separate application): Dance, Music, Theatre and Nursing. None of the 13 wired majors is on that list — so for these majors the impaction screen is GPA plus prerequisites plus local status, not a portfolio or an audition.",
    localAdmissionArea: "CSUF sets the transfer local admission area by the COLLEGE attended, not by residence: \"CSUF has defined the local admission area as all community colleges in Orange County. Students who attended more than one institution will be classified based on where the majority of their units were completed. Priority admission preference will be given to local area transfers for all majors.\" The nine named local colleges are Coastline, Golden West, Saddleback, Cypress, Irvine Valley, Santa Ana, Fullerton, Orange Coast and Santiago Canyon. Of the 20 sending colleges wired here, exactly FOUR are local — Fullerton College, Irvine Valley College, Orange Coast College and Saddleback College. The other sixteen are NON-LOCAL: Cerritos, Chaffey, College of the Canyons, De Anza, Diablo Valley, East Los Angeles, El Camino, Long Beach City, Los Angeles Pierce, Modesto Junior, Moorpark, Mount San Antonio, Pasadena City, Riverside City, Santa Monica and Sierra. The CSU system chart states Fullerton's upper-division transfer local area identically: \"Majority of courses from or in combination with each of the community colleges in Orange County.\" Honesty point that matters when comparing campuses: unlike some CSUs, CSUF does NOT publish an admission guarantee for local applicants — local status buys first priority in a competitive, space-available pool and the first tiebreak off the waitlist, nothing more. (https://admissions.fullerton.edu/prospective-students/transfer.html, https://admissions.fullerton.edu/prospective-students/transfer-waitlist.html and https://www.calstate.edu/apply/counselor-resources/Documents/CSULocalAdmission-ServiceAreas.pdf, all read 2026-08-19)",
    sourceUrl: "https://admissions.fullerton.edu/prospective-students/transfer.html",
  },
  majorPrep: [
    {
      id: "psyc-101",
      label: "Introductory Psychology (PSYC 101)",
      options: ["PSYC C1000"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "psyc-101" },
    },
    {
      id: "psyc-201-p1",
      label: "Introduction to Statistics in Psychology (PSYC 201) — part 1 of 2 (complete all)",
      options: ["STAT C1000"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "psyc-201" },
    },
    {
      id: "psyc-201-p2",
      label: "Introduction to Statistics in Psychology (PSYC 201) — part 2 of 2 (complete all)",
      options: ["STAT C1000H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "psyc-201" },
    },
    {
      id: "psyc-202",
      label: "Research Meth in Psych (PSYC 202)",
      options: ["SOCI 109B"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "psyc-202" },
    },
    {
      id: "posc-100",
      label: "American Government (POSC 100)",
      options: ["POLS C1000"],
      required: true,
    },
  ],
};
