// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uci · psych.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-irvine/facts/psych.facts.json (verified UC facts, accessed 2026-07-01)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Irvine · Psychology, B.A. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=120&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F120%2FMajor%2F82458e96-27a9-4f33-fbc1-08dda2ee8889 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · PSCI 11B: This course must be taken at the university after transfer
export const REQ_ECC_UCI_PSYCH: RequirementSet = {
  school: "uci",
  major: "psych",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Irvine, Psychology, B.A.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=120&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F120%2FMajor%2F82458e96-27a9-4f33-fbc1-08dda2ee8889",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 3,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: true,
    gpa: 3.4,
    notes: "UCI TAG for Psychology, B.A. (School of Social Ecology): 3.4 GPA by end of fall (2026–27 matrix; 2027–28 not yet published). File in UC TAP Sept 1–30. Without TAG the campus floor is a 3.0 UC-transferable GPA.",
    sourceUrl: "https://admission.universityofcalifornia.edu/_assets/files/transfer-requirements/uc-tag-matrix_2026-2027.pdf",
  },
  majorPrep: [
    {
      id: "psci-11c-b1-p1",
      label: "Psychology Fundamentals (PSCI 11C) — option 1 of 2, part 1 of 2",
      options: ["PSYC C1000H"],
      required: true,
      group: { id: "psci-11c-opt", label: "Complete one full option for Psychology Fundamentals (PSCI 11C)", count: 1, memberId: "psci-11c-b1" },
    },
    {
      id: "psci-11c-b1-p2",
      label: "Psychology Fundamentals (PSCI 11C) — option 1 of 2, part 2 of 2",
      options: ["PSYC C1000"],
      required: true,
      group: { id: "psci-11c-opt", label: "Complete one full option for Psychology Fundamentals (PSCI 11C)", count: 1, memberId: "psci-11c-b1" },
    },
    {
      id: "psci-11c-b2-p1",
      label: "Psychology Fundamentals (PSCI 11C) — option 2 of 2, part 1 of 2",
      options: ["PSYC 108"],
      required: true,
      group: { id: "psci-11c-opt", label: "Complete one full option for Psychology Fundamentals (PSCI 11C)", count: 1, memberId: "psci-11c-b2" },
    },
    {
      id: "psci-11c-b2-p2",
      label: "Psychology Fundamentals (PSCI 11C) — option 2 of 2, part 2 of 2",
      options: ["PSYC 115"],
      required: true,
      group: { id: "psci-11c-opt", label: "Complete one full option for Psychology Fundamentals (PSCI 11C)", count: 1, memberId: "psci-11c-b2" },
    },
    {
      id: "socecol-13-p1",
      label: "Statistical Analysis in Social Ecology (SOCECOL 13) — part 1 of 4 (complete all)",
      options: ["BUS 116"],
      required: true,
    },
    {
      id: "socecol-13-p2",
      label: "Statistical Analysis in Social Ecology (SOCECOL 13) — part 2 of 4 (complete all)",
      options: ["SOCI 109A"],
      required: true,
    },
    {
      id: "socecol-13-p3",
      label: "Statistical Analysis in Social Ecology (SOCECOL 13) — part 3 of 4 (complete all)",
      options: ["STAT C1000"],
      required: true,
    },
    {
      id: "socecol-13-p4",
      label: "Statistical Analysis in Social Ecology (SOCECOL 13) — part 4 of 4 (complete all)",
      options: ["STAT C1000H"],
      required: true,
    },
    {
      id: "socecol-10",
      label: "Research Design (SOCECOL 10)",
      options: ["PSYC 109B"],
      required: true,
    },
    {
      id: "psci-11a-b1",
      label: "Psychology Fundamentals (PSCI 11A) — option 1 of 2",
      options: ["PSYC 107"],
      required: true,
      group: { id: "psci-11a-opt", label: "Complete one full option for Psychology Fundamentals (PSCI 11A)", count: 1, memberId: "psci-11a-b1" },
    },
    {
      id: "psci-11a-b2-p1",
      label: "Psychology Fundamentals (PSCI 11A) — option 2 of 2, part 1 of 2",
      options: ["PSYC C1000H"],
      required: true,
      group: { id: "psci-11a-opt", label: "Complete one full option for Psychology Fundamentals (PSCI 11A)", count: 1, memberId: "psci-11a-b2" },
    },
    {
      id: "psci-11a-b2-p2",
      label: "Psychology Fundamentals (PSCI 11A) — option 2 of 2, part 2 of 2",
      options: ["PSYC C1000"],
      required: true,
      group: { id: "psci-11a-opt", label: "Complete one full option for Psychology Fundamentals (PSCI 11A)", count: 1, memberId: "psci-11a-b2" },
    },
    {
      id: "crm-law-c7",
      label: "Introduction to Criminology, Law and Society (CRM/LAW C7)",
      options: ["AJ 100"],
      required: true,
    },
  ],
};
