// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uc-san-diego · business.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-san-diego/facts/business.facts.json (verified UC facts, accessed 2026-07-01)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, San Diego · Economics B.A. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=7&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F7%2FMajor%2F5ed40f63-55df-40ac-f2ed-08ddd3b241a4 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_UC_SAN_DIEGO_BUSINESS: RequirementSet = {
  school: "uc-san-diego",
  major: "business",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, San Diego, Economics B.A.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=7&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F7%2FMajor%2F5ed40f63-55df-40ac-f2ed-08ddd3b241a4",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2.4,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  majorPrep: [
    // ASSIST row note: Option 1 of 2
    {
      id: "math-10a",
      label: "Calculus I (MATH 10A)",
      options: ["MATH 190"],
      required: true,
      group: { id: "g1-opt", label: "Complete one of the 2 options for General Information.", count: 1, memberId: "g1-o1" },
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "math-10b",
      label: "Calculus II (MATH 10B)",
      options: ["MATH 191"],
      required: true,
      group: { id: "g1-opt", label: "Complete one of the 2 options for General Information.", count: 1, memberId: "g1-o1" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "math-20b",
      label: "Calculus for Science and Engineering (MATH 20B)",
      options: ["MATH 191"],
      required: true,
      group: { id: "g1-opt", label: "Complete one of the 2 options for General Information.", count: 1, memberId: "g1-o2" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "math-20c",
      label: "Calculus and Analytic Geometry for Science and Engineering (MATH 20C)",
      options: ["MATH 220"],
      required: true,
      group: { id: "g1-opt", label: "Complete one of the 2 options for General Information.", count: 1, memberId: "g1-o2" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "math-20a",
      label: "Calculus for Science and Engineering (MATH 20A)",
      options: ["MATH 190"],
      required: true,
      group: { id: "g1-opt", label: "Complete one of the 2 options for General Information.", count: 1, memberId: "g1-o2" },
    },
    {
      id: "econ-1",
      label: "Principles of Microeconomics (ECON 1)",
      options: ["ECON C2001"],
      required: true,
    },
    {
      id: "econ-3",
      label: "Principles of Macroeconomics (ECON 3)",
      options: ["ECON C2002"],
      required: true,
    },
  ],
};
