// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → cal-poly-pomona · cs.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/cal-poly-pomona/facts/cs.facts.json (verified CSU facts, accessed 2026-07-01)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California Polytechnic University, Pomona · Computer Science, B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=75&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F75%2FMajor%2F91d48af8-3aad-4422-6625-08dd783dfd80 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · CS 2610: cell absent from articulations
//   · STA 2260: cell absent from articulations
//   · CS 2600: cell absent from articulations
//   · CS 2410: cell absent from articulations
//   · CS 2520: cell absent from articulations
//   · CS 2250: cell absent from articulations
//   · CS 2450: cell absent from articulations
export const REQ_ECC_CAL_POLY_POMONA_CS: RequirementSet = {
  school: "cal-poly-pomona",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California Polytechnic University, Pomona, Computer Science, B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=75&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F75%2FMajor%2F91d48af8-3aad-4422-6625-08dd783dfd80",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "Computer Science AA-T (CPP maps it to STS–AI Ethics & Society, not the CS B.S.)",
    grantsPriority: false,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: false,
      similarAdt: "Computer Science AA-T (CPP maps it to STS–AI Ethics & Society, not the CS B.S.)",
      notes: "A Computer Science AA-T guarantees admission to the CSU SYSTEM with junior standing, but CPP does not map it to the Computer Science B.S. — it maps to Science, Technology & Society (AI Ethics & Society), so there is no campus ADT priority for this major (verified 2026-07-01).",
    },
    campusImpacted: null,
    localAdmissionArea: "CPP grants impacted-major priority to its local admission area; El Camino College is NON-local at CPP, and non-local admission-index cutoffs for impacted majors were unpublished (blank) for fall 2026 (majors research, verified 2026-07-03).",
    sourceUrl: "https://www.cpp.edu/admissions/transfer/impacted-majors.shtml",
  },
  majorPrep: [
    {
      id: "bio-1150",
      label: "Biology and Society (BIO 1150) [series BIO 1150+BIO 1150L]",
      options: ["BIOL 120", "BIOL 120H"],
      required: true,
    },
    {
      id: "cs-1300",
      label: "Discrete Structures (CS 1300)",
      options: ["MATH 210"],
      required: true,
    },
    {
      id: "cs-2400",
      label: "Data Structures and Advanced Programming (CS 2400)",
      options: ["CSCI 2"],
      required: true,
    },
    {
      id: "cs-1400",
      label: "Introduction to Programming and Problem Solving (CS 1400)",
      options: ["CSCI 3"],
      required: true,
    },
    {
      id: "cs-2640",
      label: "Computer Organization and Assembly Programming (CS 2640)",
      options: ["CSCI 16"],
      required: true,
    },
    {
      id: "mat-1150",
      label: "Calculus II (MAT 1150)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "mat-1140",
      label: "Calculus I (MAT 1140)",
      options: ["MATH 190"],
      required: true,
    },
    {
      id: "phy-1510",
      label: "Introduction to Newtonian Mechanics (PHY 1510) [series PHY 1510+PHY 1510L]",
      options: ["PHYS 1A"],
      required: true,
    },
    {
      id: "cs-2560",
      label: "C++ Programming (CS 2560)",
      options: ["CSCI 30"],
      required: true,
    },
  ],
};
