// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uc-davis · business.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-davis/facts/business.facts.json (verified UC facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Davis · Managerial Economics B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=89&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F89%2FMajor%2F2433e4d6-04f6-4176-347b-08ddb349963e (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · ARE 018: cell absent from articulations
export const REQ_ECC_UC_DAVIS_BUSINESS: RequirementSet = {
  school: "uc-davis",
  major: "business",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Davis, Managerial Economics B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=89&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F89%2FMajor%2F2433e4d6-04f6-4176-347b-08ddb349963e",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2.8,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: true,
    gpa: 3.2,
    notes: "UC Davis is one of the six TAG campuses. From the 2027-28 UC TAG matrix (fall 2027 / spring 2028 cycle, \"accurate as of June 9, 2026\") cross-checked against UC Davis's own TAG requirements page, both read 2026-08-19: 3.20 UC-transferable GPA for every major in the College of Agricultural and Environmental Sciences, the College of Biological Sciences and the College of Letters and Science; 3.50 in BOTH cumulative and major-preparation coursework for every College of Engineering major; GPA required by end of summer 2026. Fall quarter only, file Sept 1-30 via UC TAP, Cal-GETC/IGETC NOT required. Davis pre-evaluates and releases decisions mid-November — wait for the TAG decision before submitting the UC application. TAG-excluded at Davis: business, computer science, data science, undeclared programs, and the landscape architecture guarantee (pre-Landscape Architecture only). Managerial Economics is a CAES major and remains TAG-eligible at 3.20; the TAG exclusion named \"Business\" is the separate Graduate School of Management Business B.S.",
    sourceUrl: "https://admission.universityofcalifornia.edu/_assets/files/transfer-requirements/updated_202728-tag-matrix_ada.pdf",
  },
  majorPrep: [
    {
      id: "ecn-001a",
      label: "Principles of Microeconomics (ECN 001A)",
      options: ["ECON C2001"],
      required: true,
    },
    {
      id: "ecn-001b",
      label: "Principles of Macroeconomics (ECN 001B)",
      options: ["ECON C2002H", "ECON C2002"],
      required: true,
    },
    // ASSIST row note: Option 2 of 3
    {
      id: "mat-021a",
      label: "Calculus (MAT 021A)",
      options: ["MATH 190"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 3 options for MATHEMATICS.", count: 1, memberId: "g2-o2" },
    },
    // ASSIST row note: Option 2 of 3
    {
      id: "mat-021b-p1",
      label: "Calculus (MAT 021B) — part 1 of 2 (complete all)",
      options: ["MATH 190"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 3 options for MATHEMATICS.", count: 1, memberId: "g2-o2" },
    },
    // ASSIST row note: Option 2 of 3
    {
      id: "mat-021b-p2",
      label: "Calculus (MAT 021B) — part 2 of 2 (complete all)",
      options: ["MATH 191"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 3 options for MATHEMATICS.", count: 1, memberId: "g2-o2" },
    },
    // ASSIST row note: Option 2 of 3
    {
      id: "mat-021c-p1",
      label: "Calculus (MAT 021C) — part 1 of 2 (complete all)",
      options: ["MATH 191"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 3 options for MATHEMATICS.", count: 1, memberId: "g2-o2" },
    },
    // ASSIST row note: Option 2 of 3
    {
      id: "mat-021c-p2",
      label: "Calculus (MAT 021C) — part 2 of 2 (complete all)",
      options: ["MATH 220"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 3 options for MATHEMATICS.", count: 1, memberId: "g2-o2" },
    },
    {
      id: "sta-013",
      label: "Elementary Statistics (STA 013)",
      options: ["SOCI 109A", "PSYC 109A", "COMS 180", "STAT C1000H", "STAT C1000", "BUS 116"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "sta-013" },
    },
    {
      id: "mgt-011b",
      label: "Elementary Accounting  (MGT 011B)",
      options: ["BUS 151"],
      required: false,
    },
    {
      id: "mgt-011a",
      label: "Elementary Accounting  (MGT 011A)",
      options: ["BUS 150"],
      required: false,
    },
    {
      id: "cmn-003",
      label: "Interpersonal Communication Competence (CMN 003)",
      options: ["COMM C1004"],
      required: true,
      group: { id: "g6-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "cmn-003" },
    },
    {
      id: "cmn-001",
      label: "Introduction to Public Speaking (CMN 001)",
      options: ["COMM C1000", "COMM C1000H"],
      required: true,
      group: { id: "g6-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "cmn-001" },
    },
  ],
};
