// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → san-diego-state · business.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/san-diego-state/facts/business.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → San Diego State University · General Business, Business Administration, B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=26&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F26%2FMajor%2F9f49a1a3-90ea-4e0a-f3b5-08ddd3b241a4 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_SAN_DIEGO_STATE_BUSINESS: RequirementSet = {
  school: "san-diego-state",
  major: "business",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → San Diego State University, General Business, Business Administration, B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=26&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F26%2FMajor%2F9f49a1a3-90ea-4e0a-f3b5-08ddd3b241a4",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2.9,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "Business Administration AS-T, and Business Administration 2.0 AS-T — SDSU maps both to Business Administration – General Business (and to – Financial Services), effective Fall 2021",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "Business Administration AS-T, and Business Administration 2.0 AS-T — SDSU maps both to Business Administration – General Business (and to – Financial Services), effective Fall 2021",
      notes: "SDSU’s own equivalence table lists \"Business Administration (AS-T) → Business Administration – General, B.S.\" and the same for \"Business Administration 2.0\"; the CSU TMC dataset carries the matching San Diego rows for General Business and Financial Services, TMC \"AS-T Business Administration 2.0\", effective Fall 2021. The other concentrations — Accounting, Entrepreneurship, Finance, Human Resource Management, Information Systems, Management, Marketing and Real Estate — are all marked ADT \"no\" on SDSU’s pathway table, so an AS-T Business Administration buys nothing there. The concentration wired here is therefore the one where the ADT is actually worth the 0.1 GPA cushion under the 2.90 minimum. How an ADT works at SDSU: an ADT holder who applies to the SDSU major SDSU has approved as equivalent \"will be given admission priority\", and \"applicants using the ADT pathway for admission may be within .1 of the grade point average (GPA) required by the major to which they are applying\" — a 0.1 GPA cushion under the published minimum — \"however, a higher GPA may be required.\" The applicant must select the matching ADT major on Cal State Apply by November 30, 2026, submit the mandatory Academic History Update, have the community college eVerify the degree (or send the Verification of Intent form by March 15, 2027), and send a final transcript showing the ADT awarded. Sources: https://admissions.sdsu.edu/transfers/transfer-pathways (SDSU’s own AA-T/AS-T-to-SDSU-major equivalence table, read 2026-08-19) cross-checked against the CSU Chancellor’s Office TMC similar-degree dataset for campus \"San Diego\" (46 rows; SiteAssets/tmcData.js?v=20260817 behind https://www.calstate.edu/attend/degrees-certificates-credentials/Pages/TMC-Search.aspx, read 2026-08-19). The two sources agree on every one of the 13 majors wired here.",
    },
    campusImpacted: "campus-wide, and for upper-division transfers as well as first-time freshmen. The CSU Chancellor’s Office 2027-28 Undergraduate Impacted Programs Matrix (July 2026) says it verbatim: \"San Diego: Impacted for FTF and UDT, and in all undergraduate programs, pre-programs, and undeclared/undecided programs.\" (https://www.calstate.edu/attend/impaction-at-the-csu/Documents/ImpactedProgramsMatrix.pdf, read 2026-08-19). SDSU repeats it on its own transfer page: \"SDSU is impacted at the undergraduate level in all majors and programs. As such, we are unable to offer admission to all CSU eligible applicants.\" (https://admissions.sdsu.edu/transfers/minimum-requirements, page last updated 7/1/26). Because EVERY undergraduate program is impacted, impaction does not distinguish one SDSU major from another — the per-major minimum cumulative GPA does, and SDSU publishes one for every major.",
    localAdmissionArea: "SDSU sets its transfer local admissions area by the COMMUNITY COLLEGE attended, and the list is short: Cuyamaca, Grossmont, Imperial Valley, San Diego City, San Diego Mesa, San Diego Miramar and Southwestern. \"If you attend a community college in SDSU’s local admissions area, then you will receive priority consideration during the admission ranking process.\" NONE of the 20 sending colleges wired in this repo is on that list — Cerritos, Chaffey, College of the Canyons, De Anza, Diablo Valley, East Los Angeles, El Camino, Fullerton, Irvine Valley, Los Angeles Pierce, Long Beach City, Modesto Junior, Moorpark, Mount San Antonio, Orange Coast, Pasadena City, Riverside City, Saddleback, Santa Monica and Sierra are ALL non-local at SDSU. So every student this repo serves is a non-local applicant to a campus where every program is impacted: no local priority, no local guarantee, admitted on a space-available basis and \"ranked based on the extent to which they have completed the requirements\" — i.e. the ranking lever is finishing the 60 units, the Golden Four, the GE and the full major preparation early and with the highest GPA, not merely clearing the minimum. Two adjacent local routes also exclude these colleges: the SDCCD-SDSU Guaranteed Admissions Agreement (San Diego City, Mesa and Miramar only) and the Palomar/MiraCosta priority for programs CSU San Marcos does not offer. (The FIRST-YEAR local area is a different, geographic definition — a high school in San Diego County south of state route 56 extending east to the Imperial County line, or any high school in Imperial County — and does not apply to transfers.) Sources: https://admissions.sdsu.edu/local-admissions-area (read 2026-08-19; page last updated 11/14/25), https://admissions.sdsu.edu/transfers/transfer-pathways and https://admissions.sdsu.edu/_resources/pdf/tag-2027-fall.pdf (Enrollment Services, 7/2026).",
    sourceUrl: "https://admissions.sdsu.edu/transfers/gpa-requirements",
  },
  majorPrep: [
    {
      id: "mis-180",
      label: "Principles of Information Systems (MIS 180)",
      options: ["CIS 13"],
      required: true,
    },
    {
      id: "acctg-202",
      label: "Managerial Accounting Fundamentals (ACCTG 202)",
      options: ["BUS 151"],
      required: true,
    },
    {
      id: "acctg-201",
      label: "Financial Accounting Fundamentals (ACCTG 201)",
      options: ["BUS 150"],
      required: true,
    },
    {
      id: "econ-101",
      label: "Principles of Economics (ECON 101)",
      options: ["ECON C2002", "ECON C2002H"],
      required: true,
    },
    {
      id: "fin-240",
      label: "Legal Environment of Business (FIN 240)",
      options: ["LAW 5", "LAW 4"],
      required: true,
    },
    {
      id: "rws-290",
      label: "Business Writing and Rhetoric (RWS 290)",
      options: ["BUS 108"],
      required: true,
    },
    {
      id: "econ-102",
      label: "Principles of Economics (ECON 102)",
      options: ["ECON C2001"],
      required: true,
    },
    {
      id: "math-120-p1",
      label: "Calculus for Business Analysis (MATH 120) — part 1 of 2 (complete all)",
      options: ["MATH 165"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "math-120" },
    },
    {
      id: "math-120-p2",
      label: "Calculus for Business Analysis (MATH 120) — part 2 of 2 (complete all)",
      options: ["MATH 140"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "math-120" },
    },
    {
      id: "math-150",
      label: "Calculus I (MATH 150)",
      options: ["MATH 190"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "math-150" },
    },
    {
      id: "stat-119",
      label: "Elementary Statistics for Business (STAT 119)",
      options: ["STAT C1000", "PSYC 109A"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "stat-119" },
    },
    {
      id: "econ-201",
      label: "Statistical Methods (ECON 201)",
      options: ["STAT C1000"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "econ-201" },
    },
  ],
};
