// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uc-berkeley · psych.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-berkeley/facts/psych.facts.json (verified UC facts, accessed 2026-07-02)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Berkeley · Psychology, B.A. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=79&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F79%2FMajor%2F72ebd5bc-b397-4532-ace4-08ddbf3f4ee7 (accessed 2026-08-18)
// verification: 'verified' — checked against the official ASSIST agreement
// (verified 2026-08-18; evidence in verification/ + the agreement JSON's verificationNote).
// ASSIST header notes: Auto-transformed 2026-08-18 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_UC_BERKELEY_PSYCH: RequirementSet = {
  school: "uc-berkeley",
  major: "psych",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Berkeley, Psychology, B.A.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=79&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F79%2FMajor%2F72ebd5bc-b397-4532-ace4-08ddbf3f4ee7",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-18",
    verification: 'verified',
  },
  impacted: true,
  gpaTarget: 3,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: false,
    gpa: null,
    notes: "Berkeley does NOT offer TAG — confirmed by omission 2026-07-02: the official TAG page/matrix list exactly six TAG campuses (Davis, Irvine, Merced, Riverside, Santa Barbara, Santa Cruz).",
    sourceUrl: "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/uc-transfer-programs/transfer-admission-guarantee-tag.html",
  },
  majorPrep: [
    {
      id: "psych-1",
      label: "General Psychology (PSYCH 1)",
      options: ["PSYC C1000", "PSYC C1000H"],
      required: true,
    },
    {
      id: "mcellbi-32",
      label: "Introduction to Human Physiology (MCELLBI 32) [series MCELLBI 32+MCELLBI 32L]",
      options: ["PHYO 31"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "mcellbi-32" },
    },
    {
      id: "anthro-1",
      label: "Introduction to Biological Anthropology (ANTHRO 1)",
      options: ["ANTH 1H", "ANTH 1"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "anthro-1" },
    },
    {
      id: "biology-1a-p1",
      label: "General Biology Lecture (Cells, Genetics, Animal Form & Function) (BIOLOGY 1A) [series BIOLOGY 1A+BIOLOGY 1AL+BIOLOGY 1B] — part 1 of 3 (complete all)",
      options: ["BIOL 130"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "biology-1a" },
    },
    {
      id: "biology-1a-p2",
      label: "General Biology Lecture (Cells, Genetics, Animal Form & Function) (BIOLOGY 1A) [series BIOLOGY 1A+BIOLOGY 1AL+BIOLOGY 1B] — part 2 of 3 (complete all)",
      options: ["BIOL 120"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "biology-1a" },
    },
    {
      id: "biology-1a-p3",
      label: "General Biology Lecture (Cells, Genetics, Animal Form & Function) (BIOLOGY 1A) [series BIOLOGY 1A+BIOLOGY 1AL+BIOLOGY 1B] — part 3 of 3 (complete all)",
      options: ["BIOL 110"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "biology-1a" },
    },
    {
      id: "pol-sci-1",
      label: "Introduction to American Politics (POL SCI 1)",
      options: ["POLS C1000", "POLS C1000H"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "pol-sci-1" },
    },
    {
      id: "philos-25b",
      label: "Modern Philosophy (PHILOS 25B)",
      options: ["PHIL 112"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "philos-25b" },
    },
    {
      id: "pol-sci-4",
      label: "Introduction to Political Theory (POL SCI 4)",
      options: ["POLI 7"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "pol-sci-4" },
    },
    {
      id: "anthro-3",
      label: "Introduction to Social and Cultural Anthropology (ANTHRO 3)",
      options: ["ANTH 2H", "ANTH 2"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "anthro-3" },
    },
    {
      id: "sociol-1",
      label: "Introduction to Sociology (SOCIOL 1)",
      options: ["SOCI 101"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "sociol-1" },
    },
    {
      id: "pol-sci-2",
      label: "Introduction to Comparative Politics (POL SCI 2)",
      options: ["POLI 2"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "pol-sci-2" },
    },
    {
      id: "stat-2",
      label: "Introduction to Statistics (STAT 2)",
      options: ["STAT C1000", "STAT C1000H", "BUS 116"],
      required: true,
      group: { id: "g4-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "stat-2" },
    },
    {
      id: "math-51",
      label: "Calculus I (MATH 51)",
      options: ["MATH 190"],
      required: true,
      group: { id: "g4-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "math-51" },
    },
    {
      id: "math-55",
      label: "Discrete Mathematics (MATH 55)",
      options: ["MATH 210"],
      required: true,
      group: { id: "g4-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "math-55" },
    },
    {
      id: "stat-c8",
      label: "Foundations of Data Science (STAT C8)",
      options: ["CSCI 8"],
      required: true,
      group: { id: "g4-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "stat-c8" },
    },
    {
      id: "math-52",
      label: "Calculus II (MATH 52)",
      options: ["MATH 191"],
      required: true,
      group: { id: "g4-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "math-52" },
    },
    {
      id: "math-54",
      label: "Linear Algebra and Differential Equations (MATH 54)",
      options: ["MATH 270"],
      required: true,
      group: { id: "g4-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "math-54" },
    },
  ],
};
