// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → sf-state · cs.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/sf-state/facts/cs.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → San Francisco State University · Computer Science, B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=116&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F116%2FMajor%2Fd71b56bc-6f68-4403-f29c-08ddd3b241a4 (accessed 2026-08-19)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-19 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · MATH 225: cell absent from articulations
//   · MATH 324: cell absent from articulations
//   · CSC 215: cell absent from articulations
//   · CSC 230: cell absent from articulations
//   · CSC 101: cell absent from articulations
//   · CSC 220: cell absent from articulations
export const REQ_ECC_SF_STATE_CS: RequirementSet = {
  school: "sf-state",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → San Francisco State University, Computer Science, B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=116&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F116%2FMajor%2Fd71b56bc-6f68-4403-f29c-08ddd3b241a4",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-19",
    verification: 'unreviewed',
  },
  impacted: false,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "Computer Science AS-T (TMC 2007) — deemed similar to the SF State Computer Science B.S. effective Fall 2012",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "Computer Science AS-T (TMC 2007) — deemed similar to the SF State Computer Science B.S. effective Fall 2012",
      notes: "The Computer Science AS-T is deemed similar to this major, so it carries the full 60-unit completion guarantee — worth contrasting with Cal Poly Pomona, which maps the same AS-T to Science, Technology & Society rather than to its CS B.S. What the ADT is worth: statewide it guarantees priority admission to a CSU campus with junior standing — \"though not necessarily to a particular campus or major\" (https://www.calstate.edu/apply/transfer/Pages/ccc-associate-degree-for-transfer.aspx) — and, when the receiving program is deemed SIMILAR, the bachelor’s is completable in no more than 60 further units. At SF State the similarity determination is made by faculty in the discipline and published on the Articulation Office’s ADT Pathways and Roadmaps page; SF State additionally gives an ADT in a similar program +0.10 GPA in the competitive admission process, which only matters for its impacted (nursing) programs. SF State’s bulletin is explicit that \"no specific degree is required for admission as an upper-division student\" — the ADT buys the 60-unit completion guarantee and priority, not the admission itself. Sources: https://ueap.sfsu.edu/2025-2026_ADT-pathways-roadmaps (SF State’s own faculty-approved similar list), https://ueap.sfsu.edu/articulation (SB 1440 / STAR Act implementation), and the CSU Chancellor’s Office TMC similar-major dataset behind https://www.calstate.edu/attend/degrees-certificates-credentials/Pages/TMC-Search.aspx (247 San Francisco rows), all read 2026-08-19.",
    },
    campusImpacted: "none — SF State has NO campus-level impaction, and none of the 13 majors wired here is impacted. The CSU Chancellor’s Office 2027-28 Undergraduate Impacted Programs Matrix (July 2026) reads verbatim: \"San Francisco: No campus impaction for FTF or UDT. Impacted in nursing (general) and undeclared/undecided (with an interest in nursing).\" SF State’s own impaction page agrees and names the impacted programs for the open cycles: BSN Nursing and the ADN-BSN programs (fall 2026 and spring 2027), plus Undeclared with an Interest in Nursing (first-time freshmen only); the ADN-BSN College of San Mateo program is CLOSED for fall 2026. Practical effect for this major: no supplemental application, no raised GPA bar, and no requirement to name an alternate major. Sources: https://www.calstate.edu/attend/impaction-at-the-csu/Documents/ImpactedProgramsMatrix.pdf and https://future.sfsu.edu/impaction, both read 2026-08-19.",
    localAdmissionArea: "SF State sets local admission priority by the APPLICANT’S RESIDENCE, not by the college attended: applicants residing in the six Bay Area counties (Alameda, Contra Costa, Marin, San Francisco, San Mateo, Santa Clara) get +0.10 added to their GPA for the competitive admission process, and an ADT in a similar program adds a further +0.10. Both bonuses exist to RANK applicants, so they only bite where ranking happens — the impacted nursing programs. This major is not impacted, so a CSU-eligible applicant is not ranked against others and neither bonus changes the outcome; they are worth knowing only if the student switches to or adds a nursing program. Of the 20 sending colleges wired here, only De Anza (Santa Clara County) and Diablo Valley (Contra Costa County) sit inside the six-county area at all — and even there the criterion is where the student LIVES, so a Los Angeles-area resident attending De Anza is still non-local while a San Mateo resident attending any college is local. (https://future.sfsu.edu/impaction, read 2026-08-19)",
    sourceUrl: "https://future.sfsu.edu/admissions/transfers",
  },
  majorPrep: [
    {
      id: "math-226",
      label: "Calculus I (MATH 226)",
      options: ["MATH 190"],
      required: true,
    },
    {
      id: "math-227",
      label: "Calculus II (MATH 227)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "phys-220",
      label: "General Physics with Calculus I (PHYS 220) [series PHYS 220+PHYS 222]",
      options: ["PHYS 1A"],
      required: true,
    },
    {
      id: "phys-230",
      label: "General Physics with Calculus II (PHYS 230) [series PHYS 230+PHYS 232]",
      options: ["PHYS 1C"],
      required: true,
    },
    {
      id: "csc-256",
      label: "Machine Structures (CSC 256)",
      options: ["CSCI 16"],
      required: true,
    },
  ],
};
