// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uc-san-diego · psych.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-san-diego/facts/psych.facts.json (verified UC facts, accessed 2026-07-01)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, San Diego · Psychology B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=7&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F7%2FMajor%2F7f4fecec-ee5e-4be4-f36b-08ddd3b241a4 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · MAE 5: cell absent from articulations
//   · ECE 15: This course must be taken at the university after transfer
//   · CSS 1: cell absent from articulations
//   · COGS 14B: cell absent from articulations
export const REQ_ECC_UC_SAN_DIEGO_PSYCH: RequirementSet = {
  school: "uc-san-diego",
  major: "psych",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, San Diego, Psychology B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=7&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F7%2FMajor%2F7f4fecec-ee5e-4be4-f36b-08ddd3b241a4",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: false,
  gpaTarget: 2.4,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  majorPrep: [
    {
      id: "chem-4",
      label: "Basic Chemistry (CHEM 4)",
      options: ["CHEM 4"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "chem-4" },
    },
    {
      id: "bild-2-c1",
      label: "Multicellular Life (BILD 2) — option set 1 of 4",
      options: ["BIOL 110", "BIOL 110H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-2" },
    },
    {
      id: "bild-2-c2",
      label: "Multicellular Life (BILD 2) — option set 2 of 4",
      options: ["BIOL 110", "BIOL 120H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-2" },
    },
    {
      id: "bild-2-c3",
      label: "Multicellular Life (BILD 2) — option set 3 of 4",
      options: ["BIOL 120", "BIOL 110H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-2" },
    },
    {
      id: "bild-2-c4",
      label: "Multicellular Life (BILD 2) — option set 4 of 4",
      options: ["BIOL 120", "BIOL 120H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-2" },
    },
    {
      id: "bild-26",
      label: "Human Physiology (BILD 26)",
      options: ["PHYO 31"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-26" },
    },
    {
      id: "bild-3-c1",
      label: "Organismic and Evolutionary Biology (BILD 3) — option set 1 of 4",
      options: ["BIOL 110", "BIOL 110H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-3" },
    },
    {
      id: "bild-3-c2",
      label: "Organismic and Evolutionary Biology (BILD 3) — option set 2 of 4",
      options: ["BIOL 110", "BIOL 120H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-3" },
    },
    {
      id: "bild-3-c3",
      label: "Organismic and Evolutionary Biology (BILD 3) — option set 3 of 4",
      options: ["BIOL 120", "BIOL 110H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-3" },
    },
    {
      id: "bild-3-c4",
      label: "Organismic and Evolutionary Biology (BILD 3) — option set 4 of 4",
      options: ["BIOL 120", "BIOL 120H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-3" },
    },
    {
      id: "bild-1-c1",
      label: "The Cell (BILD 1) — option set 1 of 4",
      options: ["BIOL 110", "BIOL 110H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-1" },
    },
    {
      id: "bild-1-c2",
      label: "The Cell (BILD 1) — option set 2 of 4",
      options: ["BIOL 110", "BIOL 120H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-1" },
    },
    {
      id: "bild-1-c3",
      label: "The Cell (BILD 1) — option set 3 of 4",
      options: ["BIOL 120", "BIOL 110H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-1" },
    },
    {
      id: "bild-1-c4",
      label: "The Cell (BILD 1) — option set 4 of 4",
      options: ["BIOL 120", "BIOL 120H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-1" },
    },
    {
      id: "bild-10",
      label: "Fundamental Concepts of Modern Biology (BILD 10)",
      options: ["BIOL 10", "BIOL 10H"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bild-10" },
    },
    {
      id: "chem-6a",
      label: "General Chemistry I (CHEM 6A)",
      options: ["CHEM 1A"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "chem-6a" },
    },
    {
      id: "chem-6c",
      label: "General Chemistry III (CHEM 6C)",
      options: ["CHEM 1B"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "chem-6c" },
    },
    {
      id: "chem-6b-p1",
      label: "General Chemistry II (CHEM 6B) — part 1 of 2 (complete all)",
      options: ["CHEM 1A"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "chem-6b" },
    },
    {
      id: "chem-6b-p2",
      label: "General Chemistry II (CHEM 6B) — part 2 of 2 (complete all)",
      options: ["CHEM 1B"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "chem-6b" },
    },
    {
      id: "psyc-2",
      label: "General Psychology: Biological Foundations (PSYC 2)",
      options: ["PSYC 107"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "psyc-2" },
    },
    {
      id: "phys-10",
      label: "Concepts in Physics (PHYS 10)",
      options: ["PHYS 11"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phys-10" },
    },
    {
      id: "phys-1b-p1",
      label: "Electricity and Magnetism (PHYS 1B) — part 1 of 2 (complete all)",
      options: ["PHYS 3A"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phys-1b" },
    },
    {
      id: "phys-1b-p2",
      label: "Electricity and Magnetism (PHYS 1B) — part 2 of 2 (complete all)",
      options: ["PHYS 3B"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phys-1b" },
    },
    {
      id: "phys-2b",
      label: "Physics - Electricity and Magnetism (PHYS 2B)",
      options: ["PHYS 1C"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phys-2b" },
    },
    {
      id: "phys-2a",
      label: "Physics - Mechanics (PHYS 2A)",
      options: ["PHYS 1A"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phys-2a" },
    },
    {
      id: "phys-1c-p1",
      label: "Waves, Optics, and Modern Physics (PHYS 1C) — part 1 of 2 (complete all)",
      options: ["PHYS 3A"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phys-1c" },
    },
    {
      id: "phys-1c-p2",
      label: "Waves, Optics, and Modern Physics (PHYS 1C) — part 2 of 2 (complete all)",
      options: ["PHYS 3B"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phys-1c" },
    },
    {
      id: "phys-1a-p1",
      label: "Mechanics (PHYS 1A) — part 1 of 2 (complete all)",
      options: ["PHYS 3A"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phys-1a" },
    },
    {
      id: "phys-1a-p2",
      label: "Mechanics (PHYS 1A) — part 2 of 2 (complete all)",
      options: ["PHYS 3B"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phys-1a" },
    },
    {
      id: "phys-2c",
      label: "Physics - Fluids, Waves, Thermodynamics, and Optics (PHYS 2C)",
      options: ["PHYS 1B"],
      required: true,
      group: { id: "g1-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phys-2c" },
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "math-10a",
      label: "Calculus I (MATH 10A)",
      options: ["MATH 190"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for LOWER DIVISION MAJOR REQUIREMENTS.", count: 1, memberId: "g2-o1" },
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "math-10b",
      label: "Calculus II (MATH 10B)",
      options: ["MATH 191"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for LOWER DIVISION MAJOR REQUIREMENTS.", count: 1, memberId: "g2-o1" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "math-20a",
      label: "Calculus for Science and Engineering (MATH 20A)",
      options: ["MATH 190"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for LOWER DIVISION MAJOR REQUIREMENTS.", count: 1, memberId: "g2-o2" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "math-20b",
      label: "Calculus for Science and Engineering (MATH 20B)",
      options: ["MATH 191"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for LOWER DIVISION MAJOR REQUIREMENTS.", count: 1, memberId: "g2-o2" },
    },
    {
      id: "psyc-70",
      label: "Research Methods in Psychology (PSYC 70)",
      options: ["PSYC 109B"],
      required: true,
    },
    {
      id: "cogs-14a",
      label: "Introduction to Research Methods (COGS 14A)",
      options: ["PSYC 109B"],
      required: true,
    },
    {
      id: "cse-8a",
      label: "Introduction to Programming and Computational Problem Solving I (CSE 8A)",
      options: ["CSCI 1"],
      required: true,
    },
    {
      id: "mae-8",
      label: "MATLAB Programming for Engineering Analysis (MAE 8)",
      options: ["CSCI 17"],
      required: true,
    },
    {
      id: "cse-6r",
      label: "Introduction to Computer Science and Object-Oriented Programming: Python (CSE 6R)",
      options: ["CSCI 14"],
      required: true,
    },
    {
      id: "cse-12",
      label: "Basic Data Structures and Object-Oriented Design (CSE 12)",
      options: ["CSCI 2"],
      required: true,
    },
    {
      id: "cogs-18",
      label: "Introduction to Python (COGS 18)",
      options: ["CSCI 14"],
      required: true,
    },
    {
      id: "cse-11",
      label: "Introduction to Programming and Computational Problem Solving - Accelerated Pace (CSE 11)",
      options: ["CSCI 3"],
      required: true,
    },
    {
      id: "psyc-60",
      label: "Introduction to Statistics (PSYC 60)",
      options: ["STAT C1000", "PSYC 109A"],
      required: true,
    },
    {
      id: "math-11",
      label: "Calculus Based Elementary Probability and Statistics (MATH 11)",
      options: ["STAT C1000"],
      required: true,
    },
  ],
};
