// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → csulb · business.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/csu-long-beach/facts/business.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California State University, Long Beach · Management · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=81&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F81%2FMajor%2F92494576-e834-4fb8-33b0-08ddb349963e (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_CSULB_BUSINESS: RequirementSet = {
  school: "csulb",
  major: "business",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California State University, Long Beach, Management",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=81&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F81%2FMajor%2F92494576-e834-4fb8-33b0-08ddb349963e",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2.5,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "Business Administration 2.0 AS-T (TMC 200602) — deemed similar to ALL EIGHT CSULB Business Administration B.S. options (Accounting, Finance, Human Resources Management, International Business, Management, Management Information Systems, Marketing, Operations & Supply Chain Management), effective Fall 2021",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "Business Administration 2.0 AS-T (TMC 200602) — deemed similar to ALL EIGHT CSULB Business Administration B.S. options (Accounting, Finance, Human Resources Management, International Business, Management, Management Information Systems, Marketing, Operations & Supply Chain Management), effective Fall 2021",
      notes: "Unusually clean: the CSU TMC database lists all eight Long Beach business options as similar to the Business Administration 2.0 AS-T, so the ADT benefit applies whichever option the student picks. CAVEAT: the older Business Administration AS-T (TMC 2006) is NOT among CSULB's similar designations, even though the College of Business page states it \"remains committed to honoring the completed Associate Degree for Transfer (ADT) based on either the 2014 revision of the Transfer Model Curriculum (TMC) or the TMC 2.0, revised in 2021, through the academic year of 2025-26\" — a student holding a 2014-TMC business ADT should confirm directly with the college. How CSULB uses an ADT: it counts only when the ADT is deemed \"similar\" to the CSULB major applied to, and the student applies to that major. When it is similar, the ADT curriculum is used IN LIEU OF the major-specific degree requirements, the cumulative GPA is increased by 0.1 (applied both to the major-specific minimum GPA and to the ranking of applicants), and the bachelor's is completable in 60 further units. The ADT must be granted no later than the prior Spring term for fall entry, or the prior Summer for spring entry; if it is not completed, CSULB re-evaluates and may withdraw the admission offer. CSULB does not publish the similarity list itself — it points students at their community-college transfer center — so the similarity facts here come from the CSU Chancellor's Office TMC similar-major database (2,649 rows across all 22 universities; dataset SiteAssets/tmcData.js?v=20260817 behind https://www.calstate.edu/attend/degrees-certificates-credentials/Pages/TMC-Search.aspx), read 2026-08-19. Sources: https://www.csulb.edu/admissions/associate-degree-transfer-program-adt and the college transfer-criteria page in factsSourceUrl.",
    },
    campusImpacted: "campus-wide — the CSU's official 2027-28 impaction listing names Cal State Long Beach among the universities where ALL undergraduate programs, pre-programs and undeclared/undecided programs are impacted, for first-time freshmen and upper-division transfers alike (https://www.calstate.edu/attend/degrees-certificates-credentials/Pages/impacted-degrees.aspx, read 2026-08-19); CSULB repeats it in its own ASSIST agreement header: \"ALL MAJORS ARE IMPACTED at California State University, Long Beach.\" CSULB then flags a smaller HIGHLY IMPACTED tier inside that — for the fall 2026 / spring 2027 cycle exactly three programs: Nursing BSN Basic, Nursing RN-to-BSN and Social Work. None of the 13 wired majors is highly impacted, so local preference is not suspended for them.",
    localAdmissionArea: "CSULB sets local preference by HIGH SCHOOL of graduation (named districts: ABC, Anaheim Union in part, Bellflower, Compton, Downey, Huntington Beach, Long Beach, Los Alamitos, Norwalk-La Mirada, Paramount, plus named private schools), by military-veteran status regardless of school, or — for transfers, new since fall 2025 — by completing the MAJORITY of units with the LAST school attended being one of five colleges: Long Beach City College, Cerritos College, Golden West College, Coastline Community College or Orange Coast College. Of the 20 sending colleges wired here, only Long Beach City, Cerritos and Orange Coast are local; the other 17 are non-local. This matters more than usual at CSULB: for a major that is NOT highly impacted (all 13 wired majors), a CSU-eligible LOCAL applicant who meets the major-specific minimum cumulative GPA and the required lower-division preparation \"will be offered admission\". Non-local applicants are admitted on a space-available basis, ranked by cumulative GPA and by how many of the additional recommended preparation courses they finished. A local applicant to a HIGHLY impacted major gets a +0.1 GPA increase instead of the guarantee. (https://www.csulb.edu/admissions/local-preference-admission-consideration, read 2026-08-19)",
    sourceUrl: "https://www.csulb.edu/admissions/fall-2026-transfer-major-specific-degree-requirements-college-of-business-cob",
  },
  majorPrep: [
    {
      id: "acct-202",
      label: "Managerial Accounting (ACCT 202)",
      options: ["BUS 151"],
      required: true,
    },
    {
      id: "econ-100",
      label: "Principles of Macroeconomics (ECON 100)",
      options: ["ECON C2002"],
      required: true,
    },
    {
      id: "econ-101",
      label: "Principles of Microeconomics (ECON 101)",
      options: ["ECON C2001"],
      required: true,
    },
    {
      id: "blaw-220",
      label: "Introduction to Law and Business Transactions (BLAW 220)",
      options: ["LAW 4", "LAW 5"],
      required: true,
    },
    {
      id: "acct-201",
      label: "Elementary Financial Accounting (ACCT 201)",
      options: ["BUS 150"],
      required: true,
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "math-115",
      label: "Calculus for Business (MATH 115)",
      options: ["MATH 165"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for LOWER DIVISION MAJOR REQUIREMENTS.", count: 1, memberId: "g2-o1" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "math-116",
      label: "Finite Math (MATH 116)",
      options: ["MATH 140"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for LOWER DIVISION MAJOR REQUIREMENTS.", count: 1, memberId: "g2-o2" },
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "stat-118-p1",
      label: "Introductory Business Statistics (STAT 118) — part 1 of 2 (complete all)",
      options: ["BUS 116"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 2 options for STATISTICS.", count: 1, memberId: "g3-o1" },
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "stat-118-p2",
      label: "Introductory Business Statistics (STAT 118) — part 2 of 2 (complete all)",
      options: ["STAT C1000"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 2 options for STATISTICS.", count: 1, memberId: "g3-o1" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "stat-108-p1",
      label: "Statistics for Everyday Life (STAT 108) — part 1 of 2 (complete all)",
      options: ["BUS 116"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 2 options for STATISTICS.", count: 1, memberId: "g3-o2" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "stat-108-p2",
      label: "Statistics for Everyday Life (STAT 108) — part 2 of 2 (complete all)",
      options: ["STAT C1000"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 2 options for STATISTICS.", count: 1, memberId: "g3-o2" },
    },
    {
      id: "i-s-233",
      label: "Introduction to Business Data Analysis and Programming (I S 233)",
      options: ["CIS 13"],
      required: true,
    },
  ],
};
