// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → cal-poly-pomona · psych.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/cal-poly-pomona/facts/psych.facts.json (verified CSU facts, accessed 2026-07-01)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California Polytechnic University, Pomona · Psychology, B.A. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=75&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F75%2FMajor%2F375df927-92f5-4cd9-65dc-08dd783dfd80 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · PSY 2222: cell absent from articulations
export const REQ_ECC_CAL_POLY_POMONA_PSYCH: RequirementSet = {
  school: "cal-poly-pomona",
  major: "psych",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California Polytechnic University, Pomona, Psychology, B.A.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=75&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F75%2FMajor%2F375df927-92f5-4cd9-65dc-08dd783dfd80",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "Psychology AA-T",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "Psychology AA-T",
      notes: "A Psychology AA-T guarantees admission to the CSU SYSTEM with junior standing and priority consideration, and CPP maps it to its Psychology B.A. Because the major is impacted at CPP, ADT holders must still meet the campus's supplemental/local criteria to land here (verified 2026-07-01).",
    },
    campusImpacted: null,
    localAdmissionArea: "CPP grants impacted-major priority to its local admission area; El Camino College is NON-local at CPP, and non-local admission-index cutoffs for impacted majors were unpublished (blank) for fall 2026 (majors research, verified 2026-07-03).",
    sourceUrl: "https://www.cpp.edu/admissions/transfer/impacted-majors.shtml",
  },
  majorPrep: [
    {
      id: "psy-2210",
      label: "Mind, Brain, and Behavior: An Integrated View (PSY 2210)",
      options: ["PSYC 107"],
      required: true,
    },
    {
      id: "psy-2201",
      label: "Introduction to Psychology (PSY 2201)",
      options: ["PSYC C1000", "PSYC C1000H"],
      required: true,
    },
    {
      id: "psy-2204",
      label: "Research Methods in Psychology (PSY 2204)",
      options: ["PSYC 109B"],
      required: true,
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "sta-1200",
      label: "Statistics with Applications (STA 1200)",
      options: ["STAT C1000", "STAT C1000H"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for MAJOR REQUIRED.", count: 1, memberId: "g2-o1" },
    },
  ],
};
