// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → csulb · psych.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/csu-long-beach/facts/psych.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California State University, Long Beach · Psychology · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=81&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F81%2FMajor%2F48e73ff7-36c9-441e-3369-08ddb349963e (accessed 2026-08-19)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-19 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_CSULB_PSYCH: RequirementSet = {
  school: "csulb",
  major: "psych",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California State University, Long Beach, Psychology",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=81&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F81%2FMajor%2F48e73ff7-36c9-441e-3369-08ddb349963e",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-19",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2.5,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "Psychology AA-T (TMC 1002) — deemed similar to the CSULB Psychology B.A. (General), effective Fall 2011",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "Psychology AA-T (TMC 1002) — deemed similar to the CSULB Psychology B.A. (General), effective Fall 2011",
      notes: "The Psychology AA-T carries the full ADT benefit here, which matters because the four-course prep suite is otherwise strict: a similar ADT is used in lieu of it. How CSULB uses an ADT: it counts only when the ADT is deemed \"similar\" to the CSULB major applied to, and the student applies to that major. When it is similar, the ADT curriculum is used IN LIEU OF the major-specific degree requirements, the cumulative GPA is increased by 0.1 (applied both to the major-specific minimum GPA and to the ranking of applicants), and the bachelor's is completable in 60 further units. The ADT must be granted no later than the prior Spring term for fall entry, or the prior Summer for spring entry; if it is not completed, CSULB re-evaluates and may withdraw the admission offer. CSULB does not publish the similarity list itself — it points students at their community-college transfer center — so the similarity facts here come from the CSU Chancellor's Office TMC similar-major database (2,649 rows across all 22 universities; dataset SiteAssets/tmcData.js?v=20260817 behind https://www.calstate.edu/attend/degrees-certificates-credentials/Pages/TMC-Search.aspx), read 2026-08-19. Sources: https://www.csulb.edu/admissions/associate-degree-transfer-program-adt and the college transfer-criteria page in factsSourceUrl.",
    },
    campusImpacted: "campus-wide — the CSU's official 2027-28 impaction listing names Cal State Long Beach among the universities where ALL undergraduate programs, pre-programs and undeclared/undecided programs are impacted, for first-time freshmen and upper-division transfers alike (https://www.calstate.edu/attend/degrees-certificates-credentials/Pages/impacted-degrees.aspx, read 2026-08-19); CSULB repeats it in its own ASSIST agreement header: \"ALL MAJORS ARE IMPACTED at California State University, Long Beach.\" CSULB then flags a smaller HIGHLY IMPACTED tier inside that — for the fall 2026 / spring 2027 cycle exactly three programs: Nursing BSN Basic, Nursing RN-to-BSN and Social Work. None of the 13 wired majors is highly impacted, so local preference is not suspended for them.",
    localAdmissionArea: "CSULB sets local preference by HIGH SCHOOL of graduation (named districts: ABC, Anaheim Union in part, Bellflower, Compton, Downey, Huntington Beach, Long Beach, Los Alamitos, Norwalk-La Mirada, Paramount, plus named private schools), by military-veteran status regardless of school, or — for transfers, new since fall 2025 — by completing the MAJORITY of units with the LAST school attended being one of five colleges: Long Beach City College, Cerritos College, Golden West College, Coastline Community College or Orange Coast College. Of the 20 sending colleges wired here, only Long Beach City, Cerritos and Orange Coast are local; the other 17 are non-local. This matters more than usual at CSULB: for a major that is NOT highly impacted (all 13 wired majors), a CSU-eligible LOCAL applicant who meets the major-specific minimum cumulative GPA and the required lower-division preparation \"will be offered admission\". Non-local applicants are admitted on a space-available basis, ranked by cumulative GPA and by how many of the additional recommended preparation courses they finished. A local applicant to a HIGHLY impacted major gets a +0.1 GPA increase instead of the guarantee. (https://www.csulb.edu/admissions/local-preference-admission-consideration, read 2026-08-19)",
    sourceUrl: "https://www.csulb.edu/admissions/fall-2026-transfer-major-specific-degree-requirements-college-of-liberal-arts-cla",
  },
  majorPrep: [
    {
      id: "psy-110",
      label: "Elementary Statistics (PSY 110)",
      options: ["STAT C1000", "PSYC 109A", "SOCI 109A"],
      required: true,
    },
    {
      id: "psy-241",
      label: "Psychobiology (PSY 241)",
      options: ["PSYC 107"],
      required: true,
    },
    {
      id: "psy-220",
      label: "Research Methods (PSY 220)",
      options: ["SOCI 109B", "PSYC 109B"],
      required: true,
    },
    {
      id: "psy-100",
      label: "General Psychology (PSY 100)",
      options: ["PSYC C1000H", "PSYC C1000"],
      required: true,
    },
  ],
};
