// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → csudh · business.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/csu-dominguez-hills/facts/business.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California State University, Dominguez Hills · Business Administration B.S. General Business Concentration · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=50&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F50%2FMajor%2F97c4b703-409a-433a-ac8c-08ddbf3f4ee7 (accessed 2026-08-19)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-19 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_CSUDH_BUSINESS: RequirementSet = {
  school: "csudh",
  major: "business",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California State University, Dominguez Hills, Business Administration B.S. General Business Concentration",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=50&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F50%2FMajor%2F97c4b703-409a-433a-ac8c-08ddbf3f4ee7",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-19",
    verification: 'unreviewed',
  },
  impacted: false,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "AS-T Business Administration",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "AS-T Business Administration",
      notes: "CSUDH’s catalog states that ADT holders \"are guaranteed admission with junior standing to a CSU and given priority admission over other transfer applicants when applying to a local CSU or non-impacted CSU program\" — and since every CSUDH program is non-impacted, that priority applies to this major. The similar-degree determination below is the CSU Chancellor’s Office’s own, read 2026-08-19 from the ADT Major & Campus Search (webapps.calstate.edu/sasdegreesearch, AjaxMethods.aspx/CreateCSUProgramList for campus \"Dominguez Hills\"; the tool reports its data last updated 07/08/2026). A similar degree also means the remaining requirements can be finished within 60 more semester units. CAREFUL — the two Business ADTs do not behave the same here. The original \"Business Administration\" AS-T returns \"Business Administration, BS\" as a similar CSUDH program. The newer \"Business Administration 2.0\" AS-T does NOT: at CSUDH it maps instead to Public Administration, Political Science, Sociology, Psychology and the ethnic/gender-studies majors. A student holding Business Administration 2.0 therefore keeps ADT admission priority at CSUDH (nothing is impacted) but does NOT get the 60-unit similar-degree guarantee into the Business Administration B.S. Both were checked 2026-08-19 in the CSU ADT search.",
    },
    campusImpacted: "none",
    localAdmissionArea: "Not a gating factor at CSUDH. CSU local-admission areas matter only where a campus or program is impacted, and nothing at CSUDH is impacted for 2027-28, so there is no local-vs-non-local cutoff to clear — every one of the 20 sending colleges wired in this repo is admitted on the same 2.0 + Golden Four basis. CSUDH’s own local-service-area definition was not re-verified on 2026-08-19 because it does not affect admission here.",
    sourceUrl: "https://www.csudh.edu/future-students/transfer/admitted/admissions-requirements/",
  },
  majorPrep: [
    {
      id: "cis-270",
      label: "Information Systems and Technology Fundamentals (CIS 270)",
      options: ["CIS 13"],
      required: true,
    },
    {
      id: "eco-210",
      label: "Economic Theory 1A Microecomonics (ECO 210)",
      options: ["ECON C2001"],
      required: true,
    },
    {
      id: "law-240",
      label: "Legal Environment of Business (LAW 240)",
      options: ["LAW 5", "LAW 4"],
      required: true,
    },
    {
      id: "eco-211",
      label: "Economic Theory 1B Macroeconomics (ECO 211)",
      options: ["ECON C2002", "ECON C2002H"],
      required: true,
    },
    {
      id: "acc-230",
      label: "Financial Accounting (ACC 230)",
      options: ["BUS 150"],
      required: true,
    },
    {
      id: "acc-231",
      label: "Managerial Accounting (ACC 231)",
      options: ["BUS 151"],
      required: true,
    },
    {
      id: "req-statistics",
      label: "STATISTICS",
      options: ["STAT C1000", "MATH 115", "STAT C1000H", "PSYC 109A", "SOCI 109A"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "req-statistics" },
    },
    {
      id: "mat-131",
      label: "Elementary Statistics and Probability (MAT 131)",
      options: ["STAT C1000", "STAT C1000H"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "mat-131" },
    },
    {
      id: "omg-221-c1",
      label: "Introduction to Business Statistics (OMG 221) — option set 1 of 2",
      options: ["STAT C1000", "BUS 116"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "omg-221" },
    },
    {
      id: "omg-221-c2",
      label: "Introduction to Business Statistics (OMG 221) — option set 2 of 2",
      options: ["STAT C1000H", "BUS 116"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "omg-221" },
    },
  ],
};
