// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uc-davis · cs.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-davis/facts/cs.facts.json (verified UC facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Davis · Computer Science B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=89&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F89%2FMajor%2F37adebfb-6deb-4e42-34ac-08ddb349963e (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · ECS 050: cell absent from articulations
export const REQ_ECC_UC_DAVIS_CS: RequirementSet = {
  school: "uc-davis",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Davis, Computer Science B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=89&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F89%2FMajor%2F37adebfb-6deb-4e42-34ac-08ddb349963e",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 3.4,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: false,
    gpa: null,
    notes: "Computer Science is TAG-EXCLUDED at UC Davis — confirmed twice on 2026-08-19, in the 2027-28 UC TAG matrix (\"Undeclared programs, Business, Computer Science, Data Science and Landscape Architecture\") and on Davis's own TAG requirements page (\"All majors except business, computer science and data science are open to TAG\"). CS applicants must go through the regular UC application (Oct 1 - Nov 30, 2026) and clear the selective screen instead. UC Davis is one of the six TAG campuses. From the 2027-28 UC TAG matrix (fall 2027 / spring 2028 cycle, \"accurate as of June 9, 2026\") cross-checked against UC Davis's own TAG requirements page, both read 2026-08-19: 3.20 UC-transferable GPA for every major in the College of Agricultural and Environmental Sciences, the College of Biological Sciences and the College of Letters and Science; 3.50 in BOTH cumulative and major-preparation coursework for every College of Engineering major; GPA required by end of summer 2026. Fall quarter only, file Sept 1-30 via UC TAP, Cal-GETC/IGETC NOT required. Davis pre-evaluates and releases decisions mid-November — wait for the TAG decision before submitting the UC application. TAG-excluded at Davis: business, computer science, data science, undeclared programs, and the landscape architecture guarantee (pre-Landscape Architecture only).",
    sourceUrl: "https://admission.universityofcalifornia.edu/_assets/files/transfer-requirements/updated_202728-tag-matrix_ada.pdf",
  },
  majorPrep: [
    {
      id: "ecs-036c",
      label: "Data Structures, Algorithms, & Programming  (ECS 036C)",
      options: ["CSCI 2"],
      required: true,
    },
    {
      id: "ecs-036a",
      label: "Programming & Problem Solving  (ECS 036A)",
      options: ["CSCI 3", "CSCI 1"],
      required: true,
    },
    {
      id: "ecs-020",
      label: "Discrete Mathematics For Computer Science  (ECS 020)",
      options: ["MATH 210"],
      required: true,
    },
    {
      id: "ecs-036b",
      label: "Software Development & Object-Oriented Programming in C++ (ECS 036B)",
      options: ["CSCI 30"],
      required: true,
    },
    {
      id: "mat-021b-p1",
      label: "Calculus (MAT 021B) — part 1 of 2 (complete all)",
      options: ["MATH 190"],
      required: true,
    },
    {
      id: "mat-021b-p2",
      label: "Calculus (MAT 021B) — part 2 of 2 (complete all)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "mat-021a",
      label: "Calculus (MAT 021A)",
      options: ["MATH 190"],
      required: true,
    },
    {
      id: "mat-021c-p1",
      label: "Calculus (MAT 021C) — part 1 of 2 (complete all)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "mat-021c-p2",
      label: "Calculus (MAT 021C) — part 2 of 2 (complete all)",
      options: ["MATH 220"],
      required: true,
    },
    {
      id: "mat-022a",
      label: "Linear Algebra  (MAT 022A)",
      options: ["MATH 270"],
      required: true,
      group: { id: "g3-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "mat-022a" },
    },
    {
      id: "phy-009c",
      label: "Classical Physics  (PHY 009C)",
      options: ["PHYS 1C"],
      required: true,
      group: { id: "g4-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phy-009c" },
    },
    {
      id: "bis-002c-c1",
      label: "Introduction to Biology: Biodiversity & the Tree of Life (BIS 002C) — option set 1 of 4",
      options: ["BIOL 120H", "BIOL 120"],
      required: true,
      group: { id: "g4-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bis-002c" },
    },
    {
      id: "bis-002c-c2",
      label: "Introduction to Biology: Biodiversity & the Tree of Life (BIS 002C) — option set 2 of 4",
      options: ["BIOL 120H", "BIOL 110"],
      required: true,
      group: { id: "g4-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bis-002c" },
    },
    {
      id: "bis-002c-c3",
      label: "Introduction to Biology: Biodiversity & the Tree of Life (BIS 002C) — option set 3 of 4",
      options: ["BIOL 110H", "BIOL 120"],
      required: true,
      group: { id: "g4-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bis-002c" },
    },
    {
      id: "bis-002c-c4",
      label: "Introduction to Biology: Biodiversity & the Tree of Life (BIS 002C) — option set 4 of 4",
      options: ["BIOL 110H", "BIOL 110"],
      required: true,
      group: { id: "g4-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bis-002c" },
    },
    {
      id: "phy-009b-p1",
      label: "Classical Physics  (PHY 009B) — part 1 of 2 (complete all)",
      options: ["PHYS 1B"],
      required: true,
      group: { id: "g4-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phy-009b" },
    },
    {
      id: "phy-009b-p2",
      label: "Classical Physics  (PHY 009B) — part 2 of 2 (complete all)",
      options: ["PHYS 1D"],
      required: true,
      group: { id: "g4-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phy-009b" },
    },
    {
      id: "phy-009a",
      label: "Classical Physics  (PHY 009A)",
      options: ["PHYS 1A"],
      required: true,
      group: { id: "g4-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "phy-009a" },
    },
    {
      id: "bis-002b",
      label: "Introduction to Biology: Principles of Ecology & Evolution (BIS 002B)",
      options: ["BIOL 120H", "BIOL 120"],
      required: true,
      group: { id: "g4-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bis-002b" },
    },
    {
      id: "bis-002a",
      label: "Introduction to Biology: Essentials of Life on Earth (BIS 002A)",
      options: ["BIOL 110H", "BIOL 110"],
      required: true,
      group: { id: "g4-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "bis-002a" },
    },
    {
      id: "che-002a-p1",
      label: "General Chemistry (CHE 002A) [series CHE 002A+CHE 002B+CHE 002C] — part 1 of 2 (complete all)",
      options: ["CHEM 1A"],
      required: true,
      group: { id: "g4-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "che-002a" },
    },
    {
      id: "che-002a-p2",
      label: "General Chemistry (CHE 002A) [series CHE 002A+CHE 002B+CHE 002C] — part 2 of 2 (complete all)",
      options: ["CHEM 1B"],
      required: true,
      group: { id: "g4-n3", label: "Select 3 course(s) from the following.", count: 3, memberId: "che-002a" },
    },
  ],
};
