// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → ucla · cs.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/ucla/facts/cs.facts.json (verified UC facts, accessed 2026-07-01)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Los Angeles · Computer Science/B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=117&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F117%2FMajor%2F3fc7b07d-4058-4a0a-1f72-08ddcb96df9e (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · COM SCI 35L: cell absent from articulations
//   · COM SCI M51A: cell absent from articulations
//   · EC ENGR M16: cell absent from articulations
export const REQ_ECC_UCLA_CS: RequirementSet = {
  school: "ucla",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Los Angeles, Computer Science/B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=117&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F117%2FMajor%2F3fc7b07d-4058-4a0a-1f72-08ddcb96df9e",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 3.4,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  majorPrep: [
    {
      id: "com-sci-31-b1-p1",
      label: "Introduction to Computer Science I (COM SCI 31) — option 1 of 2, part 1 of 2",
      options: ["CSCI 1"],
      required: true,
      group: { id: "com-sci-31-opt", label: "Complete one full option for Introduction to Computer Science I (COM SCI 31)", count: 1, memberId: "com-sci-31-b1" },
    },
    {
      id: "com-sci-31-b1-p2",
      label: "Introduction to Computer Science I (COM SCI 31) — option 1 of 2, part 2 of 2",
      options: ["CSCI 2"],
      required: true,
      group: { id: "com-sci-31-opt", label: "Complete one full option for Introduction to Computer Science I (COM SCI 31)", count: 1, memberId: "com-sci-31-b1" },
    },
    {
      id: "com-sci-31-b2",
      label: "Introduction to Computer Science I (COM SCI 31) — option 2 of 2",
      options: ["CSCI 30"],
      required: true,
      group: { id: "com-sci-31-opt", label: "Complete one full option for Introduction to Computer Science I (COM SCI 31)", count: 1, memberId: "com-sci-31-b2" },
    },
    {
      id: "com-sci-32",
      label: "Introduction to Computer Science II (COM SCI 32)",
      options: ["CSCI 2"],
      required: true,
    },
    {
      id: "com-sci-33",
      label: "Introduction to Computer Organization (COM SCI 33)",
      options: ["CSCI 16"],
      required: true,
    },
    {
      id: "math-31a",
      label: "Differential and Integral Calculus (MATH 31A)",
      options: ["MATH 190"],
      required: true,
    },
    {
      id: "math-31b",
      label: "Integration and Infinite Series (MATH 31B)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "math-32a",
      label: "Calculus of Several Variables (MATH 32A)",
      options: ["MATH 220"],
      required: true,
    },
    {
      id: "math-32b",
      label: "Calculus of Several Variables (MATH 32B)",
      options: ["MATH 220"],
      required: true,
    },
    {
      id: "math-33a",
      label: "Linear Algebra and Applications (MATH 33A)",
      options: ["MATH 270"],
      required: true,
    },
    {
      id: "math-33b",
      label: "Differential Equations (MATH 33B)",
      options: ["MATH 270"],
      required: true,
    },
    {
      id: "math-61",
      label: "Introduction to Discrete Structures (MATH 61)",
      options: ["MATH 210"],
      required: true,
    },
    {
      id: "physics-1a-p1",
      label: "Physics for Scientists and Engineers: Mechanics (PHYSICS 1A) [series PHYSICS 1A+PHYSICS 1B+PHYSICS 1C+PHYSICS 4AL+PHYSICS 4BL] — part 1 of 3 (complete all)",
      options: ["PHYS 1D"],
      required: true,
    },
    {
      id: "physics-1a-p2",
      label: "Physics for Scientists and Engineers: Mechanics (PHYSICS 1A) [series PHYSICS 1A+PHYSICS 1B+PHYSICS 1C+PHYSICS 4AL+PHYSICS 4BL] — part 2 of 3 (complete all)",
      options: ["PHYS 1C"],
      required: true,
    },
    {
      id: "physics-1a-p3",
      label: "Physics for Scientists and Engineers: Mechanics (PHYSICS 1A) [series PHYSICS 1A+PHYSICS 1B+PHYSICS 1C+PHYSICS 4AL+PHYSICS 4BL] — part 3 of 3 (complete all)",
      options: ["PHYS 1A"],
      required: true,
    },
    {
      id: "engcomp-3",
      label: "English Composition, Rhetoric, and Language (ENGCOMP 3)",
      options: ["ENGL C1000", "ENGL C1000H"],
      required: true,
    },
    {
      id: "req-english-composition-courses",
      label: "English composition courses",
      options: ["ENGL C1001", "ENGL C1002", "ENGL C1002H", "ENGL C1001H", "PHIL 105", "PSYC 103"],
      required: true,
    },
    {
      id: "req-computer-programming-courses-c-preferred-b1",
      label: "Computer programming courses: C++ preferred — option 1 of 3",
      options: ["CSCI 1"],
      required: true,
      group: { id: "req-computer-programming-courses-c-preferred-opt", label: "Complete one full option for Computer programming courses: C++ preferred", count: 1, memberId: "req-computer-programming-courses-c-preferred-b1" },
    },
    {
      id: "req-computer-programming-courses-c-preferred-b2-p1",
      label: "Computer programming courses: C++ preferred — option 2 of 3, part 1 of 2",
      options: ["CSCI 3"],
      required: true,
      group: { id: "req-computer-programming-courses-c-preferred-opt", label: "Complete one full option for Computer programming courses: C++ preferred", count: 1, memberId: "req-computer-programming-courses-c-preferred-b2" },
    },
    {
      id: "req-computer-programming-courses-c-preferred-b2-p2",
      label: "Computer programming courses: C++ preferred — option 2 of 3, part 2 of 2",
      options: ["CSCI 2"],
      required: true,
      group: { id: "req-computer-programming-courses-c-preferred-opt", label: "Complete one full option for Computer programming courses: C++ preferred", count: 1, memberId: "req-computer-programming-courses-c-preferred-b2" },
    },
    {
      id: "req-computer-programming-courses-c-preferred-b3",
      label: "Computer programming courses: C++ preferred — option 3 of 3",
      options: ["CSCI 30"],
      required: true,
      group: { id: "req-computer-programming-courses-c-preferred-opt", label: "Complete one full option for Computer programming courses: C++ preferred", count: 1, memberId: "req-computer-programming-courses-c-preferred-b3" },
    },
  ],
};
