// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uc-berkeley · business.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-berkeley/facts/business.facts.json (verified UC facts, accessed 2026-07-02)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Berkeley · Business Administration, B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=79&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F79%2FMajor%2Fe15195a7-0cc9-4b8c-acf9-08ddbf3f4ee7 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_UC_BERKELEY_BUSINESS: RequirementSet = {
  school: "uc-berkeley",
  major: "business",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Berkeley, Business Administration, B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=79&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F79%2FMajor%2Fe15195a7-0cc9-4b8c-acf9-08ddbf3f4ee7",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 3,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: false,
    gpa: null,
    notes: "Berkeley does NOT offer TAG — confirmed by omission 2026-07-02: the official TAG page/matrix list exactly six TAG campuses (Davis, Irvine, Merced, Riverside, Santa Barbara, Santa Cruz).",
    sourceUrl: "https://admission.universityofcalifornia.edu/admission-requirements/transfer-requirements/uc-transfer-programs/transfer-admission-guarantee-tag.html",
  },
  majorPrep: [
    {
      id: "req-courses-that-satisfy-the-statistics-requirement-for-the-business-admin-major",
      label: "Courses that satisfy the Statistics requirement for the Business Admin major",
      options: ["STAT C1000", "STAT C1000H", "BUS 116"],
      required: true,
    },
    {
      id: "ugba-10x",
      label: "Foundations of Business (UGBA 10X)",
      options: ["BUS 101"],
      required: true,
    },
    {
      id: "econ-1-p1",
      label: "Introduction to Economics (ECON 1) — part 1 of 2 (complete all)",
      options: ["ECON C2002"],
      required: true,
    },
    {
      id: "econ-1-p2",
      label: "Introduction to Economics (ECON 1) — part 2 of 2 (complete all)",
      options: ["ECON C2001"],
      required: true,
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "math-52",
      label: "Calculus II (MATH 52)",
      options: ["MATH 191"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for CALCULUS.", count: 1, memberId: "g2-o1" },
    },
    // ASSIST row note: Option 1 of 2
    {
      id: "math-51",
      label: "Calculus I (MATH 51)",
      options: ["MATH 190"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for CALCULUS.", count: 1, memberId: "g2-o1" },
    },
    // ASSIST row note: Option 2 of 2
    {
      id: "math-16a",
      label: "Analytic Geometry and Calculus (MATH 16A)",
      options: ["MATH 165"],
      required: true,
      group: { id: "g2-opt", label: "Complete one of the 2 options for CALCULUS.", count: 1, memberId: "g2-o2" },
    },
    {
      id: "req-courses-that-satisfy-reading-composition-a-p1",
      label: "Courses that satisfy Reading & Composition A — part 1 of 2 (complete all)",
      options: ["ENGL C1000"],
      required: true,
    },
    {
      id: "req-courses-that-satisfy-reading-composition-a-p2",
      label: "Courses that satisfy Reading & Composition A — part 2 of 2 (complete all)",
      options: ["ENGL C1000H"],
      required: true,
    },
    {
      id: "req-courses-that-satisfy-reading-composition-b-p1",
      label: "Courses that satisfy Reading & Composition B — part 1 of 2 (complete all)",
      options: ["ENGL C1002"],
      required: true,
    },
    {
      id: "req-courses-that-satisfy-reading-composition-b-p2",
      label: "Courses that satisfy Reading & Composition B — part 2 of 2 (complete all)",
      options: ["ENGL C1002H"],
      required: true,
    },
  ],
};
