// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → csudh · psych.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/csu-dominguez-hills/facts/psych.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California State University, Dominguez Hills · Psychology B.A.  · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=50&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F50%2FMajor%2Fdd7d9d93-db0c-47f5-ac5f-08ddbf3f4ee7 (accessed 2026-08-19)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-19 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_CSUDH_PSYCH: RequirementSet = {
  school: "csudh",
  major: "psych",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California State University, Dominguez Hills, Psychology B.A. ",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=50&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F50%2FMajor%2Fdd7d9d93-db0c-47f5-ac5f-08ddbf3f4ee7",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-19",
    verification: 'unreviewed',
  },
  impacted: false,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "AA-T Psychology",
    grantsPriority: true,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: true,
      similarAdt: "AA-T Psychology",
      notes: "CSUDH’s catalog states that ADT holders \"are guaranteed admission with junior standing to a CSU and given priority admission over other transfer applicants when applying to a local CSU or non-impacted CSU program\" — and since every CSUDH program is non-impacted, that priority applies to this major. The similar-degree determination below is the CSU Chancellor’s Office’s own, read 2026-08-19 from the ADT Major & Campus Search (webapps.calstate.edu/sasdegreesearch, AjaxMethods.aspx/CreateCSUProgramList for campus \"Dominguez Hills\"; the tool reports its data last updated 07/08/2026). A similar degree also means the remaining requirements can be finished within 60 more semester units. The CSU search returns \"Psychology, BA\" as similar to the Psychology AA-T at CSUDH — a direct match, non-impacted, so both admission priority and the 60-unit guarantee apply.",
    },
    campusImpacted: "none",
    localAdmissionArea: "Not a gating factor at CSUDH. CSU local-admission areas matter only where a campus or program is impacted, and nothing at CSUDH is impacted for 2027-28, so there is no local-vs-non-local cutoff to clear — every one of the 20 sending colleges wired in this repo is admitted on the same 2.0 + Golden Four basis. CSUDH’s own local-service-area definition was not re-verified on 2026-08-19 because it does not affect admission here.",
    sourceUrl: "https://www.csudh.edu/future-students/transfer/admitted/admissions-requirements/",
  },
  majorPrep: [
    {
      id: "psy-101",
      label: "General Studies Psychology: Understanding Human Behavior (PSY 101)",
      options: ["PSYC C1000", "PSYC C1000H"],
      required: true,
    },
    {
      id: "psy-235",
      label: "Introduction to Research Methods (PSY 235)",
      options: ["SOCI 109B", "PSYC 109B"],
      required: true,
    },
    {
      id: "psy-230",
      label: "Elementary Statistical Analysis in Psychology (PSY 230)",
      options: ["SOCI 109A", "STAT C1000", "STAT C1000H", "PSYC 109A"],
      required: true,
    },
    {
      id: "psy-240",
      label: "Biopsychology (PSY 240)",
      options: ["PSYC 107"],
      required: true,
    },
  ],
};
