// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → uc-davis · psych.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/uc-davis/facts/psych.facts.json (verified UC facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Davis · Psychology A.B. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=89&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F89%2FMajor%2Fe16ebc5d-34f1-4b08-346c-08ddb349963e (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
export const REQ_ECC_UC_DAVIS_PSYCH: RequirementSet = {
  school: "uc-davis",
  major: "psych",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Davis, Psychology A.B.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=89&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F89%2FMajor%2Fe16ebc5d-34f1-4b08-346c-08ddb349963e",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: true,
  gpaTarget: 2.9,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: true,
    gpa: 3.2,
    notes: "UC Davis is one of the six TAG campuses. From the 2027-28 UC TAG matrix (fall 2027 / spring 2028 cycle, \"accurate as of June 9, 2026\") cross-checked against UC Davis's own TAG requirements page, both read 2026-08-19: 3.20 UC-transferable GPA for every major in the College of Agricultural and Environmental Sciences, the College of Biological Sciences and the College of Letters and Science; 3.50 in BOTH cumulative and major-preparation coursework for every College of Engineering major; GPA required by end of summer 2026. Fall quarter only, file Sept 1-30 via UC TAP, Cal-GETC/IGETC NOT required. Davis pre-evaluates and releases decisions mid-November — wait for the TAG decision before submitting the UC application. TAG-excluded at Davis: business, computer science, data science, undeclared programs, and the landscape architecture guarantee (pre-Landscape Architecture only).",
    sourceUrl: "https://admission.universityofcalifornia.edu/_assets/files/transfer-requirements/updated_202728-tag-matrix_ada.pdf",
  },
  majorPrep: [
    {
      id: "psc-001",
      label: "General Psychology (PSC 001)",
      options: ["PSYC C1000", "PSYC C1000H"],
      required: true,
    },
    {
      id: "sta-013",
      label: "Elementary Statistics (STA 013)",
      options: ["SOCI 109A", "PSYC 109A", "COMS 180", "STAT C1000H", "STAT C1000", "BUS 116"],
      required: true,
      group: { id: "g2-n1", label: "Select 1 course(s) from the following.", count: 1, memberId: "sta-013" },
    },
    // ASSIST row note: Option 1 of 4
    {
      id: "ant-001",
      label: "Human Evolutionary Biology (ANT 001)",
      options: ["ANTH 1"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 4 options for BIOLOGY.", count: 1, memberId: "g3-o1" },
    },
    // ASSIST row note: Option 1 of 4
    {
      id: "bis-010",
      label: "Everyday Biology (BIS 010)",
      options: ["BIOL 10", "BIOL 10H"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 4 options for BIOLOGY.", count: 1, memberId: "g3-o1" },
    },
    // ASSIST row note: Option 1 of 4
    {
      id: "bis-010-2",
      label: "Everyday Biology (BIS 010)",
      options: ["BIOL 10", "BIOL 10H"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 4 options for BIOLOGY.", count: 1, memberId: "g3-o2" },
    },
    // ASSIST row note: Option 3 of 4
    {
      id: "bis-002a",
      label: "Introduction to Biology: Essentials of Life on Earth (BIS 002A)",
      options: ["BIOL 110H", "BIOL 110"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 4 options for BIOLOGY.", count: 1, memberId: "g3-o3" },
    },
    // ASSIST row note: Option 4 of 4
    {
      id: "npb-010",
      label: "Elementary Human Physiology (NPB 010)",
      options: ["ANAT 32", "APHY 34A", "APHY 34B", "ANAT 30", "PHYO 31"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 4 options for BIOLOGY.", count: 1, memberId: "g3-o4" },
    },
    // ASSIST row note: Option 1 of 4
    {
      id: "bis-010-3",
      label: "Everyday Biology (BIS 010)",
      options: ["BIOL 10", "BIOL 10H"],
      required: true,
      group: { id: "g3-opt", label: "Complete one of the 4 options for BIOLOGY.", count: 1, memberId: "g3-o4" },
    },
    {
      id: "psc-041",
      label: "Research Methods in Psychology  (PSC 041)",
      options: ["PSYC 109B", "SOCI 109B"],
      required: false,
    },
  ],
};
