// [LOCAL DEMO — generated by scripts/gen-demo-requirements.ts; not wired into the
// atomic swap or DATA_VERSION] ecc → csu-sacramento · cs.
// facts (gpaTarget/impacted/adt/tag): data-sources/universities/csu-sacramento/facts/cs.facts.json (verified CSU facts, accessed 2026-08-19)
import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → California State University, Sacramento · Computer Science, BS · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=60&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F60%2FMajor%2Fb689aa3c-c0b2-4ea6-ad2b-08ddbf3f4ee7 (accessed 2026-08-20)
// verification: 'unreviewed' — flipping to 'verified' is a HUMAN act, after
// checking every row against the agreement PDF (see DATA_REQUIREMENTS).
// ASSIST header notes: Auto-transformed 2026-08-20 from the ASSIST detail JSON (X-XSRF-TOKEN method). required/recommended is a heuristic (nearest section heading; UCR lists most prep as "strongly recommended") — verify every flag in the human pass.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · CSC 15: Not Articulated
//   · CSC 20: Not Articulated
//   · CSC 28: Not Articulated
//   · CSC 35: Not Articulated
//   · CSC 60: Not Articulated
//   · MATH 35: No Comparable Course
//   · STAT 50: No Comparable Course
//   · BIO 10: Not Articulated
//   · CHEM 1E: No Comparable Course
export const REQ_ECC_CSU_SACRAMENTO_CS: RequirementSet = {
  school: "csu-sacramento",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → California State University, Sacramento, Computer Science, BS",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=60&agreementType=to&view=agreement&viewBy=major&viewByKey=76%2F103%2Fto%2F60%2FMajor%2Fb689aa3c-c0b2-4ea6-ad2b-08ddbf3f4ee7",
    catalogYear: "2025-2026",
    lastVerified: "2026-08-20",
    verification: 'unreviewed',
  },
  impacted: false,
  gpaTarget: 2,
  // Engine-facing adt derived from csu.adtGuarantee (deriveCsuAdt).
  adt: {
    available: true,
    name: "AS-T Computer Science (exists statewide, but Sacramento State designates NO similar major for it)",
    grantsPriority: false,
  },
  // CSU facts — advisory copy only (B1); never a verdict input. The ADT
  // guarantee is to the CSU SYSTEM, not this campus/major (rule 4).
  csu: {
    adtGuarantee: {
      available: true,
      similarMajorAtCampus: false,
      similarAdt: "AS-T Computer Science (exists statewide, but Sacramento State designates NO similar major for it)",
      notes: "This is the finding most likely to surprise a student, and it is checked twice. The Computer Science AS-T exists as one of the 48 statewide TMC degrees, so available:true. But Sacramento State does not treat it as similar to ANY Sacramento State program: the campus’s own ADT \"Similar\" Majors and Concentrations list (Rev. 06.2026) has no Computer Science row at all, and the CSU Chancellor’s Office ADT Major & Campus Search returns ZERO Sacramento programs for TMC key 2007 (Computer Science) — while returning results for that same key at other campuses. Both read 2026-08-19. Consequence: a Computer Science AS-T still guarantees admission SOMEWHERE in the CSU system with junior standing, but at Sacramento State it buys no campus priority for this major, no 60-remaining-units guarantee and no ENG 20 waiver. The route into the Sac State Computer Science B.S. is the ordinary transfer bar (2.0 + Golden Four + 60 units) plus the lower-division preparation in the ASSIST agreement, which is unusually deep for a non-impacted major — 16 receiving rows. This is the same shape of trap as Cal Poly Pomona mapping the CS ADT to Science, Technology & Society rather than its CS B.S.; it is worth telling a student before they commit to the AS-T for this campus. Re-verify when the ADT list revises (Sac State stamps it \"Rev. MM.YYYY\").",
    },
    campusImpacted: "none — the 2027-28 CSU Undergraduate Impacted Programs Matrix (July 2026) reads for this campus exactly: \"Sacramento: No campus impaction for FTF or UDT.  Impacted in business administration (all options), graphic design (general), and nursing (general).\" (https://www.calstate.edu/attend/impaction-at-the-csu/Documents/ImpactedProgramsMatrix.pdf, read 2026-08-19). Sacramento State says the same on its own impaction page: \"Campus-wide impaction has been lifted for the Fall 2024 Application Period. All applicants, local and non-local who meet the minimum requirements of the university will be considered for admission.\" So of the 13 majors wired here, exactly ONE — Business Administration — is impacted; the other twelve are admitted on the university’s ordinary transfer bar.",
    localAdmissionArea: "Sacramento State defines its local admission area by the COLLEGE ATTENDED, not by high school or county: \"A student transferring with the majority of units from one or more of the following community colleges is considered to be in Sacramento State’s local admission area: American River, Cosumnes River, Folsom Lake, Lake Tahoe, Sacramento City, Sierra, San Joaquin Delta, Solano, Woodland, and Yuba.\" Of the 20 sending colleges wired in this repo, exactly ONE is local: SIERRA COLLEGE. The other 19 (Cerritos, Chaffey, College of the Canyons, De Anza, Diablo Valley, East Los Angeles, El Camino, Fullerton, Irvine Valley, LA Pierce, Long Beach City, Modesto Junior, Moorpark, Mt. SAC, Orange Coast, Pasadena City, Riverside City, Saddleback, Santa Monica) are NON-local. Two consequences, both published: (1) the 2.0 minimum transfer GPA is stated for local-area applicants — for a non-local applicant \"the academic characteristics of the transfer applicant pool will determine the GPA minimum\", i.e. no number is published; (2) for the impacted Business Administration major, a local-area applicant receives a +0.1 boost to the cumulative GPA used for rank-ordering, stacking with the separate +0.1 an ADT earns. Note Diablo Valley College appears on Sac State’s ADT \"Transfer Ready\" partners list but NOT on the local-admission-area list, so it is a partner, not a local college. (https://www.csus.edu/apply/admissions/application-process/transfer-process.html, read 2026-08-19)",
    sourceUrl: "https://www.csus.edu/apply/admissions/application-process/transfer-process.html",
  },
  majorPrep: [
    {
      id: "math-30",
      label: "Calculus I (MATH 30)",
      options: ["MATH 190"],
      required: true,
    },
    {
      id: "math-31",
      label: "Calculus II (MATH 31)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "phys-11a",
      label: "General Physics: Mechanics (PHYS 11A)",
      options: ["PHYS 1A"],
      required: true,
    },
    {
      id: "bio-1",
      label: "Biodiversity, Evolution and Ecology (BIO 1)",
      options: ["BIOL 120"],
      required: false,
    },
    {
      id: "chem-1a",
      label: "General Chemistry I (CHEM 1A)",
      options: ["CHEM 1A"],
      required: false,
    },
    {
      id: "phys-11b-p1",
      label: "General Physics: Heat, Light, Sound, Modern Physics (PHYS 11B) — part 1 of 2 (complete all)",
      options: ["PHYS 1B"],
      required: false,
    },
    {
      id: "phys-11b-p2",
      label: "General Physics: Heat, Light, Sound, Modern Physics (PHYS 11B) — part 2 of 2 (complete all)",
      options: ["PHYS 1D"],
      required: false,
    },
    {
      id: "phys-11c",
      label: "General Physics: Electricity and Magnetism (PHYS 11C)",
      options: ["PHYS 1C"],
      required: false,
    },
  ],
};
