import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Riverside · Computer Science, B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=46&agreementType=to&view=agreement&viewBy=major (accessed 2026-06-11)
// verification: 'verified' — checked against the official ASSIST agreement
// (verified 2026-07-01; evidence in verification/ + the agreement JSON's verificationNote).
// ASSIST header notes: Official ASSIST PDF (Date Published 11/18/25; printed 6/11/26) — data-sources/assist-agreements/ucr-cs-2025-26.pdf. All Bourns College of Engineering majors are selective: minimum 2.80 GPA in all transferable coursework (baseline, not a guarantee). Prior to transfer, minimum 2.50 GPA in the calculus sequence and in at least one additional sequence. C++ proficiency is a required prerequisite to UCR CS 141 and most upper-division CS courses; students completing CS 10/12 equivalents without C++ proficiency may need a C++ course before upper-division enrollment. BCOE accepts IGETC as satisfying lower-division GE/breadth, but strongly encourages prioritizing technical preparation (math/science/CS below) over IGETC. Honors/enhanced/support variants articulate the same as the base course number. AP: CS A 4+ satisfies CS 10A; Calc AB 3+ (or AB subscore) satisfies MATH 9A; Calc BC 3+ satisfies MATH 9A+9B, BC 4+ satisfies MATH 9A+9B+9C.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · EE 20B: Strongly recommended; No Course Articulated at El Camino.
export const UCR_CS: RequirementSet = {
  school: "ucr",
  major: "cs",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Riverside, Computer Science, B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=46&agreementType=to&view=agreement&viewBy=major",
    catalogYear: "2025-2026",
    lastVerified: "2026-07-01",
    verification: 'verified',
  },
  impacted: true,
  gpaTarget: 2.8,
  adt: {
    available: false,
    name: null,
    grantsPriority: false,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: true,
    gpa: 3.6,
    notes: "UCR TAG via BCOE for Computer Science (fall-2026 cycle, 2026–27 matrix). The 3.6 TAG GPA is well above the 2.8 admission screen — they are different things. File in UC TAP Sept 1–30, fall term only; ~30 UC-transferable semester units by submission and 60 by end of spring, 2.0+ with no grade below C in the final year. UCR pre-evaluates TAG coursework — wait for the TAG decision before submitting the UC application. UCR is not accepting winter 2027 TAG applications. Re-check when the 2027-28 matrix posts.",
    sourceUrl: "https://admission.universityofcalifornia.edu/_assets/files/transfer-requirements/uc-tag-matrix_2026-2027.pdf",
  },
  majorPrep: [
    // ASSIST row note: An AP exam may be used to satisfy this course requirement (Computer Science A, score 4+).
    {
      id: "cs-10a",
      label: "Intro to Computer Science for Science, Mathematics, and Engineering I (CS 10A)",
      options: ["CSCI 1", "CSCI 3"],
      required: true,
    },
    {
      id: "cs-10b",
      label: "Intro to Computer Science for Science, Mathematics, and Engineering II (CS 10B)",
      options: ["CSCI 30"],
      required: true,
    },
    // ASSIST row note: ASSIST draws this as the receiving series MATH 9A AND 9B AND 9C articulated by the sending pair MATH 190 AND MATH 191 (verified against the PDF column layout). AP: Calc AB 3+ = MATH 9A; BC 3+ = 9A+9B; BC 4+ = the full series.
    {
      id: "math-9a-math-9b-math-9c-p1",
      label: "First-Year Calculus (full three-quarter series) (MATH 9A, MATH 9B, MATH 9C) — part 1 of 2 (complete all)",
      options: ["MATH 190"],
      required: true,
    },
    // ASSIST row note: ASSIST draws this as the receiving series MATH 9A AND 9B AND 9C articulated by the sending pair MATH 190 AND MATH 191 (verified against the PDF column layout). AP: Calc AB 3+ = MATH 9A; BC 3+ = 9A+9B; BC 4+ = the full series.
    {
      id: "math-9a-math-9b-math-9c-p2",
      label: "First-Year Calculus (full three-quarter series) (MATH 9A, MATH 9B, MATH 9C) — part 2 of 2 (complete all)",
      options: ["MATH 191"],
      required: true,
    },
    {
      id: "phys-40a",
      label: "General Physics (PHYS 40A)",
      options: ["PHYS 1A"],
      required: true,
    },
    // ASSIST row note: UCR CS 11 is the same course as UCR MATH 11.
    {
      id: "cs-11",
      label: "Intro to Discrete Structures (CS 11)",
      options: ["MATH 210"],
      required: true,
      group: { id: "cs-additional", label: "Additional preparation — select 3 courses (required for admission)", count: 3, memberId: "cs-11" },
    },
    {
      id: "cs-10c",
      label: "Intro to Data Structures and Algorithms (CS 10C)",
      options: ["CSCI 2"],
      required: true,
      group: { id: "cs-additional", label: "Additional preparation — select 3 courses (required for admission)", count: 3, memberId: "cs-10c" },
    },
    {
      id: "math-10a",
      label: "Calculus of Several Variables (MATH 10A)",
      options: ["MATH 220"],
      required: true,
      group: { id: "cs-additional", label: "Additional preparation — select 3 courses (required for admission)", count: 3, memberId: "math-10a" },
    },
    {
      id: "phys-40b",
      label: "General Physics (PHYS 40B)",
      options: ["PHYS 1B"],
      required: true,
      group: { id: "cs-additional", label: "Additional preparation — select 3 courses (required for admission)", count: 3, memberId: "phys-40b" },
    },
    {
      id: "phys-40c",
      label: "General Physics (PHYS 40C)",
      options: ["PHYS 1C"],
      required: true,
      group: { id: "cs-additional", label: "Additional preparation — select 3 courses (required for admission)", count: 3, memberId: "phys-40c" },
    },
    // ASSIST row note: Strongly recommended — ASSIST prints 'Select 1 course from the following' over MATH 31 and EE 20B.
    {
      id: "math-31",
      label: "Applied Linear Algebra (MATH 31)",
      options: ["MATH 270"],
      required: false,
    },
  ],
};
