import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Riverside · Psychology, B.A. and B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=46&agreementType=to&view=agreement&viewBy=major (accessed 2026-06-11)
// verification: 'verified' — checked against the official ASSIST agreement
// (verified 2026-07-01; evidence in verification/ + the agreement JSON's verificationNote).
// ASSIST header notes: Official ASSIST PDF (Date Published 11/18/25; printed 6/11/26) — data-sources/assist-agreements/ucr-psych-2025-26.pdf. Selective major: minimum 2.70 GPA (baseline, not a guarantee). All courses must be taken for a letter grade; courses count toward UCR Psychology major requirements only with a grade of C- or better. Transfer students must complete all lower-division requirements within one year of matriculation at UCR — complete as much as possible before transfer. IGETC or CAL-GETC encouraged (CAL-GETC completers may have an additional Language-other-than-English requirement at UCR); UCR CHASS breadth is the alternative. MATHEMATICS REQUIREMENT (effective fall 2018): a course equivalent to UCR MATH 4 or higher with C- or better is required for admission consideration; courses articulating as MATH 5A, 6A, 9A, or 22 qualify. A UC-transferable College Algebra course plus a college Trigonometry course (both C or better) is an acceptable substitution for MATH 5A (trig alone carries no UC transfer credit). BIOLOGICAL SCIENCES REQUIREMENT: one biological science course (courses approved as biological science on the college's IGETC pattern qualify — e.g. Biology, Marine Biology, Microbiology, Anatomy, Physiology). PHYSICAL SCIENCE REQUIREMENT: one physical science course, excluding Cultural Geography (IGETC physical-science approved courses qualify — e.g. Chemistry, Physics, Earth Sciences, Oceanography, Astronomy, Geology). ADDITIONAL REQUIREMENT: two more courses from the biological/physical science sections, or courses approved as Mathematics on the college's IGETC list (Statistics, Finite Math, College Algebra, Discrete Structures), or UC-transferable Computer Science courses; the course used for the MATH 4-equivalent may NOT be double-counted here. Honors/enhanced/support variants articulate the same as the base course number. AP: Calc AB 3+ satisfies MATH 9A; BC 3+ satisfies 9A+9B, BC 4+ satisfies 9A+9B+9C; Psychology 4+ satisfies PSYC 2.
// Not articulated at El Camino College — completed AFTER transfer (never counted as
// gaps against the student):
//   · PSYC 1: Strongly recommended; No Course Articulated at El Camino.
export const UCR_PSYCH: RequirementSet = {
  school: "ucr",
  major: "psych",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Riverside, Psychology, B.A. and B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=46&agreementType=to&view=agreement&viewBy=major",
    catalogYear: "2025-2026",
    lastVerified: "2026-07-01",
    verification: 'verified',
  },
  impacted: true,
  gpaTarget: 2.7,
  adt: {
    available: true,
    name: "AA-T Psychology",
    grantsPriority: true,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: true,
    gpa: 3.3,
    notes: "UCR TAG via CHASS for Psychology (fall-2026 cycle, 2026–27 matrix). CHASS's default TAG GPA is 2.8; Psychology is the 3.3 exception. File in UC TAP Sept 1–30, fall term only; ~30 UC-transferable semester units by submission and 60 by end of spring, 2.0+ with no grade below C in the final year. UCR pre-evaluates TAG coursework — wait for the TAG decision before submitting the UC application. UCR is not accepting winter 2027 TAG applications. Re-check when the 2027-28 matrix posts.",
    sourceUrl: "https://admission.universityofcalifornia.edu/_assets/files/transfer-requirements/uc-tag-matrix_2026-2027.pdf",
  },
  majorPrep: [
    // ASSIST row note: Alternative pair: MATH 130 (C- or better) AND MATH 170 (C- or better; content credit only — trigonometry carries no UC transfer units).
    {
      id: "math-5a-c1",
      label: "Principles of Calculus I (MATH 5A) — option set 1 of 2",
      options: ["MATH 180", "MATH 130"],
      required: true,
      group: { id: "psych-math", label: "Mathematics — select 1 course (required for admission; minimum grade C-)", count: 1, memberId: "math-5a" },
    },
    // ASSIST row note: Alternative pair: MATH 130 (C- or better) AND MATH 170 (C- or better; content credit only — trigonometry carries no UC transfer units).
    {
      id: "math-5a-c2",
      label: "Principles of Calculus I (MATH 5A) — option set 2 of 2",
      options: ["MATH 180", "MATH 170"],
      required: true,
      group: { id: "psych-math", label: "Mathematics — select 1 course (required for admission; minimum grade C-)", count: 1, memberId: "math-5a" },
    },
    // ASSIST row note: An AP exam may be used to satisfy this course requirement (Calc AB 3+).
    {
      id: "math-9a",
      label: "First-Year Calculus (MATH 9A)",
      options: ["MATH 190"],
      required: true,
      group: { id: "psych-math", label: "Mathematics — select 1 course (required for admission; minimum grade C-)", count: 1, memberId: "math-9a" },
    },
    {
      id: "math-22",
      label: "Calculus for Business (MATH 22)",
      options: ["MATH 165"],
      required: true,
      group: { id: "psych-math", label: "Mathematics — select 1 course (required for admission; minimum grade C-)", count: 1, memberId: "math-22" },
    },
    // ASSIST row note: Strongly recommended. An AP exam may be used (Psychology, score 4+).
    {
      id: "psyc-2",
      label: "Introductory Psychology (PSYC 2)",
      options: ["PSYC C1000"],
      required: false,
    },
    // ASSIST row note: Strongly recommended; No Course Articulated at El Camino.
    {
      id: "psyc-11",
      label: "Psychological Methods: Statistical Procedures (PSYC 11)",
      options: ["PSYC 109A", "SOCI 109A"],
      required: false,
    },
    // ASSIST row note: Strongly recommended; No Course Articulated at El Camino.
    {
      id: "psyc-12",
      label: "Psychological Methods: Research Procedures (PSYC 12)",
      options: ["PSYC 109B", "SOCI 109B"],
      required: false,
    },
  ],
};
