import type { RequirementSet } from '../../types';

// GENERATED by scripts/ingest from the transcribed ASSIST agreement.
// El Camino College → University of California, Riverside · Business Administration, B.S. · agreement year 2025-2026
// Source: https://assist.org/transfer/results?year=76&institution=103&agreement=46&agreementType=to&view=agreement&viewBy=major (accessed 2026-06-11)
// verification: 'verified' — checked against the official ASSIST agreement
// (verified 2026-07-01; evidence in verification/ + the agreement JSON's verificationNote).
// ASSIST header notes: Official ASSIST PDF (Date Published 11/18/25; printed 6/11/26) — data-sources/assist-agreements/ucr-business-2025-26.pdf. Selective major: minimum 2.70 GPA in all UC-transferable coursework AND minimum 2.50 GPA in the six lower-division major prerequisites (baseline for consideration, not a guarantee). Complete IGETC/CAL-GETC or the UCR CHASS breadth pattern. Managerial Accounting note: completing a lower-division managerial accounting course before transfer earns subject credit for UCR's upper-division BUS 108 (still must meet UCR upper-division unit minimums). A course articulated to MATH 9A (semester schools) is accepted in lieu of MATH 22. Honors/enhanced/support variants articulate the same as the base course number. AP: Macro 3+ satisfies ECON 2; Micro 3+ satisfies ECON 3; Calc AB 3+ (or AB subscore) satisfies MATH 9A; Calc BC 3+ satisfies MATH 9A+9B, BC 4+ satisfies MATH 9A+9B+9C; Statistics 4+ satisfies STAT 8.
export const UCR_BUSINESS: RequirementSet = {
  school: "ucr",
  major: "business",
  meta: {
    sourceName: "ASSIST articulation: El Camino College → University of California, Riverside, Business Administration, B.S.",
    sourceUrl: "https://assist.org/transfer/results?year=76&institution=103&agreement=46&agreementType=to&view=agreement&viewBy=major",
    catalogYear: "2025-2026",
    lastVerified: "2026-07-01",
    verification: 'verified',
  },
  impacted: true,
  gpaTarget: 2.7,
  adt: {
    available: true,
    name: "AS-T Business Administration 2.0",
    grantsPriority: true,
  },
  // UC TAG — advisory copy only (B1); never a verdict input.
  tag: {
    eligible: true,
    gpa: 2.8,
    notes: "UCR TAG via the School of Business (fall-2026 cycle, 2026–27 matrix). File in UC TAP Sept 1–30, fall term only; ~30 UC-transferable semester units by submission and 60 (junior standing) by end of spring, 2.0+ in all UC-transferable work with no grade below C in the final year. UCR pre-evaluates TAG coursework — wait for the TAG decision before submitting the UC application. UCR is not accepting winter 2027 TAG applications. Re-check when the 2027-28 matrix posts.",
    sourceUrl: "https://admission.universityofcalifornia.edu/_assets/files/transfer-requirements/uc-tag-matrix_2026-2027.pdf",
  },
  majorPrep: [
    {
      id: "bus-10",
      label: "Introduction to Business (BUS 10)",
      options: ["BUS 101"],
      required: true,
    },
    {
      id: "bus-20",
      label: "Financial Accounting and Reporting (BUS 20)",
      options: ["BUS 150"],
      required: true,
    },
    // ASSIST row note: An AP exam may be used to satisfy this course requirement (Macroeconomics, score 3+).
    {
      id: "econ-2",
      label: "Intro to Macroeconomics (ECON 2)",
      options: ["ECON C2002"],
      required: true,
    },
    // ASSIST row note: An AP exam may be used to satisfy this course requirement (Microeconomics, score 3+).
    {
      id: "econ-3",
      label: "Intro to Microeconomics (ECON 3)",
      options: ["ECON C2001"],
      required: true,
    },
    {
      id: "math-22",
      label: "Calculus for Business (MATH 22)",
      options: ["MATH 165"],
      required: true,
      group: { id: "bus-math", label: "Calculus — complete 1 course (MATH 22 or MATH 9A)", count: 1, memberId: "math-22" },
    },
    // ASSIST row note: An AP exam may be used (Calc AB 3+). A course articulated to MATH 9A is accepted in lieu of MATH 22.
    {
      id: "math-9a",
      label: "First-Year Calculus (MATH 9A)",
      options: ["MATH 190"],
      required: true,
      group: { id: "bus-math", label: "Calculus — complete 1 course (MATH 22 or MATH 9A)", count: 1, memberId: "math-9a" },
    },
    // ASSIST row note: An AP exam may be used to satisfy this course requirement (Statistics, score 4+).
    {
      id: "stat-8",
      label: "Statistics for Business (STAT 8)",
      options: ["STAT C1000"],
      required: true,
      group: { id: "bus-stats", label: "Statistics — complete 1 course (STAT 8 or STAT 10)", count: 1, memberId: "stat-8" },
    },
  ],
};
