import type { Course } from '../types';

// ECC course catalog — GENERATED by scripts/ingest from data-sources/ecc-catalog/courses.csv.
// Source: https://www.elcamino.edu/academics/catalog/ (catalog year 2025–26, accessed 2026-07-01).
// Transcription is UNREVIEWED until a human checks it against the source —
// update CATALOG_SOURCE in meta.ts when flipping verification.
// Do not hand-edit: fix the CSV and re-run `node scripts/ingest.ts`.
// igetc / calgetc = area ids satisfied per pattern; eccge = ECC local GE areas.
export const ECC_COURSES: Course[] = [
  // Anatomy
  { code: "ANAT 30", name: "Essentials of Anatomy and Physiology", dept: "Anatomy", units: 4, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [] },
  { code: "ANAT 32", name: "General Human Anatomy", dept: "Anatomy", units: 4, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [] },

  // Anthropology
  { code: "ANTH 1", name: "Introduction to Biological Anthropology", dept: "Anthropology", units: 3, igetc: ["5B"], calgetc: ["5B"], eccge: [] },
  { code: "ANTH 1H", name: "Honors Introduction to Biological Anthropology", dept: "Anthropology", units: 3, igetc: ["5B"], calgetc: ["5B"], eccge: [] },
  { code: "ANTH 5", name: "Biological Anthropology Laboratory", dept: "Anthropology", units: 1, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [] },
  { code: "ANTH 2", name: "Introduction to Cultural Anthropology", dept: "Anthropology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"] },
  { code: "ANTH 2H", name: "Honors Introduction to Cultural Anthropology", dept: "Anthropology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"] },
  { code: "ANTH 3", name: "Introduction to Archaeology", dept: "Anthropology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "ANTH 4", name: "Language and Culture", dept: "Anthropology", units: 3, igetc: ["3B", "3", "4"], calgetc: ["3B", "4"], eccge: [] },
  { code: "ANTH 4H", name: "Honors Language and Culture", dept: "Anthropology", units: 3, igetc: [], calgetc: ["3B", "4"], eccge: [] },
  { code: "ANTH 11", name: "Anthropology of Religion, Magic and Witchcraft", dept: "Anthropology", units: 3, igetc: ["3B", "3", "4"], calgetc: ["3B", "4"], eccge: [] },
  { code: "ANTH 6", name: "Native Peoples of North America", dept: "Anthropology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "ANTH 7", name: "Native Peoples of South America", dept: "Anthropology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "ANTH 8", name: "Ancient Civilizations of Mesoamerica", dept: "Anthropology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "ANTH 9", name: "Women, Culture, and Society", dept: "Anthropology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },

  // Anatomy and Physiology
  { code: "APHY 34A", name: "Anatomy and Physiology I", dept: "Anatomy and Physiology", units: 4, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [] },
  { code: "APHY 34B", name: "Anatomy and Physiology II", dept: "Anatomy and Physiology", units: 4, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [], prereqs: ["APHY 34A"] },

  // Astronomy
  { code: "ASTR 12", name: "Astronomy Laboratory", dept: "Astronomy", units: 1, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "ASTR 20", name: "The Solar System", dept: "Astronomy", units: 3, igetc: ["5A"], calgetc: ["5A"], eccge: [] },
  { code: "ASTR 20H", name: "Honors The Solar System", dept: "Astronomy", units: 3, igetc: ["5A"], calgetc: ["5A"], eccge: [] },
  { code: "ASTR 25", name: "Stars and Galaxies", dept: "Astronomy", units: 3, igetc: ["5A"], calgetc: ["5A"], eccge: [] },
  { code: "ASTR 25H", name: "Honors Stars and Galaxies", dept: "Astronomy", units: 3, igetc: ["5A"], calgetc: ["5A"], eccge: [] },
  { code: "ASTR 15", name: "Life in the Universe", dept: "Astronomy", units: 3, igetc: [], calgetc: ["5A"], eccge: [] },

  // Biology
  { code: "BIOL 10", name: "Fundamentals of Biology", dept: "Biology", units: 4, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: ["5"] },
  { code: "BIOL 10H", name: "Honors Fundamentals of Biology", dept: "Biology", units: 4, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: ["5"] },
  { code: "BIOL 11", name: "Fundamentals of Zoology", dept: "Biology", units: 4, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [] },
  { code: "BIOL 15", name: "Environmental Aspects of Biology", dept: "Biology", units: 3, igetc: ["5B"], calgetc: ["5B"], eccge: [] },
  { code: "BIOL 16", name: "Field Entomology", dept: "Biology", units: 4, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [] },
  { code: "BIOL 17", name: "Marine Biology", dept: "Biology", units: 3, igetc: ["5B"], calgetc: ["5B"], eccge: [] },
  { code: "BIOL 18", name: "Marine Biology Laboratory", dept: "Biology", units: 1, igetc: ["5B"], calgetc: ["5B"], eccge: [] },
  { code: "BIOL 110", name: "Cell and Molecular Biology", dept: "Biology", units: 5, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [] },
  { code: "BIOL 110H", name: "Honors Cell and Molecular Biology", dept: "Biology", units: 5, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [] },
  { code: "BIOL 120", name: "Ecology, Evolution, Diversity, and Physiology", dept: "Biology", units: 5, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [] },
  { code: "BIOL 120H", name: "Honors Ecology, Evolution, Diversity, and Physiology", dept: "Biology", units: 5, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [] },
  { code: "BIOL 130", name: "Fundamentals of Molecular Biology", dept: "Biology", units: 3, igetc: ["5B"], calgetc: ["5B"], eccge: [] },
  { code: "BIOL 8", name: "Biology of Plants", dept: "Biology", units: 4, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [] },
  { code: "BIOL 12", name: "Field Zoology", dept: "Biology", units: 4, igetc: [], calgetc: [], eccge: [] },

  // Business
  { code: "BUS 101", name: "Introduction to Business", dept: "Business", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "BUS 150", name: "Financial Accounting", dept: "Business", units: 4, igetc: [], calgetc: [], eccge: [] },
  { code: "BUS 108", name: "Written Business Communications", dept: "Business", units: 3, igetc: [], calgetc: [], eccge: ["1B"] },
  { code: "BUS 109", name: "Oral Business Communications", dept: "Business", units: 3, igetc: [], calgetc: [], eccge: ["1B"] },
  { code: "BUS 115", name: "Business Mathematics", dept: "Business", units: 3, igetc: [], calgetc: [], eccge: ["2"] },
  { code: "BUS 116", name: "Statistics for Business Decision Making", dept: "Business", units: 3, igetc: [], calgetc: ["2"], eccge: ["2"] },
  { code: "BUS 117", name: "Personal Finance", dept: "Business", units: 3, igetc: [], calgetc: [], eccge: ["2"] },
  { code: "BUS 120", name: "Business Management", dept: "Business", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "BUS 121", name: "Human Resources Management", dept: "Business", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "BUS 122", name: "Human Relations in Organizations", dept: "Business", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "BUS 126", name: "Accounting for Small Business", dept: "Business", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "BUS 151", name: "Managerial Accounting", dept: "Business", units: 4, igetc: [], calgetc: [], eccge: [] },

  // Chemistry
  { code: "CHEM 1A", name: "General Chemistry I", dept: "Chemistry", units: 5, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: ["5"] },
  { code: "CHEM 1B", name: "General Chemistry II", dept: "Chemistry", units: 5, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: ["5"] },
  { code: "CHEM 20", name: "Fundamentals of Chemistry", dept: "Chemistry", units: 5, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "CHEM 21A", name: "Survey of General and Organic Chemistry", dept: "Chemistry", units: 4, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "CHEM 21B", name: "Survey of Organic and Biochemistry", dept: "Chemistry", units: 4, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "CHEM 4", name: "Beginning Chemistry", dept: "Chemistry", units: 5, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "CHEM 4H", name: "Honors Beginning Chemistry", dept: "Chemistry", units: 5, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "CHEM 7A", name: "Organic Chemistry I", dept: "Chemistry", units: 5, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "CHEM 7B", name: "Organic Chemistry II", dept: "Chemistry", units: 5, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },

  // Chinese
  { code: "CHIN 1", name: "Elementary Chinese I", dept: "Chinese", units: 5, igetc: ["6"], calgetc: [], eccge: [] },
  { code: "CHIN 2", name: "Elementary Chinese II", dept: "Chinese", units: 5, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },

  // Communication Studies
  { code: "COMM C1000", name: "Introduction to Public Speaking", dept: "Communication Studies", units: 3, igetc: ["1C"], calgetc: ["1C"], eccge: ["1B"] },
  { code: "COMS 120", name: "Critical Thinking Through Argumentation and Debate", dept: "Communication Studies", units: 3, igetc: ["1C"], calgetc: [], eccge: ["1B"], prereqs: ["ENGL C1000"] },
  { code: "COMM C1004", name: "Interpersonal Communication", dept: "Communication Studies", units: 3, igetc: ["1C"], calgetc: [], eccge: ["1B"], formerCode: "COMS 130", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "COMS 140", name: "Small Group Communication", dept: "Communication Studies", units: 3, igetc: ["1C"], calgetc: [], eccge: ["1B"] },
  { code: "COMS 180", name: "Data-Driven Persuasion", dept: "Communication Studies", units: 4, igetc: ["2A"], calgetc: ["2"], eccge: ["2"] },
  { code: "COMM C1000H", name: "Introduction to Public Speaking - Honors", dept: "Communication Studies", units: 3, igetc: [], calgetc: ["1C"], eccge: [] },
  { code: "COMS 250", name: "Oral Interpretation of Literature", dept: "Communication Studies", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "COMS 260", name: "Introduction to Intercultural Communication", dept: "Communication Studies", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "COMS 265", name: "Mass Communication", dept: "Communication Studies", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "COMS 270", name: "Organizational Communication", dept: "Communication Studies", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "COMM C1004H", name: "Interpersonal Communication - Honors", dept: "Communication Studies", units: 3, igetc: [], calgetc: [], eccge: [], formerCode: "COMS 130H", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "COMS 120H", name: "Honors Critical Thinking Through Argumentation and Debate", dept: "Communication Studies", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "COMS 275", name: "Gender Communication", dept: "Communication Studies", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Computer Science
  { code: "CSCI 1", name: "Problem Solving and Program Design Using C++", dept: "Computer Science", units: 4, igetc: [], calgetc: [], eccge: [] },
  { code: "CSCI 2", name: "Introduction to Data Structures", dept: "Computer Science", units: 5, igetc: [], calgetc: [], eccge: [], prereqs: ["CSCI 1"] },
  { code: "CSCI 3", name: "Object-Oriented Programming in Java", dept: "Computer Science", units: 4, igetc: [], calgetc: [], eccge: [], prereqs: ["CSCI 1"] },
  { code: "CSCI 30", name: "Advanced Programming in C++", dept: "Computer Science", units: 4, igetc: [], calgetc: [], eccge: [], prereqs: ["CSCI 2"] },
  { code: "CSCI 14", name: "Introduction to Programming with Python", dept: "Computer Science", units: 4, igetc: [], calgetc: [], eccge: [] },
  { code: "CSCI 16", name: "Assembly Language Programming for x86 (IBM PC) Processors", dept: "Computer Science", units: 4, igetc: [], calgetc: [], eccge: [] },
  { code: "CSCI 17", name: "Computer Programming in MATLAB", dept: "Computer Science", units: 4, igetc: [], calgetc: [], eccge: [] },
  { code: "CSCI 7", name: "The Beauty of Computer Science Principles", dept: "Computer Science", units: 4, igetc: [], calgetc: [], eccge: ["2"] },
  { code: "CSCI 8", name: "Foundations of Data Science", dept: "Computer Science", units: 4, igetc: [], calgetc: [], eccge: ["2"] },
  { code: "CSCI 1H", name: "Honors Problem Solving and Program Design Using C++", dept: "Computer Science", units: 4, igetc: [], calgetc: [], eccge: [] },
  { code: "CSCI 40", name: "Introduction to UNIX and LINUX Operating Systems", dept: "Computer Science", units: 4, igetc: [], calgetc: [], eccge: [] },

  // Economics
  { code: "ECON C2002", name: "Principles of Macroeconomics", dept: "Economics", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"], formerCode: "ECON 101", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "ECON C2001", name: "Principles of Microeconomics", dept: "Economics", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"], prereqs: ["ECON C2002"], formerCode: "ECON 102", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "ECON 100", name: "Fundamentals of Economics", dept: "Economics", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"] },
  { code: "ECON C2002H", name: "Principles of Macroeconomics - Honors", dept: "Economics", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"], formerCode: "ECON 101H", formerCodeEffectiveTerm: "Fall 2026" },

  // English
  { code: "ENGL C1000", name: "Academic Reading and Writing", dept: "English", units: 4, igetc: ["1A"], calgetc: ["1A"], eccge: ["1A"] },
  { code: "ENGL C1000H", name: "Academic Reading and Writing - Honors", dept: "English", units: 4, igetc: ["1A"], calgetc: ["1A"], eccge: ["1A"] },
  { code: "ENGL C1001", name: "Critical Thinking and Writing", dept: "English", units: 4, igetc: ["1B"], calgetc: ["1B"], eccge: ["1B"] },
  { code: "ENGL C1001H", name: "Critical Thinking and Writing - Honors", dept: "English", units: 4, igetc: ["1B"], calgetc: ["1B"], eccge: ["1B"] },
  { code: "ENGL 1AE", name: "Reading and Composition for English Language Learners", dept: "English", units: 5, igetc: [], calgetc: ["1A"], eccge: ["1A"] },
  { code: "ENGL C1002", name: "Introduction to Literature", dept: "English", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: ["3"], formerCode: "ENGL 1B", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "ENGL C1002H", name: "Introduction to Literature - Honors", dept: "English", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: ["3"], formerCode: "ENGL 1BH", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "ENGL 12", name: "Introduction to Fiction", dept: "English", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "ENGL 15A", name: "Survey of British Literature I", dept: "English", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "ENGL 15B", name: "Survey of British Literature II", dept: "English", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "ENGL 20", name: "Shakespeare's Plays - Tragedies and Romances", dept: "English", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "ENGL 21", name: "Shakespeare's Plays - Comedies and Histories", dept: "English", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "ENGL 35", name: "World Literature: 3500 BCE to 1650 CE", dept: "English", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "ENGL 36", name: "World Literature: 1650 CE to Present", dept: "English", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "ENGL 40A", name: "American Literature I", dept: "English", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "ENGL 40B", name: "American Literature II", dept: "English", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "ENGL 44", name: "The Literature of American Ethnic Groups", dept: "English", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },

  // French
  { code: "FREN 1", name: "Elementary French I", dept: "French", units: 5, igetc: ["6"], calgetc: [], eccge: [] },
  { code: "FREN 2", name: "Elementary French II", dept: "French", units: 5, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "FREN 3", name: "Intermediate French I", dept: "French", units: 5, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "FREN 4", name: "Intermediate French II", dept: "French", units: 5, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },

  // Geography
  { code: "GEOG 1", name: "Physical Geography", dept: "Geography", units: 3, igetc: ["5A"], calgetc: ["5A"], eccge: [] },
  { code: "GEOG 6", name: "Physical Geography Laboratory", dept: "Geography", units: 1, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "GEOG 9", name: "Weather and Climate", dept: "Geography", units: 3, igetc: ["5A"], calgetc: ["5A"], eccge: [] },
  { code: "GEOG 2", name: "Cultural Geography", dept: "Geography", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "GEOG 5", name: "World Regional Geography", dept: "Geography", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "GEOG 7", name: "Geography of California", dept: "Geography", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },

  // Geology
  { code: "GEOL 1", name: "Physical Geology", dept: "Geology", units: 3, igetc: ["5A"], calgetc: ["5A"], eccge: [] },
  { code: "GEOL 15", name: "Natural Disasters", dept: "Geology", units: 3, igetc: ["5A"], calgetc: ["5A"], eccge: [] },
  { code: "GEOL 2", name: "History of Planet Earth", dept: "Geology", units: 3, igetc: ["5A"], calgetc: ["5A"], eccge: [] },
  { code: "GEOL 3", name: "Physical Geology Laboratory", dept: "Geology", units: 1, igetc: ["5A"], calgetc: ["5A"], eccge: [] },
  { code: "GEOL 30", name: "Geology Laboratory of Death Valley", dept: "Geology", units: 1, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "GEOL 32", name: "Geology Laboratory of Owens Valley and Sierra Nevada", dept: "Geology", units: 1, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "GEOL 34", name: "Geology Laboratory of Southeastern California", dept: "Geology", units: 1, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "GEOL 36", name: "Geology Laboratory of Coastal California", dept: "Geology", units: 1, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "GEOL 4", name: "History of Planet Earth Laboratory", dept: "Geology", units: 1, igetc: ["5A"], calgetc: ["5A"], eccge: [] },
  { code: "GEOL 7", name: "Environmental Science I", dept: "Geology", units: 3, igetc: ["5A"], calgetc: ["5A"], eccge: [] },

  // German
  { code: "GERM 1", name: "Elementary German I", dept: "German", units: 5, igetc: ["6"], calgetc: [], eccge: [] },
  { code: "GERM 2", name: "Elementary German II", dept: "German", units: 5, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },

  // Italian
  { code: "ITAL 1", name: "Elementary Italian I", dept: "Italian", units: 5, igetc: ["6"], calgetc: [], eccge: [] },
  { code: "ITAL 2", name: "Elementary Italian II", dept: "Italian", units: 5, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },

  // Japanese
  { code: "JAPA 1", name: "Elementary Japanese I", dept: "Japanese", units: 5, igetc: ["6"], calgetc: [], eccge: [] },
  { code: "JAPA 2", name: "Elementary Japanese II", dept: "Japanese", units: 5, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "JAPA 4", name: "Intermediate Japanese II", dept: "Japanese", units: 5, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },

  // Mathematics
  { code: "MATH 115", name: "Probability and Statistics for Prospective Elementary School Teachers", dept: "Mathematics", units: 3, igetc: ["2A"], calgetc: ["2"], eccge: ["2"] },
  { code: "MATH 120", name: "Liberal Arts Mathematics", dept: "Mathematics", units: 3, igetc: ["2A"], calgetc: ["2"], eccge: ["2"] },
  { code: "MATH 130", name: "College Algebra", dept: "Mathematics", units: 3, igetc: ["2A"], calgetc: ["2"], eccge: ["2"] },
  { code: "MATH 140", name: "Finite Mathematics for Business and Social Sciences", dept: "Mathematics", units: 4, igetc: ["2A"], calgetc: ["2"], eccge: ["2"] },
  { code: "MATH 165", name: "Calculus for Business and Social Sciences", dept: "Mathematics", units: 5, igetc: ["2A"], calgetc: ["2"], eccge: ["2"] },
  { code: "MATH 170", name: "Trigonometry", dept: "Mathematics", units: 3, igetc: [], calgetc: [], eccge: ["2"] },
  { code: "MATH 180", name: "Precalculus", dept: "Mathematics", units: 5, igetc: ["2A"], calgetc: ["2"], eccge: ["2"], prereqs: ["MATH 170"] },
  { code: "MATH 190", name: "Single Variable Calculus and Analytic Geometry I", dept: "Mathematics", units: 5, igetc: ["2A"], calgetc: ["2"], eccge: ["2"], prereqs: ["MATH 180"] },
  { code: "MATH 191", name: "Single Variable Calculus and Analytic Geometry II", dept: "Mathematics", units: 5, igetc: ["2A"], calgetc: ["2"], eccge: ["2"], prereqs: ["MATH 190"] },
  { code: "MATH 210", name: "Introduction to Discrete Structures", dept: "Mathematics", units: 5, igetc: ["2A"], calgetc: ["2"], eccge: ["2"], prereqs: ["MATH 190"] },
  { code: "MATH 220", name: "Multi-Variable Calculus", dept: "Mathematics", units: 5, igetc: ["2A"], calgetc: ["2"], eccge: ["2"], prereqs: ["MATH 191"] },
  { code: "MATH 270", name: "Differential Equations with Linear Algebra", dept: "Mathematics", units: 5, igetc: ["2A"], calgetc: ["2"], eccge: ["2"], prereqs: ["MATH 220"] },
  { code: "STAT C1000", name: "Introduction to Statistics", dept: "Mathematics", units: 4, igetc: ["2A"], calgetc: ["2"], eccge: ["2"] },
  { code: "STAT C1000H", name: "Introduction to Statistics - Honors", dept: "Mathematics", units: 4, igetc: ["2A"], calgetc: ["2"], eccge: ["2"] },
  { code: "MATH 110", name: "Structures and Concepts in Mathematics", dept: "Mathematics", units: 3, igetc: [], calgetc: [], eccge: ["2"] },
  { code: "MATH 116", name: "Geometry and Measurement for Prospective Elementary School Teachers", dept: "Mathematics", units: 3, igetc: [], calgetc: [], eccge: ["2"] },

  // Microbiology
  { code: "MICR 33", name: "General Microbiology", dept: "Microbiology", units: 5, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: [] },

  // Oceanography
  { code: "OCEA 10", name: "Introduction to Oceanography", dept: "Oceanography", units: 4, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },
  { code: "OCEA 10H", name: "Honors Introduction to Oceanography", dept: "Oceanography", units: 4, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: [] },

  // Philosophy
  { code: "PHIL 105", name: "Critical Thinking and Writing", dept: "Philosophy", units: 3, igetc: ["1B"], calgetc: ["1B"], eccge: ["1B"] },
  { code: "PHIL 105H", name: "Honors Critical Thinking and Writing", dept: "Philosophy", units: 3, igetc: ["1B"], calgetc: ["1B"], eccge: ["1B"] },
  { code: "PHIL 101", name: "Introduction to Philosophy", dept: "Philosophy", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: ["3"] },
  { code: "PHIL 101H", name: "Honors Introduction to Philosophy", dept: "Philosophy", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: ["3"] },
  { code: "PHIL 103", name: "Ethics and Society", dept: "Philosophy", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "PHIL 106", name: "Introduction to Symbolic Logic", dept: "Philosophy", units: 3, igetc: [], calgetc: [], eccge: ["1B"] },
  { code: "PHIL 107", name: "Philosophy of Religion", dept: "Philosophy", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "PHIL 111", name: "History of Ancient and Medieval Philosophy", dept: "Philosophy", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "PHIL 112", name: "History of Modern Philosophy", dept: "Philosophy", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "PHIL 113", name: "Contemporary Philosophy", dept: "Philosophy", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "PHIL 117", name: "Political Philosophy", dept: "Philosophy", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Physiology
  { code: "PHYO 31", name: "Human Physiology", dept: "Physiology", units: 4, igetc: ["5B", "5C"], calgetc: ["5B", "5C"], eccge: ["5"], prereqs: ["ANAT 32"] },

  // Physics
  { code: "PHYS 11", name: "Descriptive Introduction to Physics", dept: "Physics", units: 3, igetc: ["5A"], calgetc: ["5A"], eccge: [] },
  { code: "PHYS 1A", name: "Mechanics of Solids", dept: "Physics", units: 4, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: ["5"], prereqs: ["MATH 190"] },
  { code: "PHYS 1B", name: "Fluids, Heat and Sound", dept: "Physics", units: 3, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: ["5"], prereqs: ["PHYS 1A", "MATH 191"] },
  { code: "PHYS 1C", name: "Electricity and Magnetism", dept: "Physics", units: 4, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: ["5"], prereqs: ["PHYS 1A", "MATH 220"] },
  { code: "PHYS 1D", name: "Optics and Modern Physics", dept: "Physics", units: 4, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: ["5"], prereqs: ["PHYS 1C", "MATH 220"] },
  { code: "PHYS 2A", name: "General Physics", dept: "Physics", units: 4, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: ["5"] },
  { code: "PHYS 2B", name: "General Physics", dept: "Physics", units: 4, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: ["5"] },
  { code: "PHYS 3A", name: "General Physics with Calculus", dept: "Physics", units: 5, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: ["5"] },
  { code: "PHYS 3B", name: "General Physics with Calculus", dept: "Physics", units: 5, igetc: ["5A", "5C"], calgetc: ["5A", "5C"], eccge: ["5"] },

  // Physical Science
  { code: "PSCI 25", name: "Exploring Physical Sciences", dept: "Physical Science", units: 3, igetc: ["5A"], calgetc: ["5A"], eccge: [] },

  // Psychology
  { code: "PSYC 103", name: "Critical Thinking and Psychology", dept: "Psychology", units: 3, igetc: ["1B"], calgetc: ["1B"], eccge: ["1B"] },
  { code: "PSYC 103H", name: "Honors Critical Thinking and Psychology", dept: "Psychology", units: 3, igetc: ["1B"], calgetc: ["1B"], eccge: ["1B"] },
  { code: "PSYC 107", name: "Physiological Psychology", dept: "Psychology", units: 3, igetc: ["5B"], calgetc: ["5B"], eccge: ["5"] },
  { code: "PSYC 109A", name: "Introduction to Statistics and Data Analysis for the Behavioral Sciences", dept: "Psychology", units: 4, igetc: ["2A"], calgetc: ["2"], eccge: ["2"], prereqs: ["PSYC C1000"] },
  { code: "PSYC 109B", name: "Research Methods in the Behavioral Sciences", dept: "Psychology", units: 4, igetc: [], calgetc: [], eccge: [], prereqs: ["PSYC C1000"] },
  { code: "PSYC C1000", name: "Introduction to Psychology", dept: "Psychology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"] },
  { code: "PSYC 102", name: "Psychology for Effective Living", dept: "Psychology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["7"] },
  { code: "PSYC 108", name: "Social Psychology", dept: "Psychology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "PSYC 110", name: "African American Psychology", dept: "Psychology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "PSYC 112", name: "Human Sexuality", dept: "Psychology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "PSYC 115", name: "Abnormal Psychology", dept: "Psychology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "PSYC 116", name: "Lifespan Development", dept: "Psychology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["7"] },
  { code: "PSYC 117", name: "Cultural Psychology", dept: "Psychology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "PSYC 119", name: "LGBTQ+ Psychology", dept: "Psychology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "PSYC 125", name: "The Psychology of Gender", dept: "Psychology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "PSYC C1000H", name: "Introduction to Psychology - Honors", dept: "Psychology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"] },

  // Sign Language
  { code: "ASL 111", name: "American Sign Language I", dept: "Sign Language", units: 4, igetc: ["6"], calgetc: [], eccge: [], formerCode: "SLAN 111", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "SLAN 130", name: "Deaf Culture", dept: "Sign Language", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Sociology
  { code: "SOCI 109A", name: "Introduction to Statistics and Data Analysis for the Behavioral Sciences", dept: "Sociology", units: 4, igetc: ["2A"], calgetc: ["2"], eccge: ["2"], prereqs: ["PSYC C1000"] },
  { code: "SOCI 109B", name: "Research Methods in the Behavioral Sciences", dept: "Sociology", units: 4, igetc: [], calgetc: [], eccge: [], prereqs: ["SOCI 109A"] },
  { code: "SOCI 101", name: "Introduction to Sociology", dept: "Sociology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"] },
  { code: "SOCI 101H", name: "Honors Introduction to Sociology", dept: "Sociology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"] },
  { code: "SOCI 102", name: "Families and Intimate Relationships", dept: "Sociology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "SOCI 104", name: "Social Problems", dept: "Sociology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "SOCI 107", name: "Issues of Race and Ethnicity in the United States", dept: "Sociology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "SOCI 108", name: "Global Perspectives on Race and Ethnicity", dept: "Sociology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "SOCI 110", name: "Introduction to Social Work", dept: "Sociology", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "SOCI 112", name: "Introduction to Criminology", dept: "Sociology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "SOCI 113", name: "Gender and Society", dept: "Sociology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "SOCI 115", name: "Sociology of Death and Dying", dept: "Sociology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "SOCI 118", name: "Sociology of Sexualities", dept: "Sociology", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "SOCI 107H", name: "Honors Issues of Race and Ethnicity in the United States", dept: "Sociology", units: 3, igetc: [], calgetc: ["4"], eccge: [] },

  // Spanish
  { code: "SPAN 1", name: "Elementary Spanish I", dept: "Spanish", units: 5, igetc: ["6"], calgetc: [], eccge: [] },
  { code: "SPAN 1H", name: "Honors Elementary Spanish I", dept: "Spanish", units: 5, igetc: ["6"], calgetc: [], eccge: [] },
  { code: "SPAN 52A", name: "Spanish for Native Speakers I", dept: "Spanish", units: 5, igetc: ["3B", "3", "6"], calgetc: ["3B"], eccge: [] },
  { code: "SPAN 52B", name: "Spanish for Native Speakers II", dept: "Spanish", units: 5, igetc: ["3B", "3", "6"], calgetc: ["3B"], eccge: [] },
  { code: "SPAN 2", name: "Elementary Spanish II", dept: "Spanish", units: 5, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "SPAN 3", name: "Intermediate Spanish I", dept: "Spanish", units: 5, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },
  { code: "SPAN 4", name: "Intermediate Spanish II", dept: "Spanish", units: 5, igetc: ["3B", "3"], calgetc: ["3B"], eccge: [] },

  // Art History
  { code: "ARTH C1100", name: "Survey of Art from Prehistory to the Medieval Era", dept: "Art History", units: 3, igetc: ["3A", "3"], calgetc: ["3A"], eccge: [], formerCode: "AHIS 102A", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "ARTH C1100H", name: "Survey of Art from Prehistory to the Medieval Era - Honors", dept: "Art History", units: 3, igetc: ["3A", "3"], calgetc: ["3A"], eccge: [], formerCode: "AHIS 102AH", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "ARTH C1200", name: "Survey of Art from the Renaissance to Contemporary", dept: "Art History", units: 3, igetc: ["3A", "3"], calgetc: ["3A"], eccge: [], formerCode: "AHIS 102B", formerCodeEffectiveTerm: "Fall 2026" },

  // Administration of Justice
  { code: "AJ 100", name: "Introduction to Administration of Justice", dept: "Administration of Justice", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },

  // Contemporary Health
  { code: "C H 1", name: "Personal and Community Health Issues", dept: "Contemporary Health", units: 3, igetc: [], calgetc: [], eccge: ["7"] },
  { code: "C H 5", name: "Contemporary Women's Health", dept: "Contemporary Health", units: 3, igetc: [], calgetc: [], eccge: ["7"] },

  // Computer Information Systems
  { code: "CIS 13", name: "Computer Information Systems", dept: "Computer Information Systems", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "CIS 26", name: "Using Microsoft Excel", dept: "Computer Information Systems", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Ethnic Studies
  { code: "ESTU 1", name: "Introduction to Ethnic Studies", dept: "Ethnic Studies", units: 3, igetc: ["4"], calgetc: ["4", "6"], eccge: ["4", "6"] },
  { code: "ESTU 3", name: "The Chicano in Contemporary United States Society", dept: "Ethnic Studies", units: 3, igetc: ["4"], calgetc: ["4", "6"], eccge: ["4", "6"] },
  { code: "ESTU 5", name: "Chicano Culture", dept: "Ethnic Studies", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"] },
  { code: "ESTU 9", name: "Introduction to Asian Pacific Islander Desi American Studies", dept: "Ethnic Studies", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Human Development
  { code: "HDEV 110", name: "Learning and Development in College and Career", dept: "Human Development", units: 3, igetc: [], calgetc: [], eccge: ["7"] },
  { code: "HDEV 115", name: "Career Development Across the Lifespan", dept: "Human Development", units: 3, igetc: [], calgetc: [], eccge: ["7"] },

  // History
  { code: "HIST C1001", name: "United States History to 1877", dept: "History", units: 3, igetc: ["3B", "3", "4"], calgetc: ["3B", "4"], eccge: ["4"], formerCode: "HIST 101", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "HIST C1001H", name: "United States History to 1877 - Honors", dept: "History", units: 3, igetc: ["3B", "3"], calgetc: ["3B", "4"], eccge: ["4"], formerCode: "HIST 101H", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "HIST C1002", name: "United States History since 1865", dept: "History", units: 3, igetc: ["3B", "3", "4"], calgetc: ["3B", "4"], eccge: ["4"], formerCode: "HIST 102", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "HIST C1002H", name: "United States History since 1865 - Honors", dept: "History", units: 3, igetc: ["3B", "3", "4"], calgetc: ["3B", "4"], eccge: ["4"], formerCode: "HIST 102H", formerCodeEffectiveTerm: "Fall 2026" },
  { code: "HIST 140", name: "History of Early Civilizations", dept: "History", units: 3, igetc: ["3B", "3", "4"], calgetc: ["3B", "4"], eccge: [] },
  { code: "HIST 141", name: "History of Modern Civilizations", dept: "History", units: 3, igetc: ["3B", "3", "4"], calgetc: ["3B", "4"], eccge: [] },
  { code: "HIST 152", name: "History of Latin America through Independence", dept: "History", units: 3, igetc: ["3B", "3", "4"], calgetc: ["3B", "4"], eccge: [] },
  { code: "HIST 154", name: "A History of Mexico", dept: "History", units: 3, igetc: [], calgetc: ["4"], eccge: [] },
  { code: "HIST 105", name: "Women and American History from the Colonial Era to 1877", dept: "History", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "HIST 106", name: "Women and American History from 1877 to the Present", dept: "History", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "HIST 108", name: "United States History: The American Indian Experience", dept: "History", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "HIST 110", name: "The African American in the United States to 1877", dept: "History", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "HIST 111", name: "The African American in the United States from 1877 to the Present", dept: "History", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "HIST 112", name: "History of the Chicano in the United States", dept: "History", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "HIST 114", name: "History of the Asian American in the United States", dept: "History", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "HIST 122", name: "United States Social History: Cultural Pluralism in America", dept: "History", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "HIST 122H", name: "Honors United States Social History: Cultural Pluralism in America", dept: "History", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Humanities
  { code: "HUMA 1", name: "An Introduction to the Humanities", dept: "Humanities", units: 3, igetc: ["3B", "3"], calgetc: ["3B"], eccge: ["3"] },

  // Law
  { code: "LAW 4", name: "Legal Environment of Business", dept: "Law", units: 4, igetc: [], calgetc: [], eccge: [] },
  { code: "LAW 5", name: "Business Law", dept: "Law", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Nutrition Science
  { code: "NUTR 110", name: "Introduction to Nutrition Science", dept: "Nutrition Science", units: 3, igetc: [], calgetc: [], eccge: ["7"] },

  // Physical Education
  { code: "PE 212", name: "Sport and Society", dept: "Physical Education", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["7"] },
  { code: "PE 266", name: "Stress Management for Healthy Living", dept: "Physical Education", units: 3, igetc: [], calgetc: [], eccge: ["7"] },
  { code: "PE 277", name: "Introduction to Kinesiology", dept: "Physical Education", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 2A", name: "Walking for Fitness", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 2B", name: "Power Walking for Fitness", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 3", name: "Boot Camp Fitness Training", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 4A", name: "Beginning Basketball", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 4B", name: "Intermediate Basketball", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 7", name: "Baseball", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 10A", name: "Body Conditioning & Physical Fitness", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 10B", name: "Intermediate Body Conditioning and Physical Fitness", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 18A", name: "Beginning Boxing", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 19", name: "Boxing for Fitness", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 54A", name: "Beginning Weight Training", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 54B", name: "Intermediate Weight Training", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 57ABC", name: "Intercollegiate Swimming Teams", dept: "Physical Education", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 74A", name: "Beginning Soccer", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 79", name: "Futsal/Indoor Soccer", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 204", name: "Badminton", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 208A", name: "Beginning Bowling", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 208B", name: "Intermediate Bowling", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 220A", name: "Naginata - A Japanese Martial Art", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 220B", name: "Intermediate Naginata: A Japanese Martial Art", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 221", name: "Combative Arts and Self Defense", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 224", name: "Golf", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 239", name: "Slow Pitch Softball", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 240A", name: "Beginning Swimming", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 240B", name: "Intermediate Swimming", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 240C", name: "Advanced Swimming", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 245", name: "Water Aerobics", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 249", name: "Swimming for Fitness", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 250", name: "Techniques of Surfboard Riding", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 251A", name: "Beginning Tennis", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 251B", name: "Intermediate Tennis", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 252A", name: "Beginning Pickleball", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 252B", name: "Intermediate Pickleball", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 253", name: "Volleyball", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 254", name: "Cardio Fitness and Body Sculpting", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 255", name: "Beach Volleyball", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 257", name: "Yoga for Health and Fitness", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 258", name: "Power Vinyasa Yoga", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 259", name: "Circuit Training", dept: "Physical Education", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "PE 280", name: "Exercise and Nutrition Programs for Fitness and Weight Management", dept: "Physical Education", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Political Science
  { code: "POLI 2", name: "Introduction to Comparative Politics", dept: "Political Science", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "POLS C1000", name: "American Government and Politics", dept: "Political Science", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"] },
  { code: "POLS C1000H", name: "American Government and Politics - Honors", dept: "Political Science", units: 3, igetc: ["4"], calgetc: ["4"], eccge: ["4"] },
  { code: "POLI 3", name: "Introduction to Principles and Methods of Political Science", dept: "Political Science", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "POLI 5", name: "Ethnicity in the American Political Process", dept: "Political Science", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "POLI 6", name: "Civil Rights and Liberties in the United States", dept: "Political Science", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },
  { code: "POLI 7", name: "Political Philosophy", dept: "Political Science", units: 3, igetc: ["3B", "3", "4"], calgetc: ["3B", "4"], eccge: [] },
  { code: "POLI 10", name: "Introduction to International Relations", dept: "Political Science", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "POLI 10H", name: "Honors Introduction to International Relations", dept: "Political Science", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Supervision
  { code: "SUPV 109", name: "Oral Business Communications", dept: "Supervision", units: 3, igetc: [], calgetc: [], eccge: ["1B"] },

  // American Studies
  { code: "ASTU 7", name: "History of American Popular Culture", dept: "American Studies", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Women's Studies
  { code: "WSTU 1", name: "Introduction of Women's Studies", dept: "Women's Studies", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },

  // First Aid
  { code: "FAID 1", name: "First Aid, Cardiopulmonary Resuscitation (CPR) and Basic Emergency Care", dept: "First Aid", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Computer Aided Design/Drafting
  { code: "CADD 5", name: "Introduction to Mechanical Drafting", dept: "Computer Aided Design/Drafting", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "CADD 7", name: "Solid Modeling, Assemblies and Two Dimensional (2D) Drawings", dept: "Computer Aided Design/Drafting", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Engineering
  { code: "ENGR 1", name: "Introduction to Engineering", dept: "Engineering", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "ENGR 11", name: "Circuit Analysis", dept: "Engineering", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "ENGR 12", name: "Circuit Analysis Laboratory", dept: "Engineering", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "ENGR 9", name: "Engineering Mechanics - Statics", dept: "Engineering", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "ENGR 15", name: "Engineering Graphics", dept: "Engineering", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "ENGR 10", name: "Dynamics", dept: "Engineering", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Film/Video
  { code: "FILM 110", name: "Film Appreciation", dept: "Film/Video", units: 3, igetc: ["3A", "3"], calgetc: ["3A"], eccge: [] },

  // HDEV
  { code: "HDEV 110H", name: "Honors Learning and Development in College and Career", dept: "HDEV", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Journalism
  { code: "JOUR 12", name: "Mass Media and Society", dept: "Journalism", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },

  // SSCI
  { code: "SSCI 103", name: "Introduction to Social Justice Studies", dept: "SSCI", units: 3, igetc: ["4"], calgetc: ["4"], eccge: [] },

  // Art
  { code: "ART 161", name: "Beginning Ceramics", dept: "Art", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Computer Aided Design
  { code: "CADD 22", name: "Introduction to 3D Design with SolidWorks", dept: "Computer Aided Design", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "CADD 43", name: "Design Process and Concepts", dept: "Computer Aided Design", units: 4.5, igetc: [], calgetc: [], eccge: [] },

  // Dance
  { code: "DANC 110", name: "Beginning Dance", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 120A", name: "Beginning Ballet A", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 120B", name: "Beginning Ballet B", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 130A", name: "Beginning Contemporary Modern Dance A", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 130B", name: "Beginning Contemporary Modern Dance B", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 140", name: "Jazz Dance I", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 161", name: "Tap Dance I - Beginning", dept: "Dance", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 162", name: "Hip Hop Dance", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 163", name: "Beginning Belly Dancing", dept: "Dance", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 165", name: "African Dance", dept: "Dance", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 167", name: "Social and Ballroom Dance", dept: "Dance", units: 1, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 168", name: "Latin Social Dance", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 220A", name: "Intermediate Ballet A", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 220B", name: "Intermediate Ballet B", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 230A", name: "Intermediate Contemporary Modern Dance A", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 230B", name: "Intermediate Contemporary Modern Dance B", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 240", name: "Jazz Dance II", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 250", name: "Introduction to Pilates", dept: "Dance", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 261", name: "Tap Dance II - Intermediate", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 262", name: "Commercial Dance", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 265", name: "Intermediate African Dance", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },
  { code: "DANC 268", name: "Intermediate Latin Social Dance", dept: "Dance", units: 2, igetc: [], calgetc: [], eccge: [] },

  // Electronics
  { code: "ECHT 130", name: "Digital Systems and Computer Logic I", dept: "Electronics", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Engineering Technology
  { code: "ETEC 12", name: "Introduction to Engineering Design", dept: "Engineering Technology", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "ETEC 16", name: "Computer Ingetrated Manufacturing", dept: "Engineering Technology", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "ETEC 18", name: "Engineering Design and Development", dept: "Engineering Technology", units: 3, igetc: [], calgetc: [], eccge: [] },

  // LGBTQ Studies
  { code: "LGBT 101", name: "Introduction to LGBTQ+ Studies", dept: "LGBTQ Studies", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Linguistics
  { code: "LING 1A", name: "Linguistics 1A: An Introduction to Language and Culture", dept: "Linguistics", units: 3, igetc: [], calgetc: [], eccge: [] },
  { code: "LING 1B", name: "Linguistics 1B: Introduction to Language and Culture II", dept: "Linguistics", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Medical Technology
  { code: "MEDT 1", name: "Medical Terminology", dept: "Medical Technology", units: 3, igetc: [], calgetc: [], eccge: [] },

  // Social Science
  { code: "SSCI 103H", name: "Honors Introduction to Social Justice Studies", dept: "Social Science", units: 3, igetc: [], calgetc: [], eccge: [] },
];

export const getCourse = (code: string) => ECC_COURSES.find((c) => c.code === code);
